### ISSUE TITLE
Pyccel's grammer get confused between FunctionKind and the actual function name.

### ISSUE THREAD

**Issue by MostafaMamouni** [pyccel/pyccel#1025]
**Describe the bug**
In the case of a user names her/his function `function`, Pyccel grammar will recognize `function` as a `functionKind` and will expect the name of the actual function which will cause an error in the parsing.

**To Reproduce**
```python
def function(i: 'int', b: 'int'):
    return i + b
```

the error message:
```bash
textx.exceptions.TextXSyntaxError: None:1:19: error: Expected Static or ID at position (1, 19) => 'r function*(int,int)'.
```

**Expected behavior**
make sure that there is a function name then collect its optional `functionKind`'s

**Language**
C/Fortran
**Additional context**
functionKind static is also related to this problem.

**Comment by nhamidn** [comment]
caused by https://github.com/pyccel/pyccel/blob/352fff96d5bfe563507af337dbd956f74aa6c3c9/pyccel/parser/grammar/headers.tx#L33
