### ISSUE TITLE
Numpy_version.h not generated

### ISSUE THREAD

**Issue by EmilyBourne** [pyccel/pyccel#1092]
**Describe the bug**
Under very specific circumstances the code will not compile as the file `numpy_version.h` is not created.

**To Reproduce**
There are several steps required to reproduce this bug:

1. Compile code requiring a cwrapper using ndarrays (generates `numpy_version.h`)
2. Modify `pyccel/stdlib/cwrapper/cwrapper_ndarrays.h`
3. Recompile code

In the last step, the following happens:
1. Check to copy `cwrapper` info (this is the stage that generates `numpy_version.h`). Nothing happens as `cwrapper.h` and `cwrapper.c` exist and are up to date
2. Check to copy `cwrapper_ndarray` info. The code recognises that the file `pyccel/stdlib/cwrapper/cwrapper_ndarrays.h` needs updating so it deletes the `__pyccel__/cwrapper` folder (containing `numpy_version.h`)
3. Copy the `cwrapper` folder to collect the updated `pyccel/stdlib/cwrapper/cwrapper_ndarrays.h` file. This time the `numpy_version.h` is not corrected

To fix the problem we simply need to move the `cwrapper_ndarray` files to their own folder

**Extra notes**
This problem could theoretically be triggered by a clock skew

**Comment by dominikbell** [comment]
To me, this issue doesn't seem resolved.

I run a Ubuntu 22.04 virtual machine on a MacOS host system and this error still appears, e.g. when using any psydac functionality with the PSYDAC_BACKEND_GPYCCEL flags (anthing that need compilation).

See also [this issue](https://github.com/pyccel/psydac/issues/227) which I guess is titled incorrectly: The dominating error is the `numpy_version.h` error and the `OSError: Directory not empty` is a consequence of that.

**Comment by EmilyBourne** [comment]
In the issue you reference you seem to be running tests in parallel. I wonder if this could cause the issue. There might be a file lock missing. I was never able to reliably reproduce it so I couldn't investigate. The file should be created [here](https://github.com/pyccel/pyccel/blob/master/pyccel/codegen/utilities.py#L85-L87) via [here](https://github.com/pyccel/pyccel/blob/master/pyccel/codegen/python_wrapper.py#L77-L79). If you can reproduce it reliably then it would be great if you could add some prints around this part of the code to see what is going on.

Once the problem has occurred it won't go away unless you delete the `__pyccel__` folder as it is only created when the folder is copied which only happens if the folder doesn't already exist

**Comment by dominikbell** [comment]
Yes, I think it is only a problem when running codes in parallel. The code in the psydac issue produces this error always when run in parallel with mpi but never when run with only a single core.

I can also run it in parallel resulting in the error and then - without deleting any folders - run it with a single process and it runs through just fine.

I will try to investigate further and will let you know if I find anything.

**Comment by dominikbell** [comment]
Adding print statements before and after [here](https://github.com/pyccel/pyccel/blob/master/pyccel/codegen/python_wrapper.py#L77-L79) will be printed twice (when running the code in the psydac issue with `mpirun -n 2` but then only once the before print is executed and then the error pops up.

I don't know if this helps much, is there a possibility to see which process number is executing a command, i.e. does this function inside `python_wrapper.py` have access to the MPI communicator?

**Comment by EmilyBourne** [comment]
If you're using mpi then you should be able to import mpi4py and check the thread.

That said, epyccel with mpi ought to run the translation once (see [here](https://github.com/pyccel/pyccel/blob/master/pyccel/epyccel.py#L274)). Are you translating the same file multiple times or using mpi to handle multiple files at the same time?

**Comment by dominikbell** [comment]
I did the following:
- I added `print(f'rank {rank} has lib_dest_path : {lib_dest_path}')` before the [while loop in `utilities.py`](https://github.com/pyccel/pyccel/blob/master/pyccel/codegen/utilities.py#L69) (in `utilities.py`) as you asked
- I added `print(f'rank {rank} now calls copy_internal_library() for the first time')` before [the first time that `copy_internal_library() is called`](https://github.com/pyccel/pyccel/blob/master/pyccel/codegen/python_wrapper.py#L77-L79) (in `python_wrapper.py`)
- I added `print(f'rank {rank} now calls copy_internal_library() for the second time')` before [the second time that `copy_internal_library()` is called](https://github.com/pyccel/pyccel/blob/master/pyccel/codegen/python_wrapper.py#L115) (in `python_wrapper.py`)
- I added `print(f'rank {rank} from python_wrapper has lib_dest_path : {lib_dest_path}')` after [the second time that `copy_internal_library()` is called](https://github.com/pyccel/pyccel/blob/master/pyccel/codegen/python_wrapper.py#L115) (in `python_wrapper.py`)

The output is the following:
```
rank 0 now calls copy_internal_library() for the first time
rank 0 has lib_dest_path : /home/ubuntu/Struphy/hylife/__gpyccel__/__epyccel__/__pyccel__/cwrapper
rank 0 now calls copy_internal_library() for the second time
rank 0 has lib_dest_path : /home/ubuntu/Struphy/hylife/__gpyccel__/__epyccel__/__pyccel__/ndarrays
rank 0 from python_wrapper has lib_dest_path : /home/ubuntu/Struphy/hylife/__gpyccel__/__epyccel__/__pyccel__/ndarrays
rank 0 now calls copy_internal_library() for the second time
rank 0 has lib_dest_path : /home/ubuntu/Struphy/hylife/__gpyccel__/__epyccel__/__pyccel__/cwrapper_ndarrays
rank 0 from python_wrapper has lib_dest_path : /home/ubuntu/Struphy/hylife/__gpyccel__/__epyccel__/__pyccel__/cwrapper_ndarrays
rank 1 now calls copy_internal_library() for the first time
rank 1 has lib_dest_path : /home/ubuntu/Struphy/hylife/__gpyccel__/__epyccel__/__pyccel__/cwrapper
rank 0 now calls copy_internal_library() for the first time
rank 0 has lib_dest_path : /home/ubuntu/Struphy/hylife/__gpyccel__/__epyccel__/__pyccel__/cwrapper
```
so it seems that rank 0 is calling `copy_internal_library()` a few times (with success) but as soon as rank 1 tries to call this function something goes wrong.

**Comment by EmilyBourne** [comment]
Can you add a print at the end to see if rank 0 has finished when rank 1 starts? In theory they shouldn't be able to execute [this code](https://github.com/pyccel/pyccel/blob/master/pyccel/codegen/utilities.py#L70-L87) at the same time.
A few prints [here](https://github.com/pyccel/pyccel/blob/master/pyccel/codegen/utilities.py#L69-L87) to check:
- the value of `to_copy`
- the value of `outdated`

could also be useful

**Comment by dominikbell** [comment]
Adding a few print statements it appears that rank 1 makes it through to the `return` statement of `utilities.copy_internal_library()` with `to_copy = True` and `outdated = True`. Then rank 0 starts and makes it up until the [`if outdated` clause](https://github.com/pyccel/pyccel/blob/master/pyccel/codegen/utilities.py#L79) but fails at the [`shutil.rmtree(lib_dest_path)` command](https://github.com/pyccel/pyccel/blob/master/pyccel/codegen/utilities.py#L80)

**Comment by EmilyBourne** [comment]
The `rmtree` error is easy, it seems we should be doing: `shutil.rmtree(lib_dest_path, ignore_errors=True)`.

I'm not sure why it thinks the generated folder is outdated though. Maybe the src/destination files have absolute names. Can you add:
```
print(src_files)
print(dst_files)
```
after [these lines](https://github.com/pyccel/pyccel/blob/master/pyccel/codegen/utilities.py#L74-L75), and
```
print([os.path.getmtime(os.path.join(lib_path, s)) for s in src_files])
print([os.path.getmtime(os.path.join(lib_dest_path, s)) for s in src_files])
```
before [this line](https://github.com/pyccel/pyccel/blob/master/pyccel/codegen/utilities.py#L78)

Does rank 1 raise an error? As long as it exits the `with` in some way before rank 0 enters I'm not too worried for now

**Comment by dominikbell** [comment]
The first two lines give the output:
```
rank 0 src_files : ['cwrapper.c', 'cwrapper.h']
rank 0 dst_files : []
```
of the second two lines, only the first one gives a print
```
rank 0 (lib_path, s in src_files) : [1656350969.7336876, 1656350969.7336876]
```
but the second raises the error: `FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/Struphy/hylife/__gpyccel__/__epyccel__/__pyccel__/cwrapper/cwrapper.c'`.

Note that this is all for rank 0 already.

Also, the error raised by [line 80](https://github.com/pyccel/pyccel/blob/master/pyccel/codegen/utilities.py#L80) has been "fixed" by the `ignore_errors=True`, but now [line 83](https://github.com/pyccel/pyccel/blob/master/pyccel/codegen/utilities.py#L83) raises another error: `FileExistsError: [Errno 17] File exists: '/home/ubuntu/Struphy/hylife/__gpyccel__/__epyccel__/__pyccel__/cwrapper'`. This function does not accept a `ignore_errors` argument.

**Comment by EmilyBourne** [comment]
And it gives the same output each time? That's very odd. That would seem to imply that something is deleting the folder. Does struphy clean up after itself?

> Also, the error raised by line 80 has been "fixed" by the ignore_errors=True, but now line 83 raises another error: FileExistsError: [Errno 17] File exists: '/home/ubuntu/Struphy/hylife/__gpyccel__/__epyccel__/__pyccel__/cwrapper'. This function does not accept a ignore_errors argument.

This definitely looks like a race condition. `ignore_errors=True` should let it delete the folder even if it isn't empty so the folder definitely shouldn't exist at line 83. If it does it's because something else created it

**Comment by EmilyBourne** [comment]
The only thing that makes sense is that the lock isn't working. Can you see the lock file in the folder? I might have to borrow your computer next week to confirm

**Comment by dominikbell** [comment]
The code is pure psydac + pyccel; the folder in which the file with code is in is called `"Struphy/hylife"`.

The `/__gpyccel__/__epyccel__/__pyccel__/cwrapper/` folder it is complaining about is actually empty ...

In the `/__gpyccel__/__epyccel__/__pyccel__/` folder there are a lot of `.lock` files. There a lot starting with `"bind_c_dependencies_"` + some random numbers and letters that differ for each file, then there are ones starting with `"dependencies_"` + some randomness. There are also three folders: `"cwrapper"`, `"cwrapper_ndarrays"`, and `"ndarrays"`. For each of the folder there is a `.lock` file; the `cwrapper.lock` file is empty, though.

I will not be there next week, my flight is on the 25th, but we can have a Zoom meeting this afternoon, if it is okay with you. Let me know on RocketChat.

**Comment by EmilyBourne** [comment]
> The /__gpyccel__/__epyccel__/__pyccel__/cwrapper/ folder it is complaining about is actually empty ...

This seems strange. Either it should have deleted the folder or it should have created it with its contents. An empty folder is suspicious.

> In the /__gpyccel__/__epyccel__/__pyccel__/ folder there are a lot of .lock files. There a lot starting with "bind_c_dependencies_" + some random numbers and letters that differ for each file, then there are ones starting with "dependencies_" + some randomness.

This sounds like psydac is generating files called "dependencies_" + some randomness and then translating them with pyccel.

> There are also three folders: "cwrapper", "cwrapper_ndarrays", and "ndarrays". For each of the folder there is a .lock file; the cwrapper.lock file is empty, though.

I think the lock files are usually empty, [filelock](https://py-filelock.readthedocs.io/en/latest/index.html) creates/opens the file in a way that forces other threads to wait until it's finished before creating/opening it themselves. But the file isn't actually used for anything else

**Comment by dominikbell** [comment]
So the time we found (1656350969.0) was June 27th, so probably the time I installed pyccel. The problem is with the files in `lib_dest_path`.

When I change the call of the modification time (`getmtime`) [of the destination files](https://github.com/pyccel/pyccel/blob/master/pyccel/codegen/utilities.py#L78) to getting the last access time (`getatime`) the code runs through fine without any issue.

I don't know if this will cause any other problems down the road, though.

**Comment by EmilyBourne** [comment]
> So the time we found (1656350969.0) was June 27th, so probably the time I installed pyccel. The problem is with the files in `lib_dest_path`.
> 
> When I change the call of the modification time (`getmtime`) [of the destination files](https://github.com/pyccel/pyccel/blob/master/pyccel/codegen/utilities.py#L78) to getting the last access time (`getatime`) the code runs through fine without any issue.
> 
> I don't know if this will cause any other problems down the road, though.

It shouldn't do. These files are never modified, only copied

**Comment by EmilyBourne** [comment]
Can you test PR #1158 without `getatime`. I can then change to `getatime` once I know it's working
