### ISSUE TITLE
Operations on numpy arrays with python types return the wrong type

### ISSUE THREAD

**Issue by EmilyBourne** [pyccel/pyccel#1105]
**Describe the bug**
Arithmetic operations between a numpy object and a pure python object return objects with the wrong type. The numpy type should be prioritised

**To Reproduce**
Provide code to reproduce the behavior:
```python
import numpy as np

def get_int_array():
    a = np.ones(5, dtype=np.int32)
    b = a*2
    return b[0]
```
The type of the result should be `numpy.int32`

Provide the generated code, or the error message:
```fortran
  !........................................
  subroutine get_int_array()

    implicit none

    integer(i32), allocatable :: a(:)
    integer(i64), allocatable :: b(:)

    allocate(a(0:4_i64))
    a = 1_i32
    allocate(b(0:4_i64))
    b = a * 2_i64
    if (allocated(a)) then
      deallocate(a)
    end if
    if (allocated(b)) then
      deallocate(b)
    end if

  end subroutine get_int_array
  !........................................
```

**Expected behavior**
The numpy type should be prioritised

**Comment by EmilyBourne** [comment]
The type is wrong because the precision is set wrong. The precision is selected in the `_calculate_dtype` functions in `pyccel/ast/operators.py`

**Comment by Pinkyboi** [comment]
@bauom  I checked the `_calculate_dtype` functions and they seems like the problem comes from `max_precision` choosing the the type with the maximum precision, but since at this point of the execution both the dtypes for the numpy object and the pure python types are `NativeIntiger` in this case i was wondering if there's a way to know if one of them is a numpy type to prioritize it.

**Comment by EmilyBourne** [comment]
> @bauom I checked the `_calculate_dtype` functions and they seems like the problem comes from `max_precision` choosing the the type with the maximum precision, but since at this point of the execution both the dtypes for the numpy object and the pure python types are `NativeIntiger` in this case i was wondering if there's a way to know if one of them is a numpy type to prioritize it.

Pure python types have default precision (-1), while numpy types have fixed precision (usually 4 or 8)

**Comment by EmilyBourne** [comment]
@Pinkyboi I think this issue and #1135 are quite similar. You may want to fix both together to avoid making changes which turn out not to work in the more general case considered in #1135

**Comment by Pinkyboi** [comment]
@EmilyBourne roger that ! ill look into both issues.
