### ISSUE TITLE
Strides not implemented for Fortran preventing passing slices to functions

### ISSUE THREAD

**Issue by flohol** [pyccel/pyccel#1117]
I have the pyccelized function

```python
def fun(x : 'int[:]'):
    for i in range(len(x)):
    	print(x[i], ' ')
    print()
```

in `file.py` which just prints the entries of the integer input array `x`.

Running the code 

```python
import numpy as np
from file import fun

A = np.ones((5, 5))
nz = np.nonzero(A)

print('Array passed to pyccelized function : ', nz[0])
print('-----------------------------------------------')

# pass array nz[0]
print(nz[0].flags)
fun(nz[0])
print('-----------------------------------------------')

# pass a copy of the array nz[0]
print(nz[0].copy().flags)
fun(nz[0].copy())
```

reveals that passing the output `nz[0]` of `np.nonzero(A)` to the pyccelized function `fun` gives a wrong order because `nz[0]` is neither F nor C contiguous. Using a copy `nz[0].copy()` instead (which is both F and C contiguous) fixes the problem.

Output:
```
Array passed to pyccelized function :  [0 0 0 0 0 1 1 1 1 1 2 2 2 2 2 3 3 3 3 3 4 4 4 4 4]
-----------------------------------------------
  C_CONTIGUOUS : False
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

0 0 0 1 0 2 0 3 0 4 1 0 1 1 1 2 1 3 1 4 2 0 2 1 2 
-----------------------------------------------
  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

0 0 0 0 0 1 1 1 1 1 2 2 2 2 2 3 3 3 3 3 4 4 4 4 4
```

**Language**
Fortran

**Comment by EmilyBourne** [comment]
Hi,
Thanks for your interest in pyccel, and thanks for opening this issue. I thought we already had an issue for this but it seems we forgot to open it! The problem arises because we don't currently pass the strides to Fortran. In C this is done so your example works when translating to C

**Comment by EmilyBourne** [comment]
This problem must be fixed in the c-Fortran wrapper (bind c). In order to be compatible with c, arrays in the wrapper are declared with F77 syntax. This syntax does not allow for the definition of a stride, however the resulting array can be sliced when it is passed in the function call.

This solution will work well in most cases however currently it will cause a bug for optional arrays. If we try to slice an array which is not present the code will crash. It is therefore important to fix issue #929 before tackling this problem

**Comment by yguclu** [comment]
If we want to fully support slices we need to pass three separate integer arguments for each dimension: `(start, end, step)`. Is this what is done in PR #1388?

**Comment by EmilyBourne** [comment]
I have just run a quick test. `start` is indeed necessary for certain cases. However in these cases the data is no longer C-contiguous or F-contiguous. As a result we don't know what order to treat the dimensions in so currently the array is rejected anyway

**Comment by EmilyBourne** [comment]
This parameter could easily be added, but it requires a few steps:
1. Check if the NumPy strides are ordered in an increasing or decreasing pattern (F vs C)
2. Add `start` to `t_ndarray`
3. Add `start` to `BindCFunctionDefArgument`
4. Add `start` to the `FunctionCall` in the `BindCFunctionDef`

I recommend that this be done separately with a new dedicated issue to ensure that the ordering issue is correctly explored

**Comment by yguclu** [comment]
I agree, this deserves a separate issue. We should discuss about it with @bauom.

**Comment by EmilyBourne** [comment]
I don't think so. #1218 is about assigning a 1D array to a 2D array (bad loop unrolling). The code that is generated therefore does not compile.

This issue is about the wrappers not exposing the strides to Fortran leading to the wrong elements being accessed (but no compilation problem)

**Comment by yguclu** [comment]
> I have just run a quick test. `start` is indeed necessary for certain cases. However in these cases the data is no longer C-contiguous or F-contiguous. As a result we don't know what order to treat the dimensions in so currently the array is rejected anyway. In fact it is not contiguous at all so this currently only works for 1D arrays.

Indeed, if we slice a multi-dimensional array using strides we end up with a view that is not contiguous at all. In Pyccel row-major or column-major is information needed just for the order to print the indices, and we can extract it from the `base` array which is always stored contiguously.

As for the `start` argument, when Numpy creates a view it computes the location of the first element and stores a pointer to it. Later when indexing the view the correct location of an element is computed using just the `strides`. I suppose that we could emulate this in Fortran by passing the pointer to the correct location. (?)

**Comment by EmilyBourne** [comment]
> > I have just run a quick test. `start` is indeed necessary for certain cases. However in these cases the data is no longer C-contiguous or F-contiguous. As a result we don't know what order to treat the dimensions in so currently the array is rejected anyway. In fact it is not contiguous at all so this currently only works for 1D arrays.
> 
> Indeed, if we slice a multi-dimensional array using strides we end up with a view that is not contiguous at all. In Pyccel row-major or column-major is information needed just for the order to print the indices, and we can extract it from the `base` array which is always stored contiguously.
> 
> As for the `start` argument, when Numpy creates a view it computes the location of the first element and stores a pointer to it. Later when indexing the view the correct location of an element is computed using just the `strides`. I suppose that we could emulate this in Fortran by passing the pointer to the correct **start** location of the view. (?)
> 

Indeed in Fortran we would have to emulate this as NumPy doesn't provide us with the original array just the pointer to the correct **start** location of the view.
