### ISSUE TITLE
Can't pass an unnamed array to a function in C

### ISSUE THREAD

**Issue by EmilyBourne** [pyccel/pyccel#1126]
**Describe the bug**
When passing an array created on the fly to a function, the code will not translate to C.

**To Reproduce**
Provide code to reproduce the behavior:
```python
import numpy as np

def f(a : 'int[:]'):
    print(a)

if __name__ == '__main__':
    f(np.array([1,2,3]))
```

Provide the generated code, or the error message:
```bash/fortran/c
ERROR at code generation stage
pyccel:
 |fatal [codegen]: tmp.py [7,6]| _print_NumpyArray is not yet implemented for language : C
Pyccel has encountered syntax that has not been implemented yet. Please create an issue at https://github.com/pyccel/pyccel/issues and provide a small example of your problem. Do not forget to specify your target language ((1, 2, 3))
```

**Expected behavior**
The C printer should create a temporary variable in which the array can be stored before calling the function

**Language**
C

**Additional information**
The above code translates to Fortran correctly. The code below translates to both Fortran and C:
```python
import numpy as np

def f(a : 'int[:]'):
    print(a)

if __name__ == '__main__':
    x = np.array([1,2,3])
    f(x)
```

**Comment by Pinkyboi** [comment]
@azouiten are you still planning to work on this issue ?

**Comment by azouiten** [comment]
> @azouiten are you still planning to work on this issue ?
> 

Yes, I apologise for the delay.
