### ISSUE TITLE
List comprehensions with anonymous iterators don't work

### ISSUE THREAD

**Issue by thinkwelltwd** [pyccel/pyccel#1131]
**Describe the bug**
I just discovered pyccel and was testing it against a toy light switch problem where 100 (x) switches are toggled by 100 (x) people, where the first person toggles every first switch, the 2nd person toggles every second switch, 3rd person every 3rd, etc. After all 100 people have toggled the switches, how many are ON?

**To Reproduce**

```python
def switches(count: int) -> int:
    """
    >>> switches(100)
    10
    >>> switches(1000)
    31
    >>> switches(10000)
    100
    >>> switches(100000)
    316
    >>> switches(1000000)
    1000
    """
    switches = [False for _ in range(count)]
    switch = 0

    while switch < count:

        person = switch + 1
        sw = switch
        while sw < count:
            switches[sw] = not switches[sw]
            sw += person
        switch = person

    on = 0
    for i in switches:
        if i:
            on += 1
    return on

# The correct answers are in the doc strings above, 
# but pyccelized code gets the wrong answers < 10000 switches

>>> switches(100)
48
>>> switches(1000)
497
>>> switches(10000)
100
>>> switches(100000)
316
>>> switches(1000000)
1000
```

**Expected behavior**
The accelerated function should return the same values as the pure python code.

**Language**
C

**Additional context**
This is the first time I've ever done anything with pyccel, so I may well be doing something wrong!

**Comment by EmilyBourne** [comment]
Thank you for your interest in pyccel! And thank you for your bug report. You are not doing anything wrong you have indeed found a bug.

It seems the error is coming from the comprehension expression: `switches = [False for _ in range(count)]`. For some reason this is translated to:
```c
    switches = array_create(1, (int64_t[]){count}, nd_bool, false);
    Dummy_0000 = 0;
    for (Dummy_0000 = 0; Dummy_0000 < count; Dummy_0000 += 1)
    {
        GET_ELEMENT(switches, nd_bool, (int64_t)Dummy_0000) = 0;
        Dummy_0000 = Dummy_0000 + 1;
    }
```
instead of:
```c
    switches = array_create(1, (int64_t[]){count}, nd_bool, false);
    Dummy_0000 = 0;
    for (Dummy_0000 = 0; Dummy_0000 < count; Dummy_0000 += 1)
    {
        GET_ELEMENT(switches, nd_bool, (int64_t)Dummy_0000) = 0;
    }
```
This error only occurs when the iterator is temporary so one temporary fix would be to use : `switches = [False for j in range(count)]`

**Comment by EmilyBourne** [comment]
This particular issue exists in all translations. But it seems that currently functional statements are not supported in C (the tests [here](https://github.com/pyccel/pyccel/blob/master/tests/epyccel/test_functionals.py) only test Fortran). 1D functionals work in C but not 2D functionals
