### ISSUE TITLE
pyccel/parser/semantic.py is too large to be analysed by codacy

### ISSUE THREAD

**Issue by EmilyBourne** [pyccel/pyccel#1140]
`pyccel/parser/semantic.py` is too large to be analysed by codacy. We should think about breaking up the file. In the meantime we should be extra careful with pull requests.

cc: @saidctb @yguclu

**Comment by yguclu** [comment]
I don't know what to suggest, as that file contains only the class `SemanticParser`...

**Comment by EmilyBourne** [comment]
I don't really have any ideas either. We could potentially extract out the utility functions.

In any case we need to bear in mind that this file isn't being scanned

**Comment by yguclu** [comment]
> Alternatively we could fix the 8 pylint errors currently in the file and add the pylint scan of this file to the github CI. It's not ideal, but at least that way it's tested

I think this is a great idea!
