### ISSUE TITLE
add topics

### ISSUE THREAD

**Issue by Beliavsky** [pyccel/pyccel#1164]
I suggest adding the topics `transpiler`, `python` in the About section, since Pyccel can translate Python to Fortran.

**Comment by EmilyBourne** [comment]
Duplicate of #1073  ?

**Comment by EmilyBourne** [comment]
I just realised that I misunderstood this issue. It is not about adding extra documentation but adding extra keywords to the About section:
![Screenshot from 2022-08-28 08-45-45](https://user-images.githubusercontent.com/25363473/187061364-b74edb61-415d-43d3-9680-3a02eda6bddb.png)

@yguclu @ratnania you are the only people who can fix this issue

**Comment by ratnania** [comment]
done
