### ISSUE TITLE
Add numpy.sign function

### ISSUE THREAD

**Issue by EmilyBourne** [pyccel/pyccel#1165]
**Describe the bug**
Add numpy.sign function

**Test Code**
Provide code which does not currently work but which should do when this issue is fixed:
```python
a = sign(-1)
```

**Comment by aihya** [comment]
I wonder if this function should deal with non-arrays only.

**Comment by EmilyBourne** [comment]
> I wonder if this function should deal with non-arrays only.

No, it is a numpy function so it should definitely deal with arrays too. Fortran probably has a vectorised function already though, and in C the unravelling should be done automatically if the `is_elemental` property is correctly set

**Comment by EmilyBourne** [comment]
See https://fortranwiki.org/fortran/show/elemental for a definition of the concept of "elemental"

**Comment by aihya** [comment]
@EmilyBourne
`numpy.sign(x, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])` what the arguments `out`, `where`... should they be supported too?

**Comment by EmilyBourne** [comment]
> @EmilyBourne `numpy.sign(x, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])` What the arguments `out`, `where`... should they be supported too?

The arguments are documented [here](https://numpy.org/doc/stable/reference/generated/numpy.sign.html)

The `out` argument exists for several functions. It ensures that memory allocation is not required. E.g:
```python
a = np.sign(x) # internally allocates space for a
b = np.empty_like(a) # internally allocates space for b
np.sign(x, out=b) # assigns values in b
# now a and b are copies of one another
```
It seems that the `where` argument only makes sense when the `out` argument is also specified.

I'm not sure what is currently supported for our other functions. Missing arguments should be specified in our [documentation](https://github.com/pyccel/pyccel/blob/master/tutorial/numpy-functions.md). I don't see anything specified for `floor` for example which has the following similar signature:
```python
numpy.floor(x, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
```
but I am not convinced that everything is supported nonetheless. You can check. You should support at least as much as `floor`. If you see an easy way to implement other arguments, then you can add this. Otherwise I think this can be left for a separate PR which can deal with all implemented ufuncs. In this case you should open an additional issue describing the work that needs to be done

**Comment by aihya** [comment]
> I'm not sure what is currently supported for our other functions.

I tested other functions (e.g. `floor`, `abs`) with other arguments and pyccel complains, it says `Function call cannot be processed.`
Most function don't seem to add the arguments other then `x`.

**Comment by EmilyBourne** [comment]
Checking the code, we can see that these functions inherit from `NumpyUfuncUnary` (see for example [floor](https://github.com/pyccel/pyccel/blob/master/pyccel/ast/numpyext.py#L1249-L1255)). The constructor of this class is defined [here](https://github.com/pyccel/pyccel/blob/1d7ad9604a6dd23dc8f380a1253291132cb52ed7/pyccel/ast/numpyext.py#L1103-L1111). It does indeed only support `x`. If you want to add additional arguments and can see how this should be done then you should add them to this class so it fixes this problem for all the functions

**Comment by EmilyBourne** [comment]
For example some of these arguments are supported by `NumpyFullLike` so this could provide you a guide to how to treat these values
