### ISSUE TITLE
[JOSS] Contribution and authorship

### ISSUE THREAD

**Issue by aholmes** [pyccel/pyccel#1243]
Hello,

Regarding openjournals/joss-reviews#4991 - on reviewing "contribution and authorship" I noticed this repository has 24 contributors, while the paper has four authors listed. Is this correct?

**Comment by yguclu** [comment]
Hi, the paper was written by the project creators, maintainers, and main contributors over several years of work. These are the 4 authors of the paper.

We try to keep an up-to-date list with the names of every person who has made significant contributions to the Pyccel library in the [AUTHORS](https://github.com/pyccel/pyccel/blob/master/AUTHORS) file, as is standard practice for a large open-source project.

In the paper we thank all contributors in the **Acknowledgment** section.
