### ISSUE TITLE
[JOSS] Reproducibility - consider locking dependency versions

### ISSUE THREAD

**Issue by aholmes** [pyccel/pyccel#1249]
Regarding openjournals/joss-reviews#4991

Hello,

One aspect of reproducibility involves the dependencies used to make any software. Dependencies change often from one release to another, sometimes dramatically. When changes occur that change the behavior in their dependents, the dependent software is then broken. For any software, it is important that the versions of dependencies for a given release of the software are the same for all new installations and usages of the software - and it is especially important for scientific software and papers in order to allow for peer review and equivalent results in further research.

An example where this could be problematic is in the specification of `numpy` as a dependency. In version [v1.7.0](https://github.com/pyccel/pyccel/blob/v1.7.0/setup.cfg#L16), for example, no version is specified. This means the latest version of `numpy` will always be used, which might cause the release v1.7.0 to fail to work correctly - in the best case causing errors, and worst case appearing to work correctly, but producing erroneous results.

The fix is to specify either exact versions of dependencies, or ranges of dependencies known to work (and that have been tested). While [the documentation](https://setuptools.pypa.io/en/latest/userguide/dependency_management.html) on ways to do this is a little obtuse, this can all be handled in setup.cfg. For example, `sympy` can be specified as

```ini
[options]
install_requires =
    sympy >= 1.2, <= 1.7.1
```

**Comment by aholmes** [comment]
> Our unit tests run on a daily basis using the latest available versions of our dependencies, hence if we catch a problem with any of them we immediately release a new (minor) version of Pyccel where we specify the maximum version of the problematic library.

This is great and definitely helps with any future versions and downloads of the software, however, users of previous versions will need to be made aware of any new issues and future updates, and we (package maintainers in general) aren't able to dictate how users of our software will manage the dependency on our own software - meaning they may end up using a version of pyccel that, when `pip install .` is run, pulls a version of a dependency that is no longer compatible with that version of pyccel. In cases where this causes the software to loudly fail (errors and such), users can quickly discover what is going wrong. In cases of silent failure (subtle changes in behavior, etc.), users may never discover that something isn't correct.

It's this case in particular that locking versions helps with - for users on past versions of the software who may or may not be monitoring updates.

> I understand the need for reproducibility in science, but I think that this could be better served by using `pip freeze > requirements.txt`

This is a reasonable compromise. Can I propose that the "Pyccel Installation Methods" section in README.md is updated to reflect this, if this method is pursued? It may make sense to categorize "user installation methods" using requirements.txt, and "developer installation methods" using `pip install -e .`. I also suggest adding a note about using a virtual environment to install and use the software to help avoid the case where a user unintentionally changes their system Python dependencies.

> Maybe we could be stricter in our dependencies when producing a Dockerfile

This is a great idea!

Another consideration would be setting specific version dependencies as part of the pyccel release process. setup.cfg can remain as is in the "main" branch, and versions can be specific in setup.cfg in a release branch. This way "main" isn't restricted, while the versions will be "self-contained," so to speak.

**Comment by yguclu** [comment]
Thanks for the clarifications! There is definitely much room for thought here... We'll get back to you ASAP

**Comment by yguclu** [comment]
After the discussion in our developers' meeting, we plan to:
- Specify the minimum version of all our dependencies
- Clarify in the README how a `virtualenv` and `requirements.txt` file can be used for reproducibility
- Provide an optional `pyccel-test` command at installation, for running all tests (`pyccel-test all`) or just the basic ones (`pyccel-test basic`)
- Automatically store a `requirements-[version].txt` file every time we upload new benchmark results to the `pyccel-benchmarks` repository

@aholmes Does this sound as a good compromise to you?

**Comment by aholmes** [comment]
@yguclu Yes, I think this sounds reasonable.

One question - why `requirements-[version].txt` over just `requirements.txt`? This seems burdensome for you to maintain, and you would eventually have many of these files, if I understand correctly.

**Comment by yguclu** [comment]
For each release of Pyccel, we already generate the following files, which are added to the directory `version_specific_results/`:
- `pypi_performance_[python-version]_[pyccel-version].md`
- `pypi_performance_[python-version]_[pyccel-version]_compilation.png`
- `pypi_performance_[python-version]_[pyccel-version]_execution.png`

The idea is to also generate the corresponding requirements file by using
```bash
python3 -m pip freeze > pypi_performance_[python-version]_[pyccel-version]_requirements.txt
```

This way we will keep track of all the dependencies used to run the benchmarks.

**Comment by yguclu** [comment]
On a separate note, I am now realizing that adding all those PNG images to the git repository will cause it to grow in size very quickly, so it is not really sustainable in the long run. @EmilyBourne I think we need a better solution...

**Comment by aholmes** [comment]
> For each release of Pyccel, we already generate the following files

Okay, great!

> I am now realizing that adding all those PNG images

If I may suggest - SVG is a good alternative. The size is much smaller, and the changes can be diffed. GitHub has a really nice "SVG diff viewer" to visually see what's different.

**Comment by EmilyBourne** [comment]
> Provide an optional pyccel-test command at installation, for running all tests (pyccel-test all) or just the basic ones (pyccel-test basic)

I'm not sure how this should work given that we don't install the tests. Would it not make more sense to describe a command in the README?
