### ISSUE TITLE
[CUDA] Cuda tests do not run

### ISSUE THREAD

**Issue by EmilyBourne** [pyccel/pyccel#1293]
### Describe the bug
Cuda tests have only been running when merging to `cuda_main` (see [here](https://github.com/pyccel/pyccel/blob/cuda_main_temp/.github/workflows/Cuda_pytest.yml#L5)), however cuda branches merge to `cuda_main_temp`. As a result the tests haven't been run for 2 months and breaking changes have been merged to `cuda_main_temp`. The tests now fail.
Tests have been reactivated, they now need to be fixed.

### Error details
See https://github.com/pyccel/pyccel/actions/runs/3856177210/jobs/6572072053

### Language
Cuda

**Comment by EmilyBourne** [comment]
@bauom can this issue be closed? Or should we wait until the cuda pipeline has been restored?

**Comment by bauom** [comment]
> @bauom can this issue be closed? Or should we wait until the cuda pipeline has been restored?

as far as i know this problem is now is fixed No?
we did activate the tests in all the Cuda branches.
and @framdani is adding run time tests in #1328
so this problem should be fixed for good.
we might need to add a local check in the future until we have some way to run the `cuda` tests remotely.

**Comment by EmilyBourne** [comment]
@bauom Ok then I am closing the issue. I don't think all the tests are active because it is still not set up to merge to `cuda_devel` yet. But that is probably a separate issue. Once that pipeline is set up it should force the downstream branches to update I think.
