### ISSUE TITLE
[JOSS] Missing details for benchmark results

### ISSUE THREAD

**Issue by boegel** [pyccel/pyccel#1295]
(cfr. https://github.com/openjournals/joss-reviews/issues/4991)

The submission to JOSS (cfr. [joss-paper](https://github.com/pyccel/pyccel/tree/joss-paper/joss-paper), submitted by @yguclu ) includes some nice benchmark results, collected via [pyccel-benchmarks](https://github.com/pyccel/pyccel-benchmarks).

There are some important details missing about the experimental setup though, in particular:

* operating system + version
* hardware details (mainly which exact CPU)
* how many cores are in the system, and how many were used for running the benchmarks

Can this information be added to the paper?
It would be very helpful to interpret the results.

In addition, the use of `-ffast-math` when benchmarking Pythran and Pyccel is a bit concerning, see for example https://simonbyrne.github.io/notes/fastmath/ .
Is `-ffast-math` critical to get good results? If not, would it make sense to re-run the benchmarks without it, and include those results in the JOSS paper instead?

**Comment by EmilyBourne** [comment]
Hello, just to give an update. The benchmarks have been tested without `-ffast-math` and the results have been reproduced (see https://github.com/pyccel/pyccel-benchmarks/pull/17).

Regarding the experimental setup. We used the GitHub runners to generate our results, however GitHub doesn't provide details of which CPUs are used. We are therefore trying to work out what machines we have access to which have a recent version of python installed. Once we have found a machine where we can run the tests we will update the paper.

**Comment by boegel** [comment]
Good to hear that not using `-ffast-math` doesn't skew the results too much.

Were all benchmarks run in a single workflow run using GitHub Actions?
If not, different runs maybe end up on different types of CPUs, so that doesn't seem a reliable way of running benchmarks to me...

**Comment by boegel** [comment]
Adding a `cat /proc/cpuinfo` and `cat /etc/os-release` + `uname -a` would already give a bunch of info, but still, I don't think GitHub Actions is suitable place to run benchmarks, it's no doubt subject to *a lot* of noise which could skew the results quite a bit.

**Comment by EmilyBourne** [comment]
I've found a machine to run on. I should be able to update the paper this evening

**Comment by yguclu** [comment]
@boegel Can we close this issue after PR [#20](https://github.com/pyccel/pyccel-benchmarks/pull/20)? As requested, the test results reported in the [pyccel/joss-paper](https://github.com/pyccel/pyccel/tree/joss-paper/joss-paper) branch do not use the `-ffast-math` flag.

**Comment by boegel** [comment]
> @boegel Can we close this issue after PR [#20](https://github.com/pyccel/pyccel-benchmarks/pull/20)? As requested, the test results reported in the [pyccel/joss-paper](https://github.com/pyccel/pyccel/tree/joss-paper/joss-paper) branch do not use the `-ffast-math` flag.

Yes, thank you very much for the additional effort!
