### ISSUE TITLE
Cannot declare two np.linspace arrays when using Fortran

### ISSUE THREAD

**Issue by jalalium** [pyccel/pyccel#1318]
### Describe the bug
Fortran code generator tries to declare `integer(i64) :: linspace_index` variable each time an `np.linspace` array is created without checking if the variable has already been added to the scope. This throws an error in the `Scope.insert_variable` method

### To Reproduce
Provide code to reproduce the behavior:
```python
import numpy as np
    
if __name__ == '__main__':
    x = np.linspace(0, 2, 128)
    y = np.linspace(0, 2, 128)
    print(x)
    print(y)
   
```

### Error details
Provide the generated code, or the error message:
```Fortan
 line 278, in insert_variable
    raise RuntimeError('New variable {} already exists in scope'.format(name))
RuntimeError: New variable linspace_index already exists in scope
```

### Expected behavior
The two variables should have declared without a problem.
### Language
Fortran

### Additional context
This bug is urgent since it is used in `laplace_2d_mod` test file in the benchmarks

**Comment by yguclu** [comment]
It is really surprising that we haven't encountered this error before!
