### ISSUE TITLE
Disable conda paths warning?

### ISSUE THREAD

**Issue by spossann** [pyccel/pyccel#1356]
https://github.com/pyccel/pyccel/blob/ef95df80f0d5b910834d16d8e10ee251e0e6708e/pyccel/codegen/compiling/compilers.py#L41

Would it be possible to disable this warning by default? It is a little off-putting for first time users, who might think that something goes wrong during compilation.

**Comment by EmilyBourne** [comment]
It should be relatively easy to add a flag to disable this warning, however I don't think it should be disabled by default as ignoring these folders runs the risk of missing installed files. As a result I think it is important for the user to realise this is happening.
These folders are ignored as in most systems conda is used via anaconda to provide libraries etc intended for Python so it is easy to accidentally link an unexpected version of a library (e.g. LAPACK). However if conda was used as the package manager (as designed) for the entire system this workflow may cause problems.

Perhaps we could make this message friendlier and point to documentation and a disable flag?

**Comment by spossann** [comment]
Allright, thanks Emily. I guess it is a good idea to point the user to the doc and mention how to disable the warning.

**Comment by EmilyBourne** [comment]
Ok. In that case to fix this issue we need to:
- [ ] Add a flag to disable conda warnings
- [ ] Add a user documentation page about the pitfalls related to conda
- [ ] Modify the warning from "Ignoring conda paths when searching for compiler : ..." to "Conda paths are ignored. See DCOUMENTATION for details" where DOCUMENTATION is replaced with a link to the doc page
- [ ] Add a flag to give detailed conda warnings (where the ignored folders are listed)
