### ISSUE TITLE
Linking error with anaconda 

### ISSUE THREAD

**Issue by EmilyBourne** [pyccel/pyccel#1366]
### Description

During the final linking stage it is sometimes necessary to link to `libgfortran.so`. Anaconda has its own version of this file which is superceding the installed version.

### Environment information

Python version : 3.9

OS version : Linux

Versions for any relevant dependencies: anaconda 23.1

Cc: @mkaddani

**Comment by mkaddani** [comment]
Ubuntu 22.04.2 LTS x86_64
gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
conda 23.1.0
