### ISSUE TITLE
Coverage is no longer optional

### ISSUE THREAD

**Issue by EmilyBourne** [pyccel/pyccel#1368]
Until a few weeks ago having full coverage of a PR was encouraged but not enforced. This is no longer the case, however there are occasionally sections of code which cannot be tested on the runner (e.g. compiler settings for unusual setups) so this should not be mandatory.

cc: @yguclu

**Comment by yguclu** [comment]
Could we not exclude some "special" files from the coverage mandate?

**Comment by EmilyBourne** [comment]
@yguclu This is possible for things such as this file : https://github.com/pyccel/pyccel/blob/master/pyccel/compilers/default_compilers.py

But there is also a second case to consider. Sometimes (e.g. when fixing issues such as https://github.com/pyccel/pyccel/issues/1329 ) we touch lots of code, including code which we know less about. This code may not be tested. When this is the case it takes quite a lot of effort to determine whether the code could be tested (and to find a pertinent test) or if it is dead code which should be removed. In an ideal world this effort should be made, but in reality this would delay merging PRs too long so it is better to create dedicated issues.

If we had a significantly more complicated coverage tool we could also fix this by only asking for coverage on new code not modified code, but in many cases the coverage can be increased when the code is modified if we are made aware that it is not yet tested, so this also feels like a missed opportunity

**Comment by yguclu** [comment]
I understand the problem now, and I agree with you.
