### ISSUE TITLE
make html in doc fails due to file() used in doc/conf.py

### ISSUE THREAD

**Issue by krystophny** [pyccel/pyccel#139]
In file `doc/conf.py`, line 192, the file() statement is used
`f = file('latex_macros.sty')`

This doesn't work anymore with Python 3 and causes sphinx doc generation to fail in `make html` for Python 3 based systems.

To fix it, one could be replace the line by
`f = open('latex_macros.sty')`

**Comment by saidctb** [comment]
thanks for the remark it will be corrected in the next merge of  the pull request
