### ISSUE TITLE
Add dtype property to arrays

### ISSUE THREAD

**Issue by tomcaruso** [pyccel/pyccel#1421]
### Description
I try to create a numpy array with `np.zeros` with the `dtype` given by another array. When I try to pyccelise this file pyccel return the issue `Attribute dtype not found`.

### To Reproduce
```python
import numpy as np
from pyccel.decorators import template
@template(name='T', types=['float[:]', 'complex[:]'])
def eval_jacobians_3d(n1: int, array: 'T'):
    arr_coeffs_x = np.zeros((n1), dtype=array.dtype)
```

### Error details
```bash
ERROR at annotation (semantic) stage
pyccel:
 |fatal [semantic]: kernels.py [60,91]| Attribute dtype not found
```

### Expected behavior
It should pyccelise it without crashing, I guess.

### Language
Fortran

**Comment by EmilyBourne** [comment]
You are right, pyccel doesn't yet implement the `dtype` function or attribute.
We should create a class containing only a `__new__` function which returns the dtype of an array using the dictionary `DtypePrecisionToCastFunction`. This new class should then be added as an attribute in the numpy array class description here:  https://github.com/pyccel/pyccel/blob/3dec5c01e139aa0afda8586ba1fd4fbf4a92a304/pyccel/ast/class_defs.py#L136

While you are waiting for someone to pick up this issue, as a temporary workaround you can use:
```
import numpy as np
from pyccel.decorators import template
@template(name='T', types=['float[:]', 'complex[:]'])
def eval_jacobians_3d(n1: int, array: 'T'):
    arr_coeffs_x = np.zeros((n1), dtype=type(array[0]))
```
