### ISSUE TITLE
Pyccelisation of a cmath function

### ISSUE THREAD

**Issue by tomcaruso** [pyccel/pyccel#1422]
### Describe the bug
Pyccel does not support the `cmath` library.

### To Reproduce
Try to pyccelise the following file :
```python
from cmath import cosh
def function(a:'complex'):
    a1 = cosh(a)
    return(a1)
```

### Error details
Provide the generated code, or the error message:
```bash
error [semantic]: cmath_test_function.py [1]| Module cmath is not currently supported by pyccel 
```

### Expected behavior
I suppose that `cmath` library being similar to the `math` one, Pyccel should be able to call it no ?

### Language
Fortran

**Comment by EmilyBourne** [comment]
You are correct this should be fairly easy to add by following the example shown by the `math` library. The `cmath` functions are available in the `complex.h` header file in C (https://en.wikibooks.org/wiki/C_Programming/complex.h) and should be built-in in Fortran
