### ISSUE TITLE
adding quoted string at beginning of .py file produces failing .f90

### ISSUE THREAD

**Issue by krystophny** [pyccel/pyccel#146]
When adding as a header something like
```
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Jul 24 15:25:43 2018

@author: calbert
"""
```
pyccel correctly identifies the first part into a Fortran comment, but doesn't convert the quoted one, which leads to a compile error. Since spyder automatically generates file headers of this form, it would be nice to be able to parse them.

**Comment by saidctb** [comment]
it is been added you can see the example CommentBlock.py in the folder tests/codegen/scripts/

**Comment by krystophny** [comment]
Works great, thanks!

**Comment by krystophny** [comment]
One more detail: When I write a script that should contain only functions, but not a program, pyccel now generates a program in Fortran instead of a module if quoted strings appear in the .py file.

**Comment by saidctb** [comment]
ah you are right, I should probably modify this
