### ISSUE TITLE
Duplicated declaration of dotted variables.

### ISSUE THREAD

**Issue by sboof911** [pyccel/pyccel#1468]
### Describe the bug
The `DottedVariable` should verify if the variable exists already.
The verification should be in: https://github.com/pyccel/pyccel/blob/c75e816b0c89e4ad9088dab1faf43b1f03641183/pyccel/parser/semantic.py#L1238-L1268

### To Reproduce
Provide code to reproduce the behavior:
```python
class Point:
    def __init__(self, x, y):
        self.x = x
        self.y = y
        d = 10
        self.x = d
```

### Error details
Provide the generated code, or the error message:
```bash/fortran/c
The return of ClassDef.attributes : [x, y, x]
```

### Expected behavior
```bash/fortran/c
The return of ClassDef.attributes : [x, y]
```

**Comment by EmilyBourne** [comment]
I suspect this problem is the cause of #1469 .
