### ISSUE TITLE
Add support for type hinting to classes

### ISSUE THREAD

**Issue by EmilyBourne** [pyccel/pyccel#1492]
### Describe the bug
When classes were implemented the only way to specify types in Pyccel was via headers. Before writing the class headers must be used to declare that the class will exist and to declare its methods. E.g:

```python
#$ header class Point(public)
#$ header method __init__(Point, float)
#$ header method __del__(Point)
#$ header method translate(Point, float)
```

since then Pyccel has added support for type hinting (and the `@types` decorator). However the class support was too minimal for it to be given the same attention. As a result headers are still the only way of specifying types in classes. This should be fixed before adding documentation.

The `@types` decorator will be deprecated in the future so this can be ignored.

### Test Code
I would like to be able to write the following code:
```python
class Point:
    def __init__(self : 'Point', x : float):
        self.x = x

    def __del__(self : 'Point'):
        pass

    def translate(self : 'Point', a : float):
        self.x[:]   =  self.x + a
```
or (given that the type of the first variable cannot be modified):
```python
class Point:
    def __init__(self, x : float):
        self.x = x

    def __del__(self):
        pass

    def translate(self, a : float):
        self.x[:]   =  self.x + a
```

The start of the class should be sufficient to replace `#$ header class Point(public)`. Currently types hints are handled by converting the hints to functions as described in #1487 . Changing this will be handled in a different issue. For this issue it is sufficient to build and insert the expected header into the `FunctionDef`

### Language
All languages, this problem is in the syntactic/semantic level

### Additional context
See #1487

**Comment by adam-urbanczyk** [comment]
Hey, very useful project! It would be great if you could consider [PEP526](https://peps.python.org/pep-0526/#class-and-instance-variable-annotations) syntax for this. E.g.
```python
class Point:
    x: int
    y: int
```
