### ISSUE TITLE
Add wrapping of a FunctionDefResult containing a class

### ISSUE THREAD

**Issue by EmilyBourne** [pyccel/pyccel#1494]
### Describe the feature
I want to be able to call functions which return class instances.

### Test Code
Provide code which does not currently work but which should do when this issue is fixed:

For the following module handled by Pyccel:
```python
class Point:
    def __init__(self, x : int):
         self._x = x

def get_point(x : int):
    return Point(x)
```
we should be able to do:
```python
from mod import get_point

p = get_point(3)
```

### Proposed Solution
The function `CToPythonWrapper._visit_FunctionDefResult` should be improved to handle classes. The resulting code will be:
```c
struct PyPointObject* get_point_wrapper(PyObject* self, PyObject* args, PyObject* kwargs)
{
    PyObject* x_obj;
    int64_t x;
    struct PyPointObject* Out_0001_obj;
    static char *kwlist[] = {
        "x",
        NULL
    };
    if (!PyArg_ParseTupleAndKeywords(args, kwargs, "O", kwlist, &x_obj))
    {
        return NULL;
    }
    Out_0001_obj = (struct PyPointObject*)PyPointType.tp_alloc(&PyPointType, 0);
    if (PyIs_NativeInt(x_obj))
    {
        x = PyInt64_to_Int64(x_obj);
    }
    else
    {
        PyErr_SetString(PyExc_TypeError, "Expected an argument of type int for argument x");
        return NULL;
    }
    Out_0001_obj->instance = malloc(sizeof(struct Point));
    (*(struct Point*)(Out_0001_obj->instance)) = get_point(x);
    return Out_0001_obj;
}
```

### Issues which must be tackled first
- #1493 : To have a class instance
- #1444 : Functions which return classes

**Comment by yguclu** [comment]
When you write "I want to be able to call functions which return classes" do you mean "I want to be able to call functions which return objects of user-defined classes"?

**Comment by yguclu** [comment]
I am a bit confused by these lines in your code snippet:
```c
Point Out_0001;

Out_0001 = get_point(x);
malloc(Out_0001_obj.instance, sizeof(Point));
Out_0001_obj.instance = Out_0001;
```
While `Out_0001` is of type `Point`, `Out_0001_obj.instance` is of type `Point*`. Therefore I think that you either wanted to write
```c
Out_0001_obj->instance = Out_0001;
```
which still duplicates memory for a single `Point` object, or
```c
Out_0001_obj.instance = get_point(x);
```
where the call to `malloc` is inside `get_point` which returns a pointer.

**Comment by EmilyBourne** [comment]
You are right. I wrote this issue without running/compiling the suggested code. This is why the issue said:
> The code should look **something like**:

I have updated the issue to describe the code that is now generated by #1604 when translating to C. The code snippet you mentioned has now changed to:

```c
malloc(Out_0001_obj.instance, sizeof(Point));
(*(struct Point*)(Out_0001_obj->instance)) = Out_0001;
```

Regarding your suggested code.
```c
Out_0001_obj->instance = Out_0001;
```
This does not work as `Out_0001_obj.instance` is a pointer not `Out_0001_obj`-


```c
Out_0001_obj.instance = get_point(x);
```
`get_point` returns an instance of `Point` not a pointer so it cannot be saved to `Out_0001_obj.instance`.

**Comment by EmilyBourne** [comment]
The code generated by #1604 when translating to Fortran is:
```c
struct PyPointObject* get_point_wrapper(PyObject* self, PyObject* args, PyObject* kwargs)
{
    PyObject* x_obj;
    int64_t x;
    void* bound_Out_0001;
    struct PyPointObject* bound_Out_0001_obj;
    static char *kwlist[] = {
        "x",
        NULL
    };
    if (!PyArg_ParseTupleAndKeywords(args, kwargs, "O", kwlist, &x_obj))
    {
        return NULL;
    }
    bound_Out_0001_obj = (struct PyPointObject*)PyPointType.tp_alloc(&PyPointType, 0);
    if (PyIs_NativeInt(x_obj))
    {
        x = PyInt64_to_Int64(x_obj);
    }
    else
    {
        PyErr_SetString(PyExc_TypeError, "Expected an argument of type int for argument x");
        return NULL;
    }
    bound_Out_0001 = bind_c_get_point(x);
    bound_Out_0001_obj->instance = bound_Out_0001;
    return bound_Out_0001_obj;
}
```

**Comment by yguclu** [comment]
Thanks for the clarification. When I wrote
```c
Out_0001_obj.instance = get_point(x);
```
I meant that we would make `get_point` allocate memory and return a pointer to the new object.

**Comment by EmilyBourne** [comment]
> Thanks for the clarification. When I wrote
> ```c
> Out_0001_obj.instance = get_point(x);
> ```
> I meant that we would make `get_point` allocate memory and return a pointer to the new object.

This is what the bind c module does, but we don't do this with code coming from C as it would mean that we would have to change the generated pure c code

**Comment by yguclu** [comment]
Indeed this raises a fundamental question. Do we want the generated C code to always return an automatic variable regardless of the size of the underlying object?

**Comment by yguclu** [comment]
> The code generated by #1604 when translating to Fortran is:
> 
> ```c
> struct PyPointObject* get_point_wrapper(PyObject* self, PyObject* args, PyObject* kwargs)
> {
>     PyObject* x_obj;
>     int64_t x;
>     void* bound_Out_0001;
>     struct PyPointObject* bound_Out_0001_obj;
>     static char *kwlist[] = {
>         "x",
>         NULL
>     };
>     if (!PyArg_ParseTupleAndKeywords(args, kwargs, "O", kwlist, &x_obj))
>     {
>         return NULL;
>     }
>     bound_Out_0001_obj = (struct PyPointObject*)PyPointType.tp_alloc(&PyPointType, 0);
>     if (PyIs_NativeInt(x_obj))
>     {
>         x = PyInt64_to_Int64(x_obj);
>     }
>     else
>     {
>         PyErr_SetString(PyExc_TypeError, "Expected an argument of type int for argument x");
>         return NULL;
>     }
>     bound_Out_0001 = bind_c_get_point(x);
>     bound_Out_0001_obj->instance = bound_Out_0001;
>     return bound_Out_0001_obj;
> }
> ```

Compared to the code under "proposed solution", here there is no `malloc`, which is deferred to the `bind_c_get_point` function, and no type casting. Is the type casting superfluous?

**Comment by EmilyBourne** [comment]
> Indeed this raises a fundamental question. Do we want the generated C code to always return an automatic variable regardless of the size of the underlying object?

I am not sure what you mean by "automatic variable".

If pointers are not necessary then I think we are better avoiding them as they require calls to `free`.

The only way to make a class really large is to stock arrays, however arrays themselves are created via mallocs so I don't know if making the container a pointer too would make a difference?

**Comment by yguclu** [comment]
> I am not sure what you mean by "automatic variable".

I mean a variable local to the scope, for which memory is allocated and freed automatically (usually on the stack): https://en.wikipedia.org/wiki/Automatic_variable

**Comment by yguclu** [comment]
> If pointers are not necessary then I think we are better avoiding them as they require calls to `free`.

If the function returns more than one object, are we not back to this situation anyway? The C function will have to get as an input pointers to the preallocated objects.

**Comment by yguclu** [comment]
> The only way to make a class really large is to stock arrays, however arrays themselves are created via mallocs so I don't know if making the container a pointer too would make a difference?

This is a good point! Unless we allow for stack arrays inside class instances.

**Comment by EmilyBourne** [comment]
> Compared to the code under "proposed solution", here there is no malloc, which is deferred to the bind_c_get_point function, and no type casting. Is the type casting superfluous?

Similarly to arrays, the only way to return a class instance from Fortran to C is by returning a pointer. The bind c code is:
```fortran
  function bind_c_get_point(x) bind(c) result(bound_Out_0001)

    implicit none

    type(c_ptr) :: bound_Out_0001
    integer(i64), value :: x
    type(Point) :: Out_0001
    type(Point), pointer :: Out_0001_ptr

    Out_0001 = get_point(x = x)
    allocate(Out_0001_ptr)
    Out_0001_ptr = Out_0001
    bound_Out_0001 = c_loc(Out_0001_ptr)

  end function bind_c_get_point
  !........................................
```

This is why there is no `malloc` in the Python-C wrapper as the memory is already allocated on the heap.


Type casting of pointers does not change how the program behaves. A `void*` takes up the same amount of memory as a `(struct Point*)` as both are just memory addresses. However if we want to interact with the stored object we should use type casts to avoid compiler warnings. When collecting results from C the resulting class is copied into `Out_0001_obj->instance)`. In order to copy without a warning we need to know that the object being referenced is indeed a `struct Point`. For Fortran it is simpler, we are just storing an address in a pointer. The prototype of `bind_c_get_point` is:
```
void* bind_c_get_point(int64_t);
```
and a `void*` is already compatible with `void* instance`

**Comment by EmilyBourne** [comment]
> If the function returns more than one object, are we not back to this situation anyway?

If I translate this code:
```python
class Point:
    def __init__(self, x : int):
         self._x = x

def get_point(x : int):
    return Point(x), Point(x+1)
```
to C, the generated wrapper looks like this:
```c
PyObject* get_point_wrapper(PyObject* self, PyObject* args, PyObject* kwargs)
{
    PyObject* x_obj;
    struct PyPointObject* Out_0001_obj;
    struct PyPointObject* Out_0002_obj;
    int64_t x;
    PyObject* result;
    static char *kwlist[] = {
        "x",
        NULL
    };
    if (!PyArg_ParseTupleAndKeywords(args, kwargs, "O", kwlist, &x_obj))
    {
        return NULL;
    }
    Out_0001_obj = (struct PyPointObject*)PyPointType.tp_alloc(&PyPointType, 0);
    Out_0002_obj = (struct PyPointObject*)PyPointType.tp_alloc(&PyPointType, 0);
    if (PyIs_NativeInt(x_obj))
    {
        x = PyInt64_to_Int64(x_obj);
    }
    else
    {
        PyErr_SetString(PyExc_TypeError, "Expected an argument of type int for argument x");
        return NULL;
    }
    Out_0001_obj->instance = malloc(sizeof(struct Point));
    Out_0002_obj->instance = malloc(sizeof(struct Point));
    get_point(x, &(*(struct Point*)(Out_0001_obj->instance)), &(*(struct Point*)(Out_0002_obj->instance)));
    result = Py_BuildValue("OO", Out_0001_obj, Out_0002_obj);
    Py_DECREF(Out_0001_obj);
    Py_DECREF(Out_0002_obj);
    return result;
}
```

So the copy is avoided but we still see type casting.

**Comment by EmilyBourne** [comment]
This discussion is also possibly related to #1339
