### ISSUE TITLE
Split comments are not fully commentated

### ISSUE THREAD

**Issue by EmilyBourne** [pyccel/pyccel#150]
If a comment is too long then pyccel splits it into multiple lines, however only the first line is commented

**Comment by EmilyBourne** [comment]
This is also true for the first and last line of block comments when 
_________________________CommentBlock_________________________
Is stretched to be as wide as the comments and is then too large for the line

**Comment by EmilyBourne** [comment]
Fixed for single line comments

**Comment by saidctb** [comment]
it's now fixed
