### ISSUE TITLE
Pyccel translates list concatenation (Python) into array sum (Fortran)

### ISSUE THREAD

**Issue by yguclu** [pyccel/pyccel#152]
For example see [classes_1.py](../blob/master/tests/codegen/scripts/classes_1.py): Python and Fortran outputs differ.

**Comment by saidctb** [comment]
thanks for the remark the bug has been fixed,  but I'm not sure if we should support concatenation  like python

**Comment by yguclu** [comment]
I do not think it is important to support list concatenation at the moment, instead Pyccel should raise an error if the Python code contains such an operation. Is this what happens now?

**Comment by saidctb** [comment]
no it does do the concatination but you have to creat a new variable each time so for example you can't do a concatination in a for loop for the same variable
