### ISSUE TITLE
Misleading type names

### ISSUE THREAD

**Issue by EmilyBourne** [pyccel/pyccel#1520]
The current names of the basic underlying types are misleading. These should be changed to make the code easier to understand. The changes should be made as follows:

- `pyccel.ast.basic.Basic` -> `pyccel.ast.basic.PyccelAstNode`
- `pyccel.ast.basic.PyccelAstNode` -> `pyccel.ast.basic.TypedAstNode`
- `pyccel.ast.basic.ScopedNode` -> `pyccel.ast.basic.ScopedAstNode`

**Comment by imperial-chief** [comment]
Hello Ma'am,
I am willing to work on this but i am completely new to open source,
So can you please let me know exactly how is this to be done.

**Comment by EmilyBourne** [comment]
Hello!
Thank you very much for your interest in Pyccel.
As a new contributor to open source the first thing to do is to fork the repository and make sure that you have your development environment set up properly (see [Getting Started](https://github.com/pyccel/pyccel/blob/devel/developer_docs/getting_started.md) and the [installation docs](https://github.com/pyccel/pyccel/blob/devel/docs/installation.md#from-sources)). If you have any trouble feel free to contact me on our [discord server](https://discord.gg/2Q6hwjfFVb).

Once everything is working you can create a new branch to tackle this issue.
The issue is quite simple as it just involves renaming 3 classes but these classes are used in lots of places in the code. I would recommend using `grep` to find them all and possibly a tool such as `sed` for replacing them. Please make sure you also update any mentions in the documentation folders.

One thing to watch out for, some of our functions are called using type names so they will also need renaming. You can read more about this in the [overview](https://github.com/pyccel/pyccel/blob/devel/developer_docs/overview.md#function-naming-conventionsfile-navigation).

Once you are happy with your changes and the tests seem to be passing, you can go ahead and open a pull request. The review process is described [here](https://github.com/pyccel/pyccel/blob/devel/developer_docs/review_process.md). One thing that might be problematic during the review is the documentation tests. We moved relatively recently to enforce having neat NumPy style docstrings on all our classes and functions. However lots of our old code is still not fully documented. As this issue touches lots of different parts of the code it is likely that it will trigger this test. If there are not many errors then I will probably give you a hand with code suggestions on the review that you can apply with a few clicks. If there are lots, then I may ask @yguclu to make an exception for this PR and temporarily make that test optional.

Hopefully that gives you all the information you need. Are you still willing to work on this? Don't hesitate to contact me or the other devs either here or on the discord if you have any other questions.
