### ISSUE TITLE
Functions returning arrays are translated to subroutines without warning

### ISSUE THREAD

**Issue by EmilyBourne** [pyccel/pyccel#154]
Functions which return an array are translated to subroutines, which affects their ability to be called correctly. E.g:

```
from numpy      import empty

#$ header function getGrid(float,float,int) results(float[:])
def getGrid(a,b,n):
    result = empty(n)
    for i in range(n):
        result[i] = a+i*(b-a)/(n-1)
    return result


f=getGrid(0,1,10)
```

Pyccel does not raise an error or a warning but converts the function to a subroutine which means that it is not used in the same way. This results in other areas of the code raising unreadable errors.

This may be related to fortran 77 (can't return an array) v fortran 90 (can return an array), but there is no difference between epyccel and pyccel

**Comment by saidctb** [comment]
yes indeed we need to fix this problem but for the moment try to use only procedures and keep functions only in the case of scalers

**Comment by yguclu** [comment]
@EmilyBourne Can you please check the status of this old issue?
