### ISSUE TITLE
Pyccel converts python "float" (=> double precision) to fortran float (single precision)

### ISSUE THREAD

**Issue by EmilyBourne** [pyccel/pyccel#155]
Pyccel converts python "float" (=> double precision) to fortran float (single precision).

The generated code therefore contains `real(kind=4)` and throws errors when it is passed an array generated by numpy with the correct precision (`real(kind=8)`).

See the following file for an example:

```
from numpy      import zeros

#$ header function getElem(float[:],int) results(float)
def getElem(f,i):
    return f[i]

f=zeros(4)
getElem(f,1)
```

**Comment by saidctb** [comment]
it is  fixed float will be converted to real(kind=8) instead of real(kind=4)
