### ISSUE TITLE
Remove GCC Intrinsics

### ISSUE THREAD

**Issue by EmilyBourne** [pyccel/pyccel#1553]
### Describe the bug
The code in this file: https://github.com/pyccel/pyccel/blob/devel/pyccel/stdlib/numpy/numpy_f90.f90
uses GCC intrinsics. As a result it does not compile with the intel compiler.

### To Reproduce
Provide code to reproduce the behaviour:
```python
def literal_complex_pos():
    import numpy as np
    b = np.sign(1+2j)
    return b
```

### Error details
Provide the generated code, or the error message:
```bash/fortran/c
E           RuntimeError: Failed to build module
E           /home/runner/work/pyccel/pyccel/__epyccel__gw0/__pyccel__gw0/numpy/numpy_f90.f90(126): error #7137: Any procedure referenced in a PURE procedure, including one referenced via a defined operation or assignment, must have an explicit interface and be declared PURE.   [REALPART]
E                 x_ne_zero = (REALPART(x) .ne. 0_f32) .or. (IMAGPART(x) .ne. 0_f32)
E           -------------------^
```
See : https://github.com/pyccel/pyccel/actions/runs/6511414122/job/17687068773

### Expected behaviour
The code should compile.

### Language
Fortran

### Additional context
There is a `SIGN` intrinsic in Fortran but it only handles integers and floating point numbers. It may make more sense to use this rather than our own functions where possible

### Implementation
For complexes a small benchmark test should be run to determine what is faster between:
1. `np.sign(c.real) + (1-np.abs(np.sign(c.real)))*np.sign(c.imag)`
2. `np.sign(x.real) if x.real != 0 else np.sign(x.imag)`

**Option 1**
Correct the code in the file to remove the GCC intrinsics

**Option 2**
Change `pyccel.codegen.fcode._print_NumpySign` to call the fortran [intrinsic](https://fortranwiki.org/fortran/show/sign) directly for integers and floats and correct the code in the file for complexes.

**Comment by EmilyBourne** [comment]
@yguclu Do you have a preference between options 1 and 2? Personally I have a slight preference for option 2

**Comment by yguclu** [comment]
I also prefer option (2). In the complex case I was thinking of providing our own inline function `sign_cmplx`, but this is probably overkill.
