### ISSUE TITLE
Dtype ignored

### ISSUE THREAD

**Issue by EmilyBourne** [pyccel/pyccel#158]
In the numpy function array, the dtype argument is ignored in favour of pyccel's interpretation.

E.g:

```
from numpy      import array

#$ header function printArray(float[:],int)
def printArray(f,n):
    for i in range(n):
        print(f[i])

f=array([3, 1, 0, 2],dtype=float)
printArray(f,4)
```

Where f is interpreted as `integer(kind=4)` and therefore the function throws an error.

**Comment by saidctb** [comment]
thanks for the remark the bug is fixed
