### ISSUE TITLE
_print_NumpyArray is not yet implemented for language : C

### ISSUE THREAD

**Issue by sonnendr** [pyccel/pyccel#1613]
Related to https://github.com/pyccel/psydac/issues/341#issuecomment-1807058895

The problem of the mpif90 wrapper on Mac can be overcome by using C as the default language in pyccel at least for MPI.
Using C as the default language for Struphy (https://gitlab.mpcdf.mpg.de/struphy/struphy) doesn't work because NumpyArray doesn't seem to work with C as shown in the example below.

pyccel /Users/sonnen/Codes/struphy/struphyEnv/lib/python3.11/site-packages/struphy/linear_algebra/core.py --libdir /opt/homebrew/opt/python@3.11/Frameworks/Python.framework/Versions/3.11/lib --language=c 

ERROR at code generation stage
pyccel:
 |fatal [codegen]: core.py [289,51]| _print_NumpyArray is not yet implemented for language : C
Pyccel has encountered syntax that has not been implemented yet. Please create an issue at https://github.com/pyccel/pyccel/issues and provide a small example of your problem. Do not forget to specify your target language ((a[0,1 : ], a[1,1 : ], a[3,1 : ]))

make: *** [/Users/sonnen/Codes/struphy/struphyEnv/lib/python3.11/site-packages/struphy/linear_algebra/core.cpython-311-darwin.so] Error 1
Traceback (most recent call last):
  File "/Users/sonnen/Codes/struphy/struphyEnv/bin/struphy", line 8, in <module>
    sys.exit(struphy())
             ^^^^^^^^^
  File "/Users/sonnen/Codes/struphy/struphyEnv/lib/python3.11/site-packages/struphy/console/main.py", line 595, in struphy
    func(**kwargs)
  File "/Users/sonnen/Codes/struphy/struphyEnv/lib/python3.11/site-packages/struphy/console/compile.py", line 96, in struphy_compile
    subprocess.run(['make',
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['make', '-f', 'compile_struphy.mk', 'flags=--language=c', 'flags_openmp_pic=--openmp', 'flags_openmp_mhd=']' returned non-zero exit status 2.

**Comment by EmilyBourne** [comment]
I think this should work if you create the temporary variable explicitly:
```python
    sub_array = a[(0,1,3),1:]
    plus =  a[0,0]*det(a[1:,1:])      + a[2,0]*det(sub_array)
```

We must be missing a step to create this temporary variable automatically. This should be easy to fix

**Comment by sonnendr** [comment]
This works, but then there are (maybe unrelated) issues with core. The first is
RuntimeError: Failed to build module
/Users/sonnen/Codes/struphy/struphyEnv/lib/python3.11/site-packages/struphy/linear_algebra/__pyccel__/core.c:392:29: error: initializing 'double' with an expression of incompatible type 't_ndarray' (aka 'struct s_ndarray')

**Comment by EmilyBourne** [comment]
Which version of Pyccel are you using? I cannot reproduce the reported errors with the current version.
I can see them version 1.9.0.

In the current version things work better, but there is a problem copying slices into arrays which causes an infinite loop.

**Comment by EmilyBourne** [comment]
By the way, while looking at this file I noticed that you have implementations of `transpose` and `matmul`. When translating to Fortran, Pyccel has implementations for these NumPy functions (transpose is also implemented for C). In Fortran we use the intrinsic functions for this. I am curious, did you add these functions because you found them to be faster than the intrinsics or because you didn't realise they are already available in Pyccel (or maybe they weren't when the file was written)?

**Comment by sonnendr** [comment]
I was using pyccel 1.7.4. Struphy is now updating to the latest version of pyccel, which should solve the problems with C.
