### ISSUE TITLE
Can't copy array and change type in C

### ISSUE THREAD

**Issue by EmilyBourne** [pyccel/pyccel#1641]
### Describe the bug
It is possible to create an array from another. This functions as a copy operator. This works well for objects of the same type but it fails in a C translation when the type is different

### To Reproduce
Provide code to reproduce the behavior:
```python
import numpy as np

def create_float_copy(a : 'int[:,:]'):
    c = np.array(a, dtype=float)
    return c

if __name__ == '__main__':
    arr = np.ones((3,4), dtype=int)
    print(arr)
    arr2 = create_float_copy(arr)
    print(arr2)
```

### Error details
The output of the C translation is:
```
[[1 1 1 1]
[1 1 1 1]
[1 1 1 1]]
[[0.000000000000 0.000000000000 0.000000000000 0.000000000000]
[0.000000000000 0.000000000000 0.000000000000 0.000000000000]
[0.000000000000 0.000000000000 0.000000000000 0.000000000000]]
```

### Expected behavior
The output of the Python code is:
```
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
```

### Language
C

### Additional context
This occurs due to the implementation of `array_copy_data` here:
https://github.com/pyccel/pyccel/blob/6e6f088edc909ae339d52a5b46b0c2f0553be0d9/pyccel/stdlib/ndarrays/ndarrays.c#L491-L510
It uses `memcpy` which is very efficient for objects of the same datatype but leads to the wrong result in this case

**Comment by VaradRengaraj** [comment]
Hi @EmilyBourne, if you are ok, can I work on this bug? I have the idea what is wrong here and I can provide an implementation.

**Comment by EmilyBourne** [comment]
Hi, thanks for your help :). The issue is free. I have assigned it to you. Feel free to get in touch on discord if you need any help setting up your environment or help with the issue itself

**Comment by VaradRengaraj** [comment]
Thanks @EmilyBourne.

**Comment by VaradRengaraj** [comment]
Hi @EmilyBourne, can you please let me know if these warnings from the static analyser suppressed? If not, i need to introduce some extra variables to avoid it.
