### ISSUE TITLE
clear: this method is used for removing all items from the list.

### ISSUE THREAD

**Issue by Farouk-Echaref** [pyccel/pyccel#1691]
### Feature Description
Add support for clear() method for lists in the Python translation.

### Test Code
This code should work when this issue is fixed:
```python
lis = [1, 2, 3]
lis.clear()
print(lis)
>> []
```

### Proposed Solution
See description in https://github.com/pyccel/pyccel/issues/1529

**Comment by mgurrie** [comment]
I am interested on being assigned to this task. Can I have more information on what I need to accomplish. @Farouk-Echaref
