### ISSUE TITLE
insert: inserts a given element at a given index in a list.

### ISSUE THREAD

**Issue by mustapha-belbiad** [pyccel/pyccel#1692]
### Feature Description

Add support for insert() method for lists in the Python translation.

### Test Code

This Code Should Work 

```python
digits = [3, 4, 6]

digits.insert(1, 2)

print(digits)
>> [3, 2, 4, 6]
```

### Proposed Solution
See description in #1529

**Comment by EmilyBourne** [comment]
Beware of this example, Pyccel does not have support for strings (there is very minimal support in Fortran, but only support for printing strings in C)

**Comment by mustapha-belbiad** [comment]
> Beware of this example, Pyccel does not have support for strings (there is very minimal support in Fortran, but only support for printing strings in C)

okay I will modify the example
