### ISSUE TITLE
Integer division '//' not working on arrays

### ISSUE THREAD

**Issue by yguclu** [pyccel/pyccel#171]
See **xfail** tests in [test_arrays.py](../blob/devel/tests/epyccel/test_arrays.py), which cannot epyccel-ize the following functions from module [arrays.py](../blob/devel/tests/epyccel/modules/arrays.py):
```
array_int_1d_scalar_idiv( x, a )
array_int_1d_idiv( x, y )

array_int_2d_C_scalar_idiv( x, a )
array_int_2d_C_idiv( x, y )

array_int_2d_F_scalar_idiv( x, a )
array_int_2d_F_idiv( x, y )
```
where `x` and `y` are integer arrays, and `a` is an integer scalar.

**Comment by saidctb** [comment]
the bug in travis is due to the use of the functions ```floor``` pyccel gives a precision 8  for the lhs instead of 4

**Comment by saidctb** [comment]
the bug in travis is due to the use of the function  ```floor``` pyccel gives a precision 8  for the lhs instead of 4

**Comment by yguclu** [comment]
@saidctb Then we should generate the Fortran code `floor(a,kind)` where `kind` is 4 or 8 depending on the circumstances. Could you do that?

**Comment by saidctb** [comment]
@yguclu    okay I'll fix it

**Comment by saidctb** [comment]
it's been fixed ,all the tests pass now
