### ISSUE TITLE
intersection : Returns a new set with elements that are common to all sets.

### ISSUE THREAD

**Issue by mustapha-belbiad** [pyccel/pyccel#1744]
### Feature Description

**Add support for intersection() method for sets in the Python translation.**
`intersection(*others)` : Returns a new set containing elements that are present in all sets, the intersection of all sets.

### Test Code

This Code Should Work 

```python
set1 = {1, 2, 3}
set2 = {2, 3, 4}
intersect_set = set1.intersection(set2)
print(intersect_set) 
>>> {2, 3}
```

### Proposed Solution
See description in #1531

**Comment by yguclu** [comment]
The following syntax should also be supported:
``` python
intersect_set = set1 & set2
```
Please note that in the non-operator case `set2` only needs to be an iterable. Here it must be a set, see the [documentation](https://docs.python.org/3/library/stdtypes.html#frozenset.intersection).

**Comment by EmilyBourne** [comment]
@learning-dev assigning you here?

**Comment by EmilyBourne** [comment]
> Sure @EmilyBourne. This is similar to setdefault right? I will have to add a class for intersection and then printing, tests of course. 

Yes that's right
