### ISSUE TITLE
Function shape(a) must return inverted tuple if input array a has C ordering.

### ISSUE THREAD

**Issue by yguclu** [pyccel/pyccel#175]

**Comment by yguclu** [comment]
Commit fce15839ec3932ea8837e8920484f03c08d2811d solves this problem in those cases where `shape(a)` is assigned to a left-hand-side. In a more general situation we need to work out a cleaner solution, possibly writing and using a Fortran helper function `reverse`, so that we can simply print `reverse(shape(a))`. I am going to close this issue for now.

**Comment by saidctb** [comment]
this issue has been solved i choose to use the function ```size``` instead of ```shape``` in order to determine the shape and we print  ```(/ size(a,1) , size(a,2)/)```  if the array has rank two for example

**Comment by yguclu** [comment]
@saidctb I like your solution because it uses symbolic manipulation, and there is no need to perform a `reverse` operation on the Fortran side.
