### ISSUE TITLE
Remove the `FunctionDef`, `Imports` and `Classes` from the `Module` body in the syntactic stage

### ISSUE THREAD

**Issue by said-hadjout** [pyccel/pyccel#1768]
Instances of `FunctionDef`, `Import`, and `ClassDef` are usually saved in specific attributes of the `Module`, `FunctionDef` and `ClassDef` classes. However at the end of the syntactic stage these objects are not saved into the separate attributes. Rather they are indiscriminately saved into a `CodeBlock`. The nodes are then retrieved and removed from the `CodeBlock` in the semantic stage. This is impractical in certain cases (see #1728), and can cause us to do visit functions twice in the semantics stage to collect these objects and analyse them. We should instead collect them directly in the syntactic stage.

**Comment by EmilyBourne** [comment]
If this is done after #1768 then it should be used to remove the `annotate` argument from `_visit_FunctionDef`
