### ISSUE TITLE
[DICT] Add Python support for clear

### ISSUE THREAD

**Issue by EmilyBourne** [pyccel/pyccel#1880]
### Describe the feature
Syntactic and semantic support should be added for `clear`. This should be tested by implementing Python printing

### Test Code
Provide code which does not currently work but which should do when this issue is fixed:
```python
def foo():
    a = {1,1.0, 2:2.0}
    a.clear()
    return a
```

**Comment by EmilyBourne** [comment]
Hi @leonardopaloschi 
Thanks for your interest.
The support for `dict.clear` should be implemented in a similar way to the support for `set.clear`. The steps to resolve this issue are:
- [ ] Add a class to represent the method in this file: https://github.com/pyccel/pyccel/blob/devel/pyccel/ast/builtin_methods/dict_methods.py (see https://github.com/pyccel/pyccel/blob/devel/pyccel/ast/builtin_methods/set_methods.py#L86 for an example)
- [ ] Ensure that the method is recognised as a method of the class `dict` by making the necessary changes in this file: https://github.com/pyccel/pyccel/blob/devel/pyccel/ast/class_defs.py
- [ ] Add tests in this file: https://github.com/pyccel/pyccel/blob/devel/tests/epyccel/test_epyccel_dicts.py (for now dicts are not supported as arguments or return types so you will have to use the `len()` function to check that the result is as expected)
- [ ] If necessary modify this file: https://github.com/pyccel/pyccel/blob/devel/pyccel/codegen/printing/pycode.py to ensure that the code is printed correctly in Python

If you are feeling motivated then C and Fortran printing could also be added in this PR. If you want to tackle this you will find information about the code generation stage here:
https://github.com/pyccel/pyccel/blob/devel/developer_docs/codegen_stage.md
Again you should be able to use `set.clear` as an example:
https://github.com/pyccel/pyccel/blob/devel/pyccel/codegen/printing/ccode.py#L2638-L2641
https://github.com/pyccel/pyccel/blob/devel/pyccel/codegen/printing/fcode.py#L1321-L1323

C support is implemented using the STC library. You can find docs for `hmap` (which we use to represent a `dict`) here:
https://github.com/stclib/STC/blob/master/docs/hmap_api.md

Fortran support is implemented using the gFTL library. You can find docs for `map` (which we use to represent a `dict`) here:
https://github.com/Goddard-Fortran-Ecosystem/gFTL/blob/main/include/v2/map/map.md#modifiers

**Comment by EmilyBourne** [comment]
Please let me know if you are still interested in resolving this now you have a better idea of what it entails so I can assign the issue to you.
Feel free to contact me on this issue or on the [Pyccel Discord Server](https://discord.gg/2Q6hwjfFVb) if you need any help or have more questions

**Comment by EmilyBourne** [comment]
By the way I should probably mention that strings support is not complete enough to be used in dicts yet so you should avoid using strings as keys in tests

**Comment by leonardopaloschi** [comment]
Hi, @EmilyBourne!
I think I've solved this issue, but I'm not sure about how can I test it.
Anyway I will open a pull request, so you can see if it's right or at least in the right way!
Thanks for all support! 
My pull request link is: https://github.com/pyccel/pyccel/pull/2029
The only problem is that I forgot to add my contribution to the AUTHORS file, but as soon as it's reviewed and accepted, I will add this contribution.

**Comment by EmilyBourne** [comment]
Hi @leonardopaloschi ,
> I think I've solved this issue, but I'm not sure about how can I test it.

There are a few ways to test:
1. You can run the test you have written locally using [pytest](https://docs.pytest.org/en/stable/)
2. You can ask the bot to run the tests on your PR.
3. You can create a file containing only the function to be translated and call `pyccel` on it using the command-line tool. See https://github.com/pyccel/pyccel/blob/devel/docs/quickstart.md#how-to-use-pyccel

> My pull request link is: https://github.com/pyccel/pyccel/pull/2029

I have had a first look and left a few comments. Overall it looks pretty good :+1: 

> The only problem is that I forgot to add my contribution to the AUTHORS file, but as soon as it's reviewed and accepted, I will add this contribution.

The review procedure is described here:
https://github.com/pyccel/pyccel/blob/devel/developer_docs/review_process.md

You usually won't get a review and your code definitely won't be accepted while there are still bits misisng. Don't worry about the number of commits though. We squash commits when merging. Your PR description will become the commit message. In any case the bot won't let you take the PR out of draft to begin requesting reviews until the checklist is complete.

Thanks for the speedy PR :)

**Comment by leonardopaloschi** [comment]
Hi @EmilyBourne,
I will work on the points you mentioned in the pull request soon. I think by the end of the weekend, I should be able to update the pull request with the changes you mentioned!
Thank you, and see you soon.
