### ISSUE TITLE
[DICT] Add Python support for get

### ISSUE THREAD

**Issue by EmilyBourne** [pyccel/pyccel#1885]
### Describe the feature
Syntactic and semantic support should be added for `get`. This should be tested by implementing Python printing

### Test Code
Provide code which does not currently work but which should do when this issue is fixed:
```python
def foo():
    a = {1,1.0, 2:2.0}
    b = a.get (1)
    c = a.get(3, 4.0)
    return b, c
```

**Comment by learning-dev** [comment]
@EmilyBourne  Please assign this to me. I will take this up. Thanks for the reference comment on the previous issue.

**Comment by EmilyBourne** [comment]
@learning-dev I have assigned you. I recommend basing your branch off devel-issue1886
