### ISSUE TITLE
[DICT] Add Python support for setdefault 

### ISSUE THREAD

**Issue by EmilyBourne** [pyccel/pyccel#1888]
### Describe the feature
Syntactic and semantic support should be added for `setdefault`. This should be tested by implementing Python printing

### Test Code
Provide code which does not currently work but which should do when this issue is fixed:
```python
def foo():
    a = {1,1.0, 2:2.0}
    b = a.setdefault(1, 3.0)
    c = a.setdefault(3, 4.0)
    return a, b, c
```

**Comment by learning-dev** [comment]
Hi @EmilyBourne, can you please assign this to me? I will take this up.

**Comment by EmilyBourne** [comment]
Hi @learning-dev, I'm happy to assign either this issue or #1889 to you but I prefer to assign one issue at a time to new contributors so issues don't get stuck if new contributors struggle with their first issue or become disinterested after their first issue. I hope you understand.

Do you have a preference between #1888 and #1889? Do you need any guidance on how to go about solving the issue?

**Comment by learning-dev** [comment]
@EmilyBourne , please assign me this one #1888.

**Comment by EmilyBourne** [comment]
The support for `dict.setdefault` should be implemented in a similar way to the support for set and list methods. The steps to resolve this issue are:
- [ ] Add a class to represent the method in this file: https://github.com/pyccel/pyccel/blob/devel/pyccel/ast/builtin_methods/dict_methods.py (see https://github.com/pyccel/pyccel/blob/devel/pyccel/ast/builtin_methods/set_methods.py for examples)
- [ ] Ensure that the method is recognised as a method of the class `dict` by making the necessary changes in this file: https://github.com/pyccel/pyccel/blob/devel/pyccel/ast/class_defs.py
- [ ] Add tests in this file: https://github.com/pyccel/pyccel/blob/devel/tests/epyccel/test_epyccel_dicts.py
- [ ] **If necessary** modify this file: https://github.com/pyccel/pyccel/blob/devel/pyccel/codegen/printing/pycode.py to ensure that the code is printed correctly in Python

If you are feeling motivated then C and Fortran printing could also be added in this PR. However this may be tricky for this issue as the dict support is still quite minimal so it will be difficult to check that the result is as expected.

If you want to tackle the C/Fortran printing you will find information about the code generation stage here:
https://github.com/pyccel/pyccel/blob/devel/developer_docs/codegen_stage.md

C support is implemented using the STC library. You can find docs for `hmap` (which we use to represent a `dict`) here:
https://github.com/stclib/STC/blob/master/docs/hmap_api.md

Fortran support is implemented using the gFTL library. You can find docs for `map` (which we use to represent a `dict`) here:
https://github.com/Goddard-Fortran-Ecosystem/gFTL/blob/main/include/v2/map/map.md#modifiers

There is documentation for developers here:
https://github.com/pyccel/pyccel/tree/devel/developer_docs

If needed, you can ask for help on the [Pyccel Discord Server](https://discord.gg/2Q6hwjfFVb)
