### ISSUE TITLE
list function incorrectly implemented

### ISSUE THREAD

**Issue by EmilyBourne** [pyccel/pyccel#1892]
### Describe the bug
The `list` function is not implemented. However as `list` appears in `builtin_functions_dict` Pyccel believes that an implementation exists:

It therefore uses `PythonList` as the `list` function however the 2 functions `list()` and `[]` are not interchangeable. As a result the generated code is wrong.

### To Reproduce
Provide code to reproduce the behavior:
```python
if __name__ == '__main__':
    a = list([1,2,3,4])
    b = [[1,2,3,4]]
    print(a)
    print(b)
```

### Error details
The output of this code is:
```
[1, 2, 3, 4]
[[1, 2, 3, 4]]
```
The generated code outputs:
```
[[1, 2, 3, 4]]
[[1, 2, 3, 4]]
```

The translation is:
```python
if __name__ == "__main__":
    a = [[1, 2, 3, 4]]
    b = [[1, 2, 3, 4]]
    print(a)
    print(b)
```

### Expected behavior
The output should be:
```python
if __name__ == "__main__":
    a = [1, 2, 3, 4]
    b = [[1, 2, 3, 4]]
    print(a)
    print(b)
```

The function `list` should be handled differently to `[]`

### Language
Python

### Additional context
The equivalent issues for tuples was resolved in #1589.
The pertinent code is:
https://github.com/pyccel/pyccel/blob/d64be7ff7072faa07ce19c9e70fa02ed45a25c9c/pyccel/ast/builtins.py#L596-L620

The solution for lists should be somewhat similar

**Comment by EmilyBourne** [comment]
cc: @Farouk-Echaref

**Comment by shoaib-moeen** [comment]
@EmilyBourne Can I look into this? As I am not familiar with the codebase any guidance will be highly appreciated. Thanks

**Comment by EmilyBourne** [comment]
Hi @shoaib-moeen , thanks for your interest in Pyccel. Unfortunately I don't think this is the right issue to start with. @Farouk-Echaref is taking care of issues related to lists and this issue is his next priority as it is already blocking the PR that he is currently working on.

As a first issue I would recommend picking one of the issues tagged with the label "good-first-issue". Feel free to contact me on the [Pyccel Discord Server](https://discord.gg/2Q6hwjfFVb) if you want to discuss which issue would suit you best. Pyccel maintains [developer docs](https://github.com/pyccel/pyccel/tree/devel/developer_docs) so hopefully not being familiar with the codebase is not too much of a hindrance, especially for the good-first-issues which are chosen to be non-urgent, and reasonably small.

**Comment by shoaib-moeen** [comment]
Hi @EmilyBourne, I have already fixed the issue thanks to the relevant code provided by you. I ll submit a PR shortly. Just take a look and let me know what you think.

**Comment by EmilyBourne** [comment]
@shoaib-moeen Ah! That's great then :) I'll have a look this evening once it's been opened
