### ISSUE TITLE
Incorrect Handling of Function Name Overlap with Special Names in Target Language

### ISSUE THREAD

**Issue by smazouz42** [pyccel/pyccel#1913]
### Describe the bug
Incorrect handling occurs when using a faction name that overlaps with a special name in the target language. When Pyccel renames the function, it should be found by the new name assigned by Pyccel

### To Reproduce
code to reproduce the behavior:
```python
def order_c(x:int, y:int):
    return x + y
x = order_c(1, 2)


```

### Error details
the error message:
```ERROR at annotation (semantic) stage
pyccel:
 |fatal [semantic]: test.py [3,4]| Undefined function (order_c)
```

### Expected behavior
the code should work just fine and gave this result 
```c
#include "test.h"
#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>

int64_t x;
bool initialised;

int64_t order_c(int64_t x, int64_t y)
{
    return x + y;
}

void test__init(void)
{
    if (!initialised)
    {
        x = order_c(INT64_C(1), INT64_C(2));
        initialised = 1;
    }
}

```

### Language
language the python code is translated to (c language)

**Comment by EmilyBourne** [comment]
The result should not be the one shown above as this example has removed the renaming leaving the conflict between the function `order_c` and the enum `order_c` (from ndarrays). The code should be:

```c
#include "tmp_new.h"

int64_t x;
bool initialised;

/*........................................*/
int64_t order_c_0001(int64_t x, int64_t y)
{
    return x + y;
}
/*........................................*/
/*........................................*/
void tmp_new__init(void)
{
    if (!initialised)
    {
        x = order_c_0001(INT64_C(1), INT64_C(2));
        initialised = 1;
    }
}
/*........................................*/
```
