### ISSUE TITLE
Online docs (readthedocs) inconsistent with documentation sources

### ISSUE THREAD

**Issue by ashwinvis** [pyccel/pyccel#193]
Two issues:

* Last passed bulid was a year ago: https://readthedocs.org/projects/pyccel/builds/7960602/
* Source code missing from tutorials (see for example, https://pyccel.readthedocs.io/tutorial.html#hello-world)

**Comment by EmilyBourne** [comment]
Link to old docs has now been removed. Up to date docs are in the process of being added in the tutorial/ folder
