### ISSUE TITLE
Exporting code in Codegen is done a character at a time

### ISSUE THREAD

**Issue by jalalium** [pyccel/pyccel#1933]
### Relevant Discussion
the `export` method in the `Codegen` writes to the file a character at a time when the code is a string instead of a list of strings

### Describe the feature
When the code is a single string ` for line in code:` actually loops over the characters of the string instead of the lines. This makes it both ambiguous and slow.

### Test Code
```python
      code = self._printer.doprint(self.ast)
        with open(filename, 'w', encoding="utf-8") as f:
            for line in code:
                f.write(line)

        # print module header
        if header_ext is not None:
            code = self._printer.doprint(ModuleHeader(self.ast))
            with open(header_filename, 'w', encoding="utf-8") as f:
                for line in code:
                    f.write(line)

        # print program
        prog_filename = None
        if self.is_program and self.language != 'python':
            folder = os.path.dirname(filename)
            fname  = os.path.basename(filename)
            prog_filename = os.path.join(folder,"prog_"+fname)
            code = self._printer.doprint(self.ast.program)
            with open(prog_filename, 'w') as f:
                for line in code:
                    f.write(line)
```

### Proposed Solution

A solution would be to check for when the code is a single line, if it is not always the case at the time being.

**Comment by EmilyBourne** [comment]
Can code actually be either a list of strings or a string? I thought `doprint` always returned a string?
This might explain why the codegen stage is so much slower than the rest!

**Comment by jalalium** [comment]
> Can code actually be either a list of strings or a string? I thought `doprint` always returned a string? This might explain why the codegen stage is so much slower than the rest!

I haven't stumbled upon any case that returns a list. I figured that since lines are extracted from code, then code should be a list, but it is an erroneous conclusion.  

Yes, this might be one of the reasons why codegen is slow. I also noticed that certain methods can be made much faster if conditions are reorderd/added to make them fall fast. I will create issues for them once I formalize my observation.

So, to fix this issue, is it safe to assume code will always be a string?

**Comment by EmilyBourne** [comment]
> is it safe to assume code will always be a string?

Given how codegen is written I think this is a safe assumption. At worse we should see a problem in the CI.

> I will create issues for them once I formalize my observation.

That sounds great! Codegen and wrapper are the main bottlenecks. They are 10-100x slower than syntax+semantic which seems unreasonable
