### ISSUE TITLE
Requirements_doc.txt is not up to date

### ISSUE THREAD

**Issue by EmilyBourne** [pyccel/pyccel#195]
The requirements ask for sympy=1.1.1 but pyccel/codegen/printing/pycode.py uses sympy.printing.pycode which does not seem to be available in this version of sympy.

**Comment by yguclu** [comment]
I am going to update our `README` and remove the obsolete `requirements_doc.txt`.

**Comment by yguclu** [comment]
This issue will be solved once pull request #199 is accepted.
