### ISSUE TITLE
Extend The `C` support for `min` and `max` for more than two variables

### ISSUE THREAD

**Issue by jalalium** [pyccel/pyccel#1980]
### Relevant Discussion
`Min` and `Max` functions are limited to two variables in the `CCodePrinter` . This limitation prevents from using features such as zipping over more than two lists.

### Describe the feature
The feature should allow for the calculation of the min/max of any iterable.

### Proposed Solution
Two solutions are proposed to remedy to this issue:
- nested ternary operators but this will hinder readability
- a variadic function with a string for type declaration along with the iterable

**Comment by EmilyBourne** [comment]
This issue is important for Psydac

**Comment by jalalium** [comment]
> This issue is important for Psydac

What solution do you see fit?

**Comment by EmilyBourne** [comment]
> > This issue is important for Psydac
> 
> What solution do you see fit?

I would be fine with either. The first solution could be done in the semantic stage (e.g. transform `Min(1,2,3)` into `Min(1, Min(2,3))` which would make it work out of the box for both C and Fortran, but I agree that the second solution is more readable.

What is the status of this issue on the fortran side? Does Fortran handle this with intrinsics? If so then a variadic is probably best

**Comment by jalalium** [comment]
> > > This issue is important for Psydac
> > 
> > 
> > What solution do you see fit?
> 
> I would be fine with either. The first solution could be done in the semantic stage (e.g. transform `Min(1,2,3)` into `Min(1, Min(2,3))` which would make it work out of the box for both C and Fortran, but I agree that the second solution is more readable.
> 
> What is the status of this issue on the fortran side? Does Fortran handle this with intrinsics? If so then a variadic is probably best

Yes, Fortran handles it with `maxval`, an intrinsic function that takes the args as an array. Shall we do the same for C? Do we need to extend the support for heterogeneous args?

**Comment by EmilyBourne** [comment]
> > > > This issue is important for Psydac
> > > 
> > > 
> > > What solution do you see fit?
> > 
> > I would be fine with either. The first solution could be done in the semantic stage (e.g. transform `Min(1,2,3)` into `Min(1, Min(2,3))` which would make it work out of the box for both C and Fortran, but I agree that the second solution is more readable.
> > 
> > What is the status of this issue on the fortran side? Does Fortran handle this with intrinsics? If so then a variadic is probably best
> 
> Yes, Fortran handles it with `maxval`, an intrinsic function that takes the args as an array. Shall we do the same for C? Do we need to extend the support for heterogeneous args? 

That sounds like it would also be a simple way to manage it. If we are using a list anyway then we should check if STC already has something for this in the algorithms.

Can inhomogeneous arguments be managed? I seem to remember that `max(2, 1.0)` gives `2` not `2.0` so it isn't possible to determine the return type

**Comment by jalalium** [comment]
> > > > > This issue is important for Psydac
> > > > 
> > > > 
> > > > What solution do you see fit?
> > > 
> > > 
> > > I would be fine with either. The first solution could be done in the semantic stage (e.g. transform `Min(1,2,3)` into `Min(1, Min(2,3))` which would make it work out of the box for both C and Fortran, but I agree that the second solution is more readable.
> > > What is the status of this issue on the fortran side? Does Fortran handle this with intrinsics? If so then a variadic is probably best
> > 
> > 
> > Yes, Fortran handles it with `maxval`, an intrinsic function that takes the args as an array. Shall we do the same for C? Do we need to extend the support for heterogeneous args?
> 
> That sounds like it would also be a simple way to manage it. If we are using a list anyway then we should check if STC already has something for this in the algorithms.
> 
> Can inhomogeneous arguments be managed? I seem to remember that `max(2, 1.0)` gives `2` not `2.0` so it isn't possible to determine the return type

STC does not seem to have a specific function for this. Shall we add it to the STC_extensions?
