### ISSUE TITLE
Improve template extension integration for STC

### ISSUE THREAD

**Issue by jalalium** [pyccel/pyccel#2012]
### Relevant Discussion

The  `pyccel/stdlib/STC_Extensions` module is intended to extend the `STC` container with additional functionalities. However, the actual scheme is very limiting and does not align with `STC` intended mechanism for extending the library.
In `STC`, the following include is added at the end of each container header:
```C
#include "priv/template2.h"
```
This include reads as follows:

```C
#ifdef i_more
#undef i_more
#else
#undef i_TYPE
#undef i_type
#undef i_tag
#undef i_imp
#undef i_opt
#undef i_less
#undef i_cmp
#undef i_eq
#undef i_hash
#undef i_capacity
#undef i_raw_class

#undef i_val
#undef i_val_str
#undef i_val_ssv
#undef i_val_arcbox
#undef i_val_class
....
```
This means that if `i_more` is not defined, all low level attributes of the container will go out of scope after the import and thus won't be accessible in the extension headers. This is precisely why we can't but redefine macros like:
```C
#define _c_MEMB(name) c_JOIN(i_type, name)
```
in `List_extensions`  and `Set_extensions`.

### Describe the feature
The feature should do the following:

- During the codegen stage, imports of the extension headers should be combined with the imports of the initial containers.
- In the import printing, a `#define i_more` should be added in the case of extensions.

A discussion should be had about the way to add templated features that do not require any containers per se, most likely through extending `common.h`

### Test Code
Provide code which does not currently work but which should do when this issue is fixed:
```C
#ifndef _VEC_INT64_T
#define _VEC_INT64_T
#define i_type vec_int64_t
#define i_key int64_t
#include <stc/vec.h>
#endif // _VEC_INT64_T

#ifndef _TOOLS_LIST_VEC_INT64_T
#define _TOOLS_LIST_VEC_INT64_T
#define i_type vec_int64_t
#define i_key int64_t
#include <List_extensions.h>
#endif // _TOOLS_LIST_VEC_INT64_T
```

### Proposed Solution
```C
#ifndef _VEC_INT64_T
#define _VEC_INT64_T
#define i_type vec_int64_t
#define i_key int64_t
#define i_more
#include <stc/vec.h>
#include <List_extensions.h>
#endif // _VEC_INT64_T
```

**Comment by EmilyBourne** [comment]
Fixed in #2041
