### ISSUE TITLE
When functions have multiple outputs the order is not conserved

### ISSUE THREAD

**Issue by EmilyBourne** [pyccel/pyccel#203]
The order of the out parameters is not deterministic for functions returning tuples.

For example calling pyccel on the a file containing the following code:
```
from pyccel.decorators import external, pure

@external
@pure
def get_2_3():
    return 2,3
```

can generate both of the following versions of fortran code :

```
module tmp

implicit none




contains

!........................................
pure subroutine get_2_3(Dummy_117, Dummy_76)

implicit none
integer(kind=4), intent(out)  :: Dummy_117
integer(kind=4), intent(out)  :: Dummy_76

Dummy_117 = 2
Dummy_76 = 3
return
end subroutine
!........................................

end module
```
(where the out parameters are in the original order and the code provides the same result when run through f2py)

and :
```
module tmp

implicit none




contains

!........................................
pure subroutine get_2_3(Dummy_357, Dummy_255)

implicit none
integer(kind=4), intent(out)  :: Dummy_357
integer(kind=4), intent(out)  :: Dummy_255

Dummy_255 = 2
Dummy_357 = 3
return
end subroutine
!........................................

end module
```
(where the values are returned in the wrong order)

**Comment by yguclu** [comment]
@EmilyBourne: Your example does not work anymore with Pyccel after the changes in `ast.f2py`. Function `as_static_function` raises this error at [line 64](https://github.com/pyccel/pyccel/blob/8158163df41e2f3873136cdc5a9c0e6e18f84bae/pyccel/ast/f2py.py#L64):
```
NotImplementedError: when len(results) > 1
```
Hopefully this should be easy to fix. @saidctb: What do you think?

**Comment by yguclu** [comment]
@EmilyBourne: I am working on this issue in branch [multiple-function-outputs](https://github.com/pyccel/pyccel/tree/multiple-function-outputs). I can now run your example with Pyccel and reproduce the issue.

**Comment by yguclu** [comment]
@EmilyBourne: I think I have fixed the issue, but we need some unit tests. I will create a pull request anyway.
