### ISSUE TITLE
[STR] Add C support for local string declarations

### ISSUE THREAD

**Issue by EmilyBourne** [pyccel/pyccel#2061]
### Describe the feature
Pyccel contains some minimal support for strings. Eventually we would like to expand on this support, however as a first step C support should be brought up to the level of Fortran support in order to allow strings to be used as keys for dictionaries.

As a first step support should be added for declaring a string locally

### Test Code
Provide code which does not currently work but which should do when this issue is fixed:
```python
def f():
    a = 'abcdef'
    b = '123456'
```

### Proposed Solution
The declaration of strings should be managed via `cstr` from STC. The associated documentation can be found here:
https://github.com/stclib/STC/blob/master/docs/cstr_api.md

The generated code should be:
```c
void f() {
    cstr a;
    a = cstr_lit("abcdef");
    cstr_drop(&a);
    a = cstr_lit("123456");
    cstr_drop(&a);
}
```
In the semantic stage, this will need to be handled with the `Allocate` node. In the codegen stage, this will need to be handled in `_print_Assign`, `_print_Allocate` and `_print_Deallocate`

**Comment by GusToughSon** [comment]
1. Semantic Stage: Handling String Allocation
In the semantic analysis phase, strings should be recognized and handled by the Allocate node.

Code Changes:

Modify the semantic pass to identify string literals and assign them to the Allocate node.
Example:

# Detect string allocation in the semantic phase
if isinstance(expr, String):
    allocate_node = Allocate(variable=Variable(dtype='cstr', name=expr.name))
    return allocate_node
This will ensure that Allocate nodes are created for strings like a = 'abcdef'.

2. Code Generation Stage: Assignments
The _print_Assign method should be updated to handle string assignments using cstr_lit.

Code Changes:

def _print_Assign(self, expr):
    # Check if the variable type is a string (cstr)
    if expr.lhs.dtype == 'cstr':
        return f"{expr.lhs.name} = cstr_lit({expr.rhs});"
    # Handle other types as usual
    return super()._print_Assign(expr)
Example Input:

a = 'abcdef'
Generated Output:

a = cstr_lit("abcdef");
3. Code Generation Stage: Deallocation
The _print_Deallocate method should ensure that cstr_drop is called for strings before they go out of scope.

Code Changes:

def _print_Deallocate(self, expr):
    # Check if the variable type is a string (cstr)
    if expr.variable.dtype == 'cstr':
        return f"cstr_drop(&{expr.variable.name});"
    # Handle other types as usual
    return super()._print_Deallocate(expr)
Example Input:

deallocate(a)
Generated Output:

cstr_drop(&a);
4. End-to-End Example: Test Code
Given the Python function:

def f():
    a = 'abcdef'
    b = '123456'
Generated C Code:

void f() {
    cstr a, b;

    a = cstr_lit("abcdef");
    b = cstr_lit("123456");

    cstr_drop(&a);
    cstr_drop(&b);
}
5. Verification
Compile and run the generated C code to ensure correctness:

Include the stc/cstr.h header.
Link with the required UTF-8 library if necessary.
Run the code to check for memory leaks and string handling.
Conclusion
This implementation ensures that Pyccel can handle string declarations, assignments, and deallocations effectively by leveraging the cstr API from STC. Let me know if you'd like assistance with testing or additional implementation details!
