### ISSUE TITLE
np.arctan2(a,b) translated to atan(a/b)

### ISSUE THREAD

**Issue by EmilyBourne** [pyccel/pyccel#207]
Numpy's arctan2 is translated to atan combined with a division. This will cause problems if b=0 when the function should return pi/2. Fortran has a function atan2. This should be used instead

**Comment by yguclu** [comment]
As far as I understand, Pyccel maps Numpy's `arctan2` to Sympy's `atan2`, and then it relies on Sympy's Fortran printer. So I think this is a bug in Sympy.

@ratnania, @saidctb: What do you think?

**Comment by EmilyBourne** [comment]
Fixed by PR  #322
