### ISSUE TITLE
Using type hinting with class attribute named `data` causes bug in `Fortran`

### ISSUE THREAD

**Issue by jalalium** [pyccel/pyccel#2111]
### Describe the bug
Using type hinting with a class attribute named data causes a double declare in Fortran.

### To Reproduce
```python
class A:
    def __init__(self, x : int):
        self.data :'int'= x

if __name__ == "__main__":
    a = A(4)
    print(a.data)
```

### Error details
```fortran
 type, public :: A
    integer(i64) :: data_0001
    integer(i64) :: data_0001
    logical(b1), private :: is_freed

    contains
    procedure :: create => a_create
    procedure :: free => a_free
  end type A
```

### Expected behavior
Not sure why this only happens with `data`

### Language
Fortran

**Comment by EmilyBourne** [comment]
This seems to be related to keywords. Data is one of the conflicting keywords:

https://github.com/pyccel/pyccel/blob/6aefd2178efcd0f230dde182a0a7fc04fab18764/pyccel/naming/fortrannameclashchecker.py#L24-L48

Choosing another name from this list (e.g. `block`) gives the same problem

**Comment by EmilyBourne** [comment]
There is a similar error in C when using a C keyword (e.g. `default`):
```c
struct A {
    int64_t default_0001;
    int64_t default_0001;
    bool is_freed;
};
```
so this is probably an error in the semantic stage
