### ISSUE TITLE
Argument detected as intent(in) instead of intent(inout) even if call to another function changes its value.

### ISSUE THREAD

**Issue by EmilyBourne** [pyccel/pyccel#218]
Related to issue #198 .

When using functions from another python file the file is not read which means that all arguments are marked as in when they might be inout.

E.g.:

file1:
```
from pyccel.decorators import pure, types

@pure
@types('double[:]')
def mult_2(x):
    for i, xi in enumerate(x):
        x[i] = xi * 2
```

file2:
```
from pyccel.decorators import external, pure, types
from file1 import mult_2

@external
@pure
@types('double[:]','double[:]')
def add_2(a,b):
    mult_2(a)
    b = b + a
```

x is correctly identified as inout, but a is identified as in.

**Comment by EmilyBourne** [comment]
This problem no longer seems to be contained to functions in different files. The following file has the same problem:
```
from pyccel.decorators import external, pure, types

@pure
@types('double[:]')
def mult_2(x):
    for i, xi in enumerate(x):
        x[i] = xi * 2

@external
@pure
@types('double[:]','double[:]')
def add_2(a,b):
    mult_2(a)
    b = b + a
```

**Comment by yguclu** [comment]
@EmilyBourne So in your example the argument `x` of `mult_2` has `intent(inout)`, but the argument `a` of `add_2` has `intent(in)`?

**Comment by EmilyBourne** [comment]
This is the generated code:
```
module test

implicit none




contains

!........................................
pure  subroutine mult_2(x)

implicit none
real(kind=8), intent(inout)  :: x (0:)
integer(kind=8)  :: i
real(kind=8)  :: xi

do i = 0, size(x,1)-1_8, 1
  xi = x(i)
  x(i) = xi * 2_8


end do

end subroutine
!........................................

!........................................
pure  subroutine add_2(a, b)

implicit none
real(kind=8), intent(in)  :: a (0:)
real(kind=8), intent(inout)  :: b (0:)

call mult_2(x=a)
b = b + a
end subroutine
!........................................

end module
```

**Comment by yguclu** [comment]
This seems to be a fairly serious bug. We must be missing something during the annotation stage, when we visit a FunctionCall.

**Comment by yguclu** [comment]
@EmilyBourne Is the `@external` decorator playing any role in your example? I thought we had it removed with PR #282

**Comment by EmilyBourne** [comment]
@yguclu no it isn't. I didn't modify the code from January, hence the 'external'. I can confirm that removing it changes nothing.
Shouldn't pyccel raise an error if we use an unrecognised decorator?

**Comment by EmilyBourne** [comment]
> This seems to be a fairly serious bug. We must be missing something during the annotation stage, when we visit a FunctionCall.
You are right we are missing the `FunctionCall` case in the function `get_assigned_symbols`. This is an easy fix I can create a PR

**Comment by yguclu** [comment]
> @yguclu no it isn't. I didn't modify the code from January, hence the 'external'. I can confirm that removing it changes nothing.
> Shouldn't pyccel raise an error if we use an unrecognised decorator?

Since Pyccel does not support user-defined decorators, we should raise an error. But more importantly, I don't understand why we do not get an error when processing the line
```from pyccel.decorators import external```

**Comment by saidctb** [comment]
I forgot to add the case of `FunctionCall` case in `get_assigned_symbols`

**Comment by EmilyBourne** [comment]
@yguclu @saidctb 
> But more importantly, I don't understand why we do not get an error when processing the line
> `from pyccel.decorators import external`

I have looked into this and it seems that it comes from the handling of `pyccel.decorators` in the syntactic step.
These lines: https://github.com/pyccel/pyccel/blob/master/pyccel/parser/syntactic.py#L498-L499
```
        if is_ignored_module(source):
            return EmptyLine()
```
handle the case of `pyccel.decorators`. This is a different method to the one used for most imports, e.g. `numpy`, `scipy`.

For these imports, an Import object is created however they are not added to the namespace. They are then handled in the function `builtin_import` : https://github.com/pyccel/pyccel/blob/master/pyccel/ast/utilities.py#L176

If we use the second method to handle the line `from pyccel.decorators import external` then we can use the `inspect` module to raise an error (or a warning) if the target is not defined in `decorators.py`

If you agree with this method then we can create an issue for this. It is easy to fix so it can be fixed in the branch devel-issue327 along with the other error problems
