### ISSUE TITLE
Numpy rand not working

### ISSUE THREAD

**Issue by EmilyBourne** [pyccel/pyccel#223]
rand from numpy.random cannot be pyccelized. This is marked as to do in tests/codegen/scripts/numpyext.py

**Comment by yguclu** [comment]
We should also change the target Fortran subroutine from `rand` (GNU Fortran 77) to `random_number` (Fortran 90 standard), and support array INOUT arguments as well as scalars.

**Comment by EmilyBourne** [comment]
Currently, rand is partially supported:
```
from numpy.random import rand
a = rand()
```
Is supported but calling rand with arguments is not yet supported
