### ISSUE TITLE
Check the validity of variables  and functions names before converting it to Fortran

### ISSUE THREAD

**Issue by saidctb** [pyccel/pyccel#225]
In Python we can have  names  of variables and functions that starts with `_`  like  `_x` or `_func`,
in that case we should raze an error  or maybe change the names to a valid one.
also Python treats upper case variable names and lower case variable names as two different set of variables but Fortran sees them as one  for example the variable with names  `x` and `X` are two different variables in python but the same in Fortran, so we should either raise an error or change the names

**Comment by EmilyBourne** [comment]
Fixed by #1089
