### ISSUE TITLE
Create module to handle naming

### ISSUE THREAD

**Issue by EmilyBourne** [pyccel/pyccel#227]
We should have a module to handle names in pyccel. Currently there are multiple places where things are (or aren’t but should be) done to avoid name problems in fortran. It would be clearer if this was managed in one place. Possible problems include

- Case sensitivity:
    python is case sensitive but fortran isn't.
    x and X should be translated differently in fortran. What name should be used?
- Underscores:
    python names can start with underscores or even be underscores but fortran names can't.
    How should these variables be renamed?
- Name collisions:
    Sometimes names are generated with a random string to avoid name collisions.
    Name collisions could occur in different circumstances:
      - multiple functions epyccelized which have the same name
      - epyccelizing modules with the same name (ie. import a and import b.a)
      - renaming variables to manage "import module" syntax
- Fortran keywords
    Check that the names used in python are not fortran or c keywords
- Python keywords
    Builtin functions can be overridden in python but this is inadvisable. Therefore pyccel does not handle this information. An error should be raised if the user does this
- Lengthy names
    Names are limited to 96 characters in fortran. An error should be raised if the user has longer names

**Comment by EmilyBourne** [comment]
If functions are renamed to avoid case sensitivity name collisions then the correct name can be used in a c wrapper if this is used instead of f2py

**Comment by yguclu** [comment]
> If functions are renamed to avoid case sensitivity name collisions then the correct name can be used in a c wrapper if this is used instead of f2py (see issue #370)

Do you mean that after moving away from f2py we could print to Fortran the original Python names, which may contain capital letters, whenever we don't have name clashes?

**Comment by EmilyBourne** [comment]
> Do you mean that after moving away from f2py we could print to Fortran the original Python names, which may contain capital letters, whenever we don't have name clashes?
No. We can already do that. Let me provide an example. The following python code:
```
def littleTest():
    return 2
```
is translated to:
```
module test

implicit none

contains

!........................................
function littleTest() result(Out_0001)

  implicit none

  integer(kind=8) :: Out_0001

  Out_0001 = 2_8
  return

end function littleTest
!........................................

end module test
```
However as fortran is not case sensitive to call this function in C, you have to call `littletest()` in c. If we write our own wrapper this would be written:
```
static PyObject * littleTest_wrapper(PyObject *self, PyObject *args)
{

    long Out_0001;
    if (!PyArg_ParseTuple(args, "" ))
        return NULL;
    Out_0001 = littletest(); // call to fortran function
    return Py_BuildValue("l", Out_0001);
}

static PyMethodDef test_methods[] = {
    { "littleTest", littleTest_wrapper, METH_VARARGS, "" }, // name exposed to python
    { NULL, NULL, 0, NULL }
};
```
and as C is case sensitive we can then call test.littleTest from python. f2py however uses the same name for the call in the wrapper and for the name exposed to python. As a result currently when we translate the example we must convert the name to lower case when we want to use it.
```
In [1]: import test

In [2]: dir(test)
Out[2]: 
['__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '__version__',
 '_test_error',
 'littletest']
```
