### ISSUE TITLE
pyccel silently fails on errors

### ISSUE THREAD

**Issue by krystophny** [pyccel/pyccel#240]
Currently pyccel fails without any error messages if an exception is not handled. This is due to `try` blocks without `except`, such as in `console.py:205`. For the following example pyccel doesn’t complain but also doesn’t work:

```python

import numpy as np
from pyccel.decorators import types

@types('real[:]', 'real[:]', 'real[:]')
def kern_sqexp(x0, x1, h):
    """Generic squared exponential kernel"""
    return h[0]*np.exp(-np.sum((x1 - x0))**2/(2.0*h[1]**2))

@types('real[:]', 'real[:]', 'real[:]')
def kern_wendland4(x0, x1, h):
    """Wendland kernel for dimension <= 3"""
    r = np.abs(np.sqrt(np.sum((x1 - x0))**2)/h[1])
    if r < 1.0:
        ret = h[0]*(1.0 - r**4)*(1.0 + 4.0*r)
    else:
        ret = 0.0
    return ret

@types('real[:]', 'real[:]', 'real[:]')
def kern_wendland4_product(x0, x1, h):
    """Wendland product kernel"""
    dx = np.abs(np.sqrt((x1 - x0)**2)/h[1])
    if np.all(dx < 1.0):
        ret = h[0]*np.prod((1.0 - dx**4)*(1.0 + 4.0*dx))
    else:
        ret = 0.0
    return h[0]*np.prod((1.0 - dx**4)*(1.0 + 4.0*dx))
```

**Comment by krystophny** [comment]
Update: In that case `show_traceback=False` was set in `parser/base.py` per default. Switching it on shows an error message. In any case one should maybe exit with code nonzero and write the error somewhere / inform the user that something went wrong, even if one doesn’t want to print the full stack trace. 

A similar problem concerns `x.T` or `x.transpose()` which is just pyccelized as `x` without error or warning that this operation is not supported. This can lead to wrong results without the user knowing.

**Comment by EmilyBourne** [comment]
> Update: In that case `show_traceback=False` was set in `parser/base.py` per default. Switching it on shows an error message. In any case one should maybe exit with code nonzero and write the error somewhere / inform the user that something went wrong, even if one doesn’t want to print the full stack trace.

`show_traceback` can now be set to true by using the option `--verbose`

**Comment by EmilyBourne** [comment]
If pyccel produces errors at a given step (syntactic, semantic, codegen) then the objects are no longer sure to be correct in the future stages. Shouldn't pyccel fail at this point (at least for fatal errors) rather than trying to continue anyway?

**Comment by yguclu** [comment]
I agree. I think that Pyccel should always stop at the end of the current stage if an error was encountered.
