### ISSUE TITLE
Booleans fail

### ISSUE THREAD

**Issue by krystophny** [pyccel/pyccel#241]
Trying the following with epyccel/pyccel fails with a gfortran compile error. Reason is that it tries to set logical(kind=0) which doesn’t work in Fortran. Opened branch `devel-base` with a test case in `tests/epyccel/test_base.py`.

```python
@types('bool', 'bool')
def cmp_bool(a, b):
    c = False
    if a == b:
        c = True
    return c
```

produces

```fortran
function cmp_bool(a, b) result(c)

  implicit none
  logical(kind=0) :: c !!!!!!!!!! HERE IT FAILS !!!!!!!!!! 
  logical(kind=1), intent(in)  :: a 
  logical(kind=1), intent(in)  :: b 

  c = .False.
  if (a == b ) then
    c = .True.
  end if
  return
end function
```

**Comment by krystophny** [comment]
Another problem: printing `a == b` done currently doesn't work, Fortran requires `a .eq. b` instead.

**Comment by yguclu** [comment]
Actually, since Fortran 90/95 `==` is accepted and much clearer than `.eq.`. Maybe somewhere we pass the flag `-std=f77` to the compiler?

**Comment by krystophny** [comment]
Logicals are still different. They need `.eqv.` and `.neqv.` operators, and don't even work with `.eq.` which is now `==`.

**Comment by yguclu** [comment]
Yes, I see your point now! Sorry for the confusion.

**Comment by krystophny** [comment]
...also a is b and a is True won't work as a workaround. I'm getting the error
```
NotImplementedError: Only None rhs is allowed in Is statement
```

**Comment by krystophny** [comment]
In `_visit_ComparisonNode(self, stmt)` we have a lot of property flags in first and second arguments. These are just set as atomic symbols with all other flags on false. Could one somehow set `is_boolean flag` to `True` or will that break something?

... or do these flags mean something different and should all be false if first and second are set as symbols with `is_atom=True` ?

**Comment by krystophny** [comment]
Update: equality and inequality `==`, `!=` and `is` are working in `devel-base` with unit tests. What is failing now still is the `is not` clause, probably because I did something wrong / too general in https://github.com/pyccel/pyccel/blob/50eb37989adcfde5cc900168f3512380ecda9cba/pyccel/parser/semantic.py#L2770-L2792

**Comment by yguclu** [comment]
@krystophny @EmilyBourne Can we close this issue?

**Comment by EmilyBourne** [comment]
Ok with me

**Comment by krystophny** [comment]
Closed
