### ISSUE TITLE
Check for dead fprint code of numpyext

### ISSUE THREAD

**Issue by krystophny** [pyccel/pyccel#243]
As the base class in numpy types is mostly `Function`, I believe that the `fprint` statements never get called in https://github.com/pyccel/pyccel/blob/d56ecd774b51f3309ff42e6d4b3bbaaad4927d82/pyccel/ast/numpyext.py#L145-L152

This is already mentioned in TODOs and also (probably?) makes the following unnecessary for most of the cases. https://github.com/pyccel/pyccel/blob/d56ecd774b51f3309ff42e6d4b3bbaaad4927d82/pyccel/codegen/printing/fcode.py#L623-L642

**Comment by krystophny** [comment]
Seems like this code shouldn't be dead. It's just not used if an assignment is made in https://github.com/pyccel/pyccel/blob/d56ecd774b51f3309ff42e6d4b3bbaaad4927d82/pyccel/codegen/printing/fcode.py#L991 the Function name is printed instead of using the actual print routine.

**Comment by yguclu** [comment]
There may be still some dead code in module `pyccel.codegen.fcode`, but I think that #260 fixes the main issue: the `fprint` methods defined in `numpyext` get called also in the case of Function subclasses.
