### ISSUE TITLE
Conversion of negative indexes in arrays

### ISSUE THREAD

**Issue by krystophny** [pyccel/pyccel#248]
Currently, `a[-1]` is translated literally to `a(-1)` in Fortran, causing an out-of-bounds warning, and probably not intended behavior. Would it make sense to change it to `a(ubound(a,dim))`? See https://stackoverflow.com/questions/20986269/how-do-i-access-last-item-in-an-array-in-fortran/20986963

**Comment by yguclu** [comment]
I agree, we can easily handle a negative index if it is a literal constant. But if we have a situation like `a[i-j]` it might be very complicated to determine whether `i-j` is positive or negative. Maybe we could always assume positive indexing, unless the user specifies otherwise with a pragma comment?

**Comment by krystophny** [comment]
Since we are starting from Python, I would handle negative indexing exactly as intended in Python, so according to https://lemire.me/blog/2006/01/05/python-allows-negative-indexing-on-arrays/ . Index -1 is the last element, -2 the second-last and so on. This needs correct translation to Fortran convention though, where actual negative indexes exist if one defines an array accordingly.

**Comment by yguclu** [comment]
For GFortran, the flag is `-fcheck=bounds` or `-fcheck=all` (the latter enables several other runtime checks).

Handling negative indices is actually quite important, Python programmers do it quite a lot, so I am pinning this issue to give it higher priority. Moreover, as this is not specific to Numpy arrays but rather a general Python feature, I am changing its milestone.

**Comment by yguclu** [comment]
After discussing with @saidctb and @EmilyBourne, we have decided to support negative indices for literal constants (e.g. `a[-1]` or `a[-2]`) and assume a positive value in all other cases.

If the user wants to use general indices with no a-priori assumptions (e.g. allow `a[i-j]` where the sign of `i-j` is only known at runtime) he/she should add the "allow_negative_index" decorator to the array `a`:
```
from pyccel.decorators import types
from pyccel.decorators import allow_negative_index

@types('double [:]')
@allow_negative_index('a')
def foo(a):
    ...
```
We should point out that the `allow_negative_index` decorator may cause significant performance degradation in the generated Fortran code.

**Comment by EmilyBourne** [comment]
This should be done in the codegen stage so python is still printed as in the original code
