### ISSUE TITLE
Make mpi4py requirement optional?

### ISSUE THREAD

**Issue by krystophny** [pyccel/pyccel#255]
Since not everyone intends to use MPI, it would be nice to have mpi4py requirement optional. This would also allow for easier use on Windows (see #194) without requiring a compiler and and installing MSMPI. Related to #251 .

**Comment by yguclu** [comment]
We only need `mpi4py` for running some of our unit tests, and Pyccel does not use it at all even when it processes a Python module/script that contains mpi4py calls. Hence we can remove mpi4py from our dependencies, and install the package in Travis just before running our unit tests.

**Comment by yguclu** [comment]
I stand corrected: `epyccel` has a parallel version that uses `mpi4py`. That is used in the case where the code generation happens within a Python parallel session.
