### ISSUE TITLE
Properly separate Python3 built-in functions from Numpy's and Math's functions

### ISSUE THREAD

**Issue by yguclu** [pyccel/pyccel#258]
The confusion is evident in [pyccel.ast.utilities](https://github.com/pyccel/pyccel/blob/65fcab425c17bcb24097f2d11561c686633c34fe/pyccel/ast/utilities.py#L26), where the `math_functions` dictionary is used for importing functions that come from both `numpy` and `math`. 

For example, `abs` is a Python3 built-in function (in which case it calls the magic method `__abs__` of its argument) and also a Numpy function, but does not exist in `math`.

We should improve `pyccel.ast` and make sure that each of the functions that we support exists in one of the following modules:
- [x] pyccel.ast.builtins
- [x] pyccel.ast.numpy_ext
- [x] pyccel.ast.math_ext
- [x] pyccel.ast.itertools_ext

To avoid name clashes we must make sure that we use different names in each module, by prepending `Python`, `Numpy`, `Math`, or `Itertool` to the class names.

**Comment by EmilyBourne** [comment]
The following functions exist in sympy and are therefore in the list of math_functions but do not have a python counterpart:

- csc
- sec
- cot

The following functions exist in ast/core.py and are therefore in the list of math_functions but do not have a python counterpart:

- Acsc
- Asec
- Acot
