### ISSUE TITLE
Improve AST

### ISSUE THREAD

**Issue by yguclu** [pyccel/pyccel#259]
In order to process all Python expressions on an equal footing, we should make sure that all Pyccel AST nodes (including Add, Mul, etc..) have a very well defined DataType, or at least contain information about:
- dtype
- precision
- rank
- shape (even if only symbolic)
- ...

This may be done by creating a small basic class that contains the properties above, and then using multiple inheritance to aggregate it with another class. For example
```
from sympy import Function
from pyccel.ast.basic import PyccelAstNode

class NumpySum(Function, PyccelAstNode):
    ...
```

We may also want to create some base classes that allow us to imitate the behavior of the Python built-in function `abs`, which searches the argument for the `__abs__` magic method.

**Comment by EmilyBourne** [comment]
The branch devel-ast can be used for this
