### ISSUE TITLE
Changes to NumpySum, Pow, ... broke working kernels

### ISSUE THREAD

**Issue by krystophny** [pyccel/pyccel#261]
Pyccelizing the file https://github.com/redmod-team/profit/blob/master/profit/sur/backend/kernels.py was working in commit 3f83257a90354ffe9695ec17452ea891aed8cbc1 . After that some changes broke that support again. Main problems after checking some adaptations are

* `AttributeError: 'NumpySum' object has no attribute 'as_base_exp'`
* `AttributeError: 'NumpySum' object has no attribute '_eval_power'`
* `TypeError: unsupported operand type(s) for -: 'NumpySum' and 'int'`
* `TypeError: Abs not supported in Fortran`

As far as I understand, now sums cannot used in exponents, powers, cannot added to ints and one cannot use Abs.

**Comment by krystophny** [comment]
Just saw that #260 fixes this

**Comment by yguclu** [comment]
Can you make some version of that file into unit tests for Pyccel? That would be very useful.

**Comment by krystophny** [comment]
Sure, just wanted to propose that too! There is another problem which I don't currently understand in the two routines I have flagged with @python, which gives 

`TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'`

so I won't add those two right now.

**Comment by krystophny** [comment]
There's now a test case in 72c1d80bd46fb4a6171e94fec6135d4eec55df87 . @EmilyBourne please check if this is the way your testing framework is intended to use. Maybe it would also be useful to use temporary directories via fixtures for such tests where Fortran and Python output is compared, e.g. as in https://github.com/pyccel/fffi/blob/master/tests/01_arrays/test_arrays.py
