### ISSUE TITLE
Clearly define tuples

### ISSUE THREAD

**Issue by EmilyBourne** [pyccel/pyccel#265]
- [x] Create tuple class with NotImplementedErrors where appropriate
       - dtype is tuple
- [x] Allow allocation with the following syntax: `a, b, c = 1, False, 3.4`
- [x] Allow allocation of inhomogeneous tuple `a = (1, False, 3.4)`
- [x] Pass tuple to function using *args syntax
- [x] Access tuple element `a[0]`
- [x] Raise error when accessing tuples using indices `a[i]`

**Comment by saidctb** [comment]
we also might want to allow `c = (1,2,3); a[c]` where a is a 3d array

**Comment by yguclu** [comment]
I agree. If the tuple only contains integers it should be possible to use it for indexing purposes.
