### ISSUE TITLE
FunctionalSum/Min/Max raise pyccel Incompatible types error when used with floats

### ISSUE THREAD

**Issue by EmilyBourne** [pyccel/pyccel#272]
The return type of a FunctionalSum/FunctionalMin/FunctionalMax is assumed to be an integer and is then reset to the type that is calculated. However if this calculated type is not an integer then errors have already been raised.

The following code shows this problem:
```
from numpy import ones

a=ones(5,'double')

a7 = sum(a[i] for i in range(5))
```

**Comment by saidctb** [comment]
Functional statements doesn't work anymore , we will need to change the way we generate them by using `lampy `

**Comment by EmilyBourne** [comment]
The error raised now is related to `dtype` etc. not being defined/correctly defined for Functional objects
