### ISSUE TITLE
Issues remaining in tuples

### ISSUE THREAD

**Issue by EmilyBourne** [pyccel/pyccel#283]
- [x] `a = (0, 'Hello', 3+1j)*2` compiles but does not translate correctly
- [x] ```a = (0, 1)
b = a * 2``` does not work (this is also true for lists)
- [x]  Tuples must be indexed with constant integers for the type inference to work even for homogeneous tuples

**Comment by yguclu** [comment]
@EmilyBourne: Can you clarify the last point? What is the current behavior right now? Do we distinguish between homogeneous and heterogeneous Tuples right now?

**Comment by EmilyBourne** [comment]
Currently we can distinguish, but the behaviour is only used to allow lists of homogeneous tuples. I must have missed this.
Currently all tuples:
`a = (1, False,3.0)`
are printed as:
`a_0 = 1
a_1 = False
a_2 = 3.0`
Therefore indexing does not work or make sense.
Homogeneous tuples need to be printed as arrays in order to allow indexing

**Comment by yguclu** [comment]
I see, it looks much safer to only treat tuples "symbolically" as you are doing now. This way we can also implement tuples that contain other tuples in the future.
