### ISSUE TITLE
Detect default integer type

### ISSUE THREAD

**Issue by krystophny** [pyccel/pyccel#289]
In order to be portable, we need to detect the default integer type (32 or 64 bit). Even on 64bit Windows, C `long` is still 32bit, in contrast to Unix. This affects #288 and must be fixed before supporting Windows. 

Tests for default integer type are now set to `xfail` in `devel-win` branch.

**Comment by EmilyBourne** [comment]
This problem is potentially not restricted to integers. See the resolved review in pull request https://github.com/pyccel/pyccel/pull/242
