### ISSUE TITLE
Do not use Fortran allocatable array to store shape of Numpy array

### ISSUE THREAD

**Issue by yguclu** [pyccel/pyccel#299]
If we pyccelize the Python module `mod_shape.py`,
```
from numpy import shape
from pyccel.decorators import types

@types('double[:,:]')
def size_tuple(a):
    s = shape(a)
    return s[0] * s[1]
```
The resulting Fortran module reads
```
module mod_shape

implicit none

contains
!........................................
function size_tuple(a) result(Dummy_1569)

  implicit none
  integer(kind=8)  :: Dummy_1569  
  real(kind=8), intent(in)  :: a (0:,0:)
  integer(kind=8), allocatable  :: s (:)

  allocate(s(0:1))
  s = [size(a,2), size(a,1)]
  Dummy_1569 = s(0_8)*s(1_8)
  return
end function
!........................................

end module
```
So the shape of the 2D array `a` is placed into the allocatable array `s`: this can create considerable overhead in certain situations, and slow the code down quite a bit. Given that Numpy's shape returns a Python tuple of integers (and known length), we should be able to use an homogeneous Pyccel Tuple with 2 integers here, which should be translated to an automatic Fortran array with 2 elements:
```
function size_tuple(a) result(res)

  real(kind=8), intent(in) :: a(0:,0:)
  integer(kind=8) :: res

  integer(kind=8) :: s(2)

  s = [size(a,2), size(a,1)]
  res = s(0_8)*s(1_8)

end function
```
Alternatively, we may treat the shape Tuple as being heterogeneous and use two integer variables to store the values:
```
function size_tuple(a) result(res)

  real(kind=8), intent(in) :: a(0:,0:)
  integer(kind=8) :: res

  integer(kind=8) :: s_0
  integer(kind=8) :: s_1

  s_0 = size(a,2)
  s_1 = size(a,1)
  res = s_0*s_1

end function
```

**Comment by EmilyBourne** [comment]
This problem comes from the function _infere_type and the fprint of Shape. It is fixed in the branch devel-ast
