### ISSUE TITLE
Implement function interfaces

### ISSUE THREAD

**Issue by yguclu** [pyccel/pyccel#301]
**Describe the improvement**
Pyccel will allow the user to declare multiple possible types for a function argument. This allows the same code to be used for multiple functions with different types.

**Test Code**
The syntax in python will be as follows:
```
# Create 4 functions
@types('int','int')
@types('real','real')
@types('int','real')
@types('real','int')
def f(a,b):
    pass

# Create 4 functions
#$ header function f(int,int)
#$ header function f(real,real)
#$ header function f(int,real)
#$ header function f(real,int)
def f(a,b):
    pass
```
The user can therefore choose to either specify all possible combinations of types (example 1)

Consider the following example:
```
#$ header function decr(int)
#$ header function decr(real)
def decr(x):
    y = x - 1
    return y
```

In this example Pyccel should generate one Fortran function where `x` is `integer`, and another function where `x` is `real`. Moreover, Pyccel should generate a **Fortran interface** for calling both functions with a common name. This interface should only exist in the module, not in the generated `f2py_mod.f90` file, here the cwrapper will handle the interface

E.g:
```
module function_decr_interface

implicit none

interface decr
module procedure decr_0
module procedure decr_1
end interface

contains

!........................................
function decr_0(x) result(y)
  implicit none
  real(kind=8)  :: y  
  real(kind=8)  :: x  
  y = x - 1_8
  return
end function
!........................................

!........................................
function decr_1(x) result(y)
  implicit none
  real(kind=8)  :: y  
  real(kind=8), value  :: x
  y = x - 1_8
  return
end function
!........................................

end module
```

For C 2 functions should be generated and the appropriate function should be used as required

This issue concerns only code generation not the cwrapper

**Comment by EmilyBourne** [comment]
This can be fixed once issue #370 has been fixed
