### ISSUE TITLE
Memory Leaks

### ISSUE THREAD

**Issue by EmilyBourne** [pyccel/pyccel#304]
Allocated arrays are not deallocated.
Errors are not raised if the same variable is allocated twice:
E.g:
```
from numpy import ones, zeros

a = ones(4)
a = zeros(4)
```
creates:
```
program prog_alloc

implicit none

real(kind=8), allocatable  :: a (:)



allocate(a(0:3_8))
a = 1.0
allocate(a(0:3_8))
a = 0.0

end program prog_alloc
```

instead of:
```
program prog_alloc

implicit none

real(kind=8), allocatable  :: a (:)



allocate(a(0:3_8))
a = 1.0
deallocate(a)
allocate(a(0:3_8))
a = 0.0
deallocate(a)

end program prog_alloc
```

**Comment by ratnania** [comment]
I think we should be careful about this. 
If we allow the user to call functions that allocate memory, then we are also allowing him to change its type:
```python
from numpy import ones, zeros

a = ones(4, float)
a = zeros(4, int)
```
which will lead to an error in any static language.
I think we should see the different possible cases and how to treat each one of them (warning, error, etc)

**Comment by yguclu** [comment]
I completely agree, this is a point that we must clarify. Once we agree on a well-defined behavior, we will have to be consistent across the library.

**Comment by saidctb** [comment]
we should be careful here in the example we should do something like
`if ( allocated(a)) deallocate(a)`  because the user can write something like
```
if (condition) then
    allocate(a(0:3_8))
    a = 1.0
end if
deallocate(a)
allocate(a(0:3_8))
a = 0.0
```

**Comment by EmilyBourne** [comment]
Whether we allow multiple allocations of the same object or not. It is still important to deallocate arrays that we allocate.
We can ask pyccel to do this explicitly by writing `del a` in the python code however this is not standard practice in python. We should therefore deallocate local allocatables at the end of functions to avoid memory leaks.

Deallocating before re-allocating might be trickier to implement correctly unless we always write:
```
if ( allocated(a)) deallocate(a)
allocate(a)
```
whether a has already been allocated or not

**Comment by saidctb** [comment]
maybe we need to enforce using `del a`  otherwise we can't determine in compile time if the array is allocated or not so we will have to add this test before allocation
`if ( allocated(a)) deallocate(a)`

**Comment by yguclu** [comment]
@EmilyBourne According to the Fortran 2003 standard, all allocatable variables are automatically deallocated when they go out of scope (please double check this, but I am pretty sure). The example you have given has to do with reallocation without prior deallocation, and that could lead to
 memory leakage indeed.

**Comment by yguclu** [comment]
When we discuss about Fortran issues, we **must** always refer to the Fortran standard. And when we discuss about Python we should refer to the latest documentation available.

**Comment by EmilyBourne** [comment]
See issue #359

**Comment by EmilyBourne** [comment]
I think this issue is fixed. Do you agree @yguclu @saidctb ?

**Comment by yguclu** [comment]
@EmilyBourne Yes, I think it is fixed.

Did we decide to raise a Pyccel warning when we add a memory reallocation to the generated code? I cannot remember... :sweat_smile:

**Comment by EmilyBourne** [comment]
@yguclu Yes we did.
The following code:
```
import numpy as np

a = np.ones(5)
a = np.ones(7)
```
raises the following warning:
```
pyccel:
 |warning [semantic]: realloc.py [4]| Array redefinition may cause memory reallocation at runtime (a)
```

**Comment by saidctb** [comment]
yes , it's fixed

**Comment by yguclu** [comment]
Oh yes, I am the one who wrote that warning message... :smile:
