### ISSUE TITLE
Improve the type inference mechanism

### ISSUE THREAD

**Issue by saidctb** [pyccel/pyccel#305]
The Sympy type inference mechanism has a lot of issues and we need to move out from it.
we now use Sympy to infer the type of any expression  by using the attributes `is_integer`, `is_real`, `is_complex` ... that are provided by Sympy,.
as a first step the `_infere_type` method of `pyccel.parser.semantics` should handle this by adding all the possible arithmetic expression type inference rules.
after that we may need to use the `PyccelAstNode` attributes where we infer the type automatically at the instance creation, which means that the type inference mechanism will be local to each class 
rather than it being handled by one method that we call `_infere_type`

**Comment by EmilyBourne** [comment]
The `PyccelAstNode` attributes should be used and initialised in the `__init__` function wherever possible to avoid recalculating values
