### ISSUE TITLE
Investigate arrays in C

### ISSUE THREAD

**Issue by EmilyBourne** [pyccel/pyccel#312]
As support for C develops we need to decide how to handle arrays. I would suggest the following:

stack-array elements:
```
@stack-array('x')
def f():
    import numpy as np
     x = np.empty(4,dtype=int)
```
```
int x[4];
```
other elements:
```
@types('int')
def f(n):
    import numpy as np
     x = np.empty(n,dtype=int)
```
```
int* x;
malloc(x,4*sizeof(int));
```

Arrays in arguments should be passed as pointers. We should also pass the size.

Operations (e.g. +/-/*/ /) will need to be done element-wise. All operations in the same line should be written in the same loop.
I.e:
```
@stack-array('x','y')
def f():
    import numpy as np
     x = np.zeros(4,dtype=int)
     y = np.ones(4,dtype=int)
     x[:] += y -5
     x[:] += 7
```
should become
```
void f() {
    int x[4];
    int y[4];
    int i;
    for ( i = 0; i < 4; ++i) {
        x[i] += y[i] - 5
    }
    for ( i = 0; i < 4; ++i) {
         x[i] += 7
     }
```

We may need to add assertions if looping over non-stack-arrays to ensure that the sizes make sense

**Comment by saidctb** [comment]
the the stack arrays size must be a const int  or an Integer literal
how are going to handle something like
```
@stack-array('x')
def f():
    import numpy as np
     n = 4
     x = np.empty(n,dtype=int)
```

**Comment by EmilyBourne** [comment]
Do we not have the same problem in fortran? How is this handled currently?

**Comment by saidctb** [comment]
sorry i made a mistake it should passed as an argument, in fortran there is no problem of that kind
you can declare it with what ever integer

**Comment by EmilyBourne** [comment]
The following code compiles with gcc and g++
```
void f(int n) {
        int x[n];
}
```
From what I can find this is allowed in C99 but not in C++0x. I would prefer the following syntax though:
```
void f(const int n) {
        int x[n];
}
```

**Comment by EmilyBourne** [comment]
If the user wants to modify n later then we should either raise an error or create a dummy variable

**Comment by saidctb** [comment]
for the multi-dimension arrays how are we going to allocate them
there is tow ways of doing it, either by doing
```
int* x;
malloc(x,n*m*sizeof(int));
``` 
or 
```
int **arr = (int **)malloc(m * sizeof(int *)); 
for (i=0; i<r; i++) 
  arr[i] = (int *)malloc(n * sizeof(int)); 
``` 
for the example
`x = empty((m,n), int)`

**Comment by EmilyBourne** [comment]
I would prefer the second as it leads to the more intuitive accessing:
`x[j][i]`
rather than
`x[j*m+i]`

**Comment by saidctb** [comment]
we probably want to do this one
```
int* x;
malloc(x,n*m*sizeof(int));
```
because numpy arrays are represented this way

**Comment by yguclu** [comment]
For efficiency reasons we should really minimize the number of memory allocations, hence I am strongly in favor of
```
int* x = malloc(n*m*sizeof(int));
```
This way access to the array elements is also faster, as there is less pointer indirection. We can still use friendly accessing in the form `x[i][j]` by using an appropriate casting:
```
int (*x)[n] = (int(*)[n]) malloc(m*n*sizeof(int));
```

**Comment by saidctb** [comment]
there is also the problem of slices, if the user takes a slice of an array how are we gonna support that ?

**Comment by yguclu** [comment]
We may need to provide our own Slice data structures in C. I think the GNU Fortran compiler does that already when they compile Fortran into their own intermediate representation (IR). See output of
```
gfortran -c main.f90 -fdump-tree-original
```

**Comment by saidctb** [comment]
So we create for every type and every dimension a data structure like
typedef struct array1_integer{
 int *data;
int lbound;
int ubound;
int stride;
}

**Comment by EmilyBourne** [comment]
It's enough to make you miss templates ^^
You also need a size parameter

**Comment by EmilyBourne** [comment]
Can this issue be closed?

**Comment by yguclu** [comment]
@EmilyBourne Yes!
