### ISSUE TITLE
Help menu is extremely slow to load

### ISSUE THREAD

**Issue by EmilyBourne** [pyccel/pyccel#317]
The command `pyccel --help` takes almost 3 seconds to execute!

**Comment by yguclu** [comment]
That's because we are loading lots of modules before parsing the command line arguments. To speed this up it is sufficient to move the import statements in [pyccel.cmd.console](https://github.com/pyccel/pyccel/blob/master/pyccel/commands/console.py) inside the functions.

**Comment by EmilyBourne** [comment]
There are not that many modules loaded in pyccel.commands.console .  Just
- sys
- os
- argparse

argparse cannot be moved and moving sys and os seems to have little to no effect on the execution time

**Comment by yguclu** [comment]
Those libraries are indeed extremely fast to load. I was referring to Pyccel modules, we might be importing much more than we think. I will look into this.

**Comment by yguclu** [comment]
The problem is not in module [pyccel.commands.console](https://github.com/pyccel/pyccel/blob/master/pyccel/commands/console.py), but in the **installed script**, which imports the whole pyccel library before calling the `pyccel` function in `console.py`.
