### ISSUE TITLE
Accessing an element of an IndexedBase after the Semantic step does not return a pyccel object

### ISSUE THREAD

**Issue by EmilyBourne** [pyccel/pyccel#326]
This occurs in tests/codegen/cross.py and is one of the reasons we cannot do:
```
def _print_Integer:
     return "{0}_{1}".format(str(expr.p), expr.precision)
```

**Comment by EmilyBourne** [comment]
We should never be accessing `IndexedBase` as this is a sympy object. We should instead be using `IndexedVariable`

**Comment by yguclu** [comment]
What is the cause of the problem exactly? Somehow an `IndexedBase` object was not properly converted to `IndexedVariable`?

**Comment by EmilyBourne** [comment]
In `Cross`, `IndexedBase` is used instead of `IndexedVariable`. However I tried correcting it and reinstating:
```
def _print_Integer:
     return "{0}_{1}".format(str(expr.p), expr.precision)
```
but there still seems to b a problem somewhere preventing this from working
