### ISSUE TITLE
Order should be a member of PyccelAstNode

### ISSUE THREAD

**Issue by EmilyBourne** [pyccel/pyccel#335]
The `order` property is added to PyccelAstNode in PR #342, but it still need to be properly calculated in the following classes:

- [x] PythonTuple
- [ ] Len
- [x] Array (order is initialised but in Basic not the PyccelAstNode property)
- [ ] Rand
- [x] Full (order is initialised but in Basic not the PyccelAstNode property)
- [x] PyccelOperator ( and PyccelDiv )
- [x] PyccelBooleanOperator
- [x] PyccelAssociativeParenthesis
- [x] PyccelUnary
- [x] DottedVariable
- [x] FunctionCall
- [x] IndexedVariable
- [x] IndexedElement

This will require changes in different parts of the code, and we will also need to add more tests to make sure that everything works.

**Comment by yguclu** [comment]
The first step should be to raise an error when an expression contains objects with different `order`. Later on we will perform transpose operations where needed.
