### ISSUE TITLE
Can't iterate over a tuple

### ISSUE THREAD

**Issue by EmilyBourne** [pyccel/pyccel#339]
The following is ok:
```
a= (1,2,3)
for i in range(len(a)):
    print(a[i])
```

But the following doesn't work:
```
a = (1,2,3)
for ai in a:
    print(ai)
```

**Comment by yguclu** [comment]
Does this work for a `List`?

**Comment by EmilyBourne** [comment]
This seems to be my mistake. The problem must have been coming from a typo in my `__init__` function
