### ISSUE TITLE
Allocation with a random shape

### ISSUE THREAD

**Issue by saidctb** [pyccel/pyccel#363]
this example illustrate the bug.
```
def f(): 
    import numpy as np 
    a = np.zeros(np.random.randint(23)) 
    print(a) 
```

**Comment by EmilyBourne** [comment]
When testing this code I receive the following error:
```
ERROR at annotation (semantic) stage
pyccel: [semantic] 
 |fatal: [3,4]| Could not find randint in imported module np.random (np.random.randint)
```

Indeed, although rand and random are available `randint` does not seem to be implemented yet. The problem is therefore unrelated to the allocation

**Comment by saidctb** [comment]
> When testing this code I receive the following error:
> 
> ```
> ERROR at annotation (semantic) stage
> pyccel: [semantic] 
>  |fatal: [3,4]| Could not find randint in imported module np.random (np.random.randint)
> ```
> 
> Indeed, although rand and random are available `randint` does not seem to be implemented yet. The problem is therefore unrelated to the allocation

I didn't check if `randint` was there , but I know that the shape stored will be wrong because it will be a call to the `randint` function which will give a different number each time

**Comment by EmilyBourne** [comment]
I have added `randint`. The example that you provided works however if you try to use the shape of the object then you are right we do run into trouble.

From the following code:
```
def f():
    import numpy as np
    a = np.zeros(np.random.randint(23))
    b = np.shape(a)
    c = np.zeros_like(a)
```

The following fortran code is generated:
```
module test

implicit none




contains

!........................................
subroutine f()

  implicit none
  real(kind=8), allocatable  :: a (:)
  integer(kind=8)  :: b (0:1_8-1)
  real(kind=8), allocatable  :: c (:)
  real(kind=8)  :: Dummy_4258
  real(kind=8)  :: Dummy_4338
  real(kind=8)  :: Dummy_4273


  call random_number(Dummy_4258)

  allocate(a(0:floor(23_8 * Dummy_4258, kind=8) - 1_8))
  a = 0.0
  call random_number(Dummy_4338)

  b = [floor(23_8 * Dummy_4338, kind=8)]
  call random_number(Dummy_4273)

  allocate(c(0:floor(23_8 * Dummy_4273, kind=8) - 1_8))
  c = 0.0
end subroutine
!........................................

end module
```

The random expression is therefore reused. When the shape of an array is not an integer we should use NumpyArrayShape to avoid calling functions multiple times

**Comment by EmilyBourne** [comment]
This problem also appears when allocating the shape with a variable.

e.g: the following python code
```
import numpy as np

n = 5

a = np.ones(n)

n = 10

b = np.ones_like(a)
```

is translated to the following fortran code:
```
program prog_test2

implicit none

integer(kind=8)  :: n
real(kind=8), allocatable  :: a (:)
real(kind=8), allocatable  :: b (:)

n = 5_8
allocate(a(0:n - 1_8))
a = 1.0
n = 10_8
allocate(b(0:n - 1_8))
b = 1.0

end program prog_test2
```
```
