### ISSUE TITLE
add the math functions  that exist in numpy and math libraries of Python for c language

### ISSUE THREAD

**Issue by rakati** [pyccel/pyccel#381]
some of the math functions don't work like sqrt
```
from pyccel.decorators import types
@types('real')
def sqrt_call(x):
        from math import sqrt
        return sqrt(x)
```
converting python sqrt_call function above with the command
``>> pyccel test_sqrt.py --language c``
lead to the error :
RuntimeError: Failed to build module
ERROR at shared library generation stage
implicit declaration of function ‘MathSqrt’

and it generates this code
```
double sqrt_call(double x) {
    double Dummy_9193;

    Dummy_9193 = MathSqrt(x);
    return Dummy_9193;
```

**Comment by EmilyBourne** [comment]
Almost all of the math module is already available. The only functions in the math module not currently available should be:
```
frexp
modf
```
Are these the functions you would like adding or are you having trouble with one of the other functions?

**Comment by EmilyBourne** [comment]
The functions currently available from the numpy package are the following:
```
full
empty
zeros
ones
full_like
empty_like
zeros_like
ones_like
array
shape
norm
int
real
imag
float
double
mod
float32
float64
int32
int64
complex
complex128
complex64
matmul
sum
prod
product
linspace
diag
where
abs
floor
absolute
fabs
exp
log
sqrt
sin
cos
tan
arcsin
arccos
arctan
arctan2
sinh
cosh
tanh
arcsinh
arccosh
arctanh
linalg.norm
random.rand
random.random
random.randint
```
which additional functions would you like to be added?

**Comment by rakati** [comment]
Hi @EmilyBourne I forgot to mention that this related to c language, not Fortran which handled these cases well. I updated the issue and I will add more examples and descriptions of the issue.

**Comment by EmilyBourne** [comment]
What is the status of this issue?

**Comment by saniQQ** [comment]
for the scalars funcs i am doing a pull request now , we will need to modify the numpy funcs after we implemet the arrays.
