### ISSUE TITLE
Complex numbers in C 

### ISSUE THREAD

**Issue by MenoIy** [pyccel/pyccel#386]
**Some data types don't work as argument ex {complex complex64 complex128} exemple :**

```
@types('complex')
def func(x):
    return x
```

```
ERROR at code generation stage
**pyccel**: [codegen]
    |fatal| Pyccel has encountered syntax that has not been implemented yet
```

**Comment by EmilyBourne** [comment]
Hello,

It looks like you are reporting 2 issues here:

1. Not all datatypes are supported as arguments in C
2. Casting (to both native datatypes and numpy datatypes) does not work in C

In order to avoid confusion in any necessary discussion about each problem it is better to write separate issues for separate problems. This also allows the issues to be closed separately if they are not solved in the same pull request.
The fact that `float` is a valid argument but cannot be used for casting shows that solving one problem does not necessarily fix the other

**Comment by MenoIy** [comment]
For the issue: **Not all datatypes are supported as arguments in C** I don't know if it's a good idea to use the  Py_complex  from <Python.h> to read arguments type complex  exemple :  

a python code like  : 
```
from pyccel.decorators import types
@types('complex')
def func(y):
     return y
```

will be something like this
```
#include <complex.h>
Py_complex Cfunc(Py_complex x)
{
        return(x);
}
static PyObject* func(PyObject* self, PyObject* args)
{
        Py_complex n;
        if (!PyArg_ParseTuple(args, "D", &n))
                return  NULL;
        Py_complex test = Cfunc(n);
        PyObject* result = Py_BuildValue("D", &test);
        return result;
}
```
but to work with this we need to include <Python.h> in both  c file and add some condition to **pyccel/codegen/cwrapper.py**   to print  **'&'**  when we are working with py_complex type in    **Py_BuildValue().**

**Comment by EmilyBourne** [comment]
This special case of complex numbers needs discussing. Please split this issue into 3 by creating the following 2 new issues:
1. Some data types don't work as arguments in C ex (int8 int16 bool)
2. Casting does not work in C

This issue can then be used to discuss "Complex numbers in C"

You can edit your original message and copy and paste the relevant part of the description into the new issues. Don't forget to add the `Language:C` label

**Comment by EmilyBourne** [comment]
> to work with this we need to include <Python.h> in both c file and add some condition to pyccel/codegen/cwrapper.py to print '&' when we are working with py_complex type in Py_BuildValue().

I think we should avoid using Python types in the pure C code. Code generated using `pyccel` should be able to run on a system where Python is not installed.
As a result Python types should only exist in the cwrapper file (used by `epyccel`).

However, as the function `PyArg_ParseTuple` only allows us to collect a `Py_complex` object this will mean that we have to copy the data. I don't think that this is an issue as a complex number is just 2 floats so the copy should not be too costly.

Do you agree with this method @saidctb @yguclu @ratnania ?

If so then we will need to add the copy mechanism to the file that generates the cwrapper

**Comment by yguclu** [comment]
I think it's time to specify which C standard we want to use. If we use ISO C99 we're in luck: https://www.gnu.org/software/libc/manual/html_node/Complex-Numbers.html.

**Comment by yguclu** [comment]
I also agree that our C translation of the user Python code should be printed to a separate `.c` file which does not include `Python.h`. Instead we should only include `complex.h`, which was present in @MenoIy's example but not used.

I do not worry about copying a few floats around, that's the price to pay for calling C from Python anyway.

As mentioned above, for this to work we must use ISO C99 or later.

**Comment by saidctb** [comment]
> > to work with this we need to include <Python.h> in both c file and add some condition to pyccel/codegen/cwrapper.py to print '&' when we are working with py_complex type in Py_BuildValue().
> 
> I think we should avoid using Python types in the pure C code. Code generated using `pyccel` should be able to run on a system where Python is not installed.
> As a result Python types should only exist in the cwrapper file (used by `epyccel`).
> 
> However, as the function `PyArg_ParseTuple` only allows us to collect a `Py_complex` object this will mean that we have to copy the data. I don't think that this is an issue as a complex number is just 2 floats so the copy should not be too costly.
> 
> Do you agree with this method @saidctb @yguclu @ratnania ?
> 
> If so then we will need to add the copy mechanism to the file that generates the cwrapper

yes I agree we should always translate the Python types to pure c types in the c_wrapper and then give it to the pure c function which does not depend on Python
