### ISSUE TITLE
Some data types don't work as arguments in C ex (int8 int16 bool)

### ISSUE THREAD

**Issue by EmilyBourne** [pyccel/pyccel#390]
**Some data types don't work as argument ex {int8 int16 bool complex complex64 complex128}**

The following code:
```
@types('bool')
def func(x):
    return x
```

generates this error when translating to C:
```
KeyError: ('bool', 4)
```

cc: @MenoIy

**Comment by EmilyBourne** [comment]
Continuing the discussion begun in issue #388 here as it pertains to fixing this issue
> When inspecting the 'bool' variable passed as argument :
> 
> ```
> from pyccel.decorators import types
> 
> @types(bool)
> def func(x):
>     return x
> ```
> 
> ```
> >>> code.routines[0].arguments[0].inspect()
> >>> Variable
>   name           = x
>   dtype          = bool
>   rank           = 0
>   allocatable    = False
>   shape          = ()
>   cls_base       = None
>   cls_parameters = None
>   is_pointer     = False
>   is_target      = False
>   is_polymorphic = False
>   is_optional    = False
> ```
> 
> and
> 
> ```
> >>>code.routines[0].arguments[0].precision
> 4
> ```
> 
> The variable type is bool and the precision is **4**. but in dictionary **dtype_registry** **in pyccel/codegen/printing/ccode.py**
> **{('bool', 1) : int}** the precision set for a boolean type is **1** . When the precision is set to 4 the code work fine but
> when working with Py_BuildValue we can't product a boolean type python object exemple :
> 
> ```
> x = False
> y = func(x)
> print(y , type(y))
> print(type(x))
> 
> >>> 0 <class 'int'>
> >>> <class 'bool'>
> ```

The precision of booleans was changed in PR #242. Probably we forgot to change the boolean type to match at that point which is why we have problems here.

> when working with Py_BuildValue we can't product a boolean type python object
You are right! I had not realised this. This explains why we have problems with booleans with f2py (see issue #370). However it seems that we can use Py_BuildValue to create `True` or `False` as explained here: https://stackoverflow.com/questions/21221242/py-buildvalue-make-tuple-with-bool

**Comment by MenoIy** [comment]
Yes, as you mentioned both methods will work
```
  Py_BuildValue("O",  test ? Py_True: Py_False);
```
and
```
  Py_BuildValue("N",  PyBool_FromLong(test) );
```

Updating the way the code of the function **Py_BuildValue ()**  is printed in the file **pyccel/codegen/cwrapper. py** should solve the problem for boolean types.

**Comment by EmilyBourne** [comment]
The files `test_base.py` and `test_compare_expressions.py` can be activated for C tests in order to test bools as arguments and as return types
