### ISSUE TITLE
Can't translate a function with no return type to C

### ISSUE THREAD

**Issue by EmilyBourne** [pyccel/pyccel#395]
**Describe the bug**
The handling of functions if the wrapper assumes that a function returns something. As a result, we can't translate a function which does not return anything into c

**To Reproduce**
Provide code to reproduce the behavior:
```python
@types('int')
def g(x):
    x += 1
```

The following code is generated in the wrapper:
```c
static PyObject * g_wrapper(PyObject *self, PyObject *args)
{
    long x;

    if (!PyArg_ParseTuple(args, "l", &x))
        return NULL;
    g(x)
    return Py_BuildValue("", );
}
```
which leads to an error. This error is masked by the error output generated by issue #397. When issue #397 is fixed manually and the compile command is run the error is:
```
__pyccel__/test2_wrapper.c: In function ‘g_wrapper’:
__pyccel__/test2_wrapper.c:13:30: error: expected expression before ‘)’ token
     return Py_BuildValue("", );
                              ^
__pyccel__/test2_wrapper.c:14:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
```

**Expected behavior**
Functions without a return statement in python return `None`. This value is created with the expression `Py_BuildValue("")`, it is therefore simply a case of removing the extra comma

**Language**
C

**Comment by rakati** [comment]
in which branch you found this bug?

**Comment by EmilyBourne** [comment]
In the master branch

**Comment by yguclu** [comment]
What is the difference between this issue and #394?

**Comment by EmilyBourne** [comment]
#394 Is no arguments. #395 is no return type

#394:
```
def f():
    return 1
```

#395:
```
@types('int')
def g(x):
    x += 1
```

**Comment by yguclu** [comment]
I see! Sorry
