### ISSUE TITLE
Number or variable preceded by a negative sign not properly convert to c

### ISSUE THREAD

**Issue by rakati** [pyccel/pyccel#399]
**Describe the bug**
Any operand number or variable preceded by negative sign alone or at the first position in an operation 
does not preserve its negative sign after converting to c.

**To Reproduce**
Provide code to reproduce the behavior:
```python
from pyccel.decorators import types

@types(int)
def f(x):
        x = -1
        return x
```

Provide the generated code, or the error message:
```c
long f(long x) {
    long Dummy_4171;
    x = (1);
    Dummy_4171 = x;
    return Dummy_4171;
}
```

**Expected behavior**
the operand 

**Language**
C

**other example**
`return -val` 
`x = -1 + x`

**Comment by EmilyBourne** [comment]
Is this a C problem or a general problem?

**Comment by rakati** [comment]
it's only c problem.
