### ISSUE TITLE
Variable name collisions not always handled causing travis problems

### ISSUE THREAD

**Issue by EmilyBourne** [pyccel/pyccel#403]
**Describe the bug**
Variables created in `codegen/printing/fcode.py` (usually output variables) are not checked for name collisions. As the random string has only 9999 different possibilities this occasionally results in 2 objects having the same name. As a result the function returns one item less than it should. This is why our tests on travis fail occasionally. See PR #401 

**To Reproduce**
Provide code to reproduce the behavior:

The behaviour can be reproduced by decreasing the randomness of the name generator. I.e by changing the function `create_random_string` in `ast/core.py` from:
```python
def create_random_string(expr):
    import numpy as np
    try:
        randstr = str(abs(hash(expr)
                                  + np.random.randint(500)))[-4:]
    except TypeError:
        # Catch unhashable type (e.g. list, FunctionalSum)
        randstr = str(abs(np.random.randint(10000)))[-4:]
    return randstr
```
to:
```
def create_random_string(expr):
    import numpy as np
    return str(np.random.randint(10))
```

For example the following code:
```python
def functional_for_1d_range():
    a = [i for i in range(4)]
    return len(a), a[0], a[1], a[2], a[3]
```
is then translated to:
```fortran
module test

implicit none

contains

!........................................
subroutine functional_for_1d_range(Dummy_5, Dummy_9, Dummy_0)

  implicit none

  integer(kind=8), intent(out) :: Dummy_5
  integer(kind=8), intent(out) :: Dummy_9
  integer(kind=8), intent(out) :: Dummy_0
  integer(kind=8) :: i
  integer(kind=8), allocatable :: a(:)
  integer(kind=8) :: Dummy_3

  allocate(a(0:4_8 - 1_8))
  Dummy_3 = 0_8
  do i = 0_8, 4_8-1_8, 1_8
    a(Dummy_3) = i
    Dummy_3 = Dummy_3 + 1_8

  end do
  Dummy_5 = size(a,1)
  Dummy_5 = a(0_8)
  Dummy_9 = a(1_8)
  Dummy_9 = a(2_8)
  Dummy_0 = a(3_8)
  return

end subroutine functional_for_1d_range
!........................................

end module test
```

**Expected behavior**
We should modify the function `create_random_string` so it takes a list of forbidden values

**Language**
Fortran
The generated names are checked in parser/semantic.py however the process is not always done very neatly and could be tidied up while fixing this

**Additional context**
`parser/semantic.py` has the following 2 functions to deal with this problem:
```
    def _get_new_name(self, current_name):
        if current_name not in self._possible_names:
            self._possible_names.add(current_name)
            return current_name
        current_name = current_name + '_' + create_random_string(current_name)
        while current_name in self._possible_names:
            # Generate random name based on the original name
            current_name = current_name + create_random_string(current_name)
        self._possible_names.add(current_name)
        return current_name

    def _get_new_variable(self, obj):
        var = create_variable(obj)
        name = var.name
        while name in self._possible_names:
            var = create_variable(obj)
            name = var.name
        self._possible_names.add(name)
        return var
```
It should not be necessary to have the while loop in multiple locations. In addition `_get_new_variable` is often used when `_get_new_name` should be used

**Comment by yguclu** [comment]
Should we make the name generation purely deterministic then? And maybe use incremental numbers?

**Comment by EmilyBourne** [comment]
Incremental numbers of a fixed width? (This will help differentiate from tuple elements). That could be a good option although it will require an additional variable (for the counter) to be stored somewhere between the 2 parsers and codegen.

We should test the generated name to ensure it isn't causing a collision in any case. Whether the name is deterministic or not

**Comment by EmilyBourne** [comment]
Do we mind if the incremental numbers aren't printed in order?
They will be printed in the order they are generated which means that they will be in order, but the arguments will be printed before the normal variables and generated last (as this is language specific)
Eg:
```
module test

implicit none

contains

!........................................
subroutine functional_for_1d_range(Dummy_0002, Dummy_0003, Dummy_0004, &
      Dummy_0005, Dummy_0006)

  implicit none

  integer(kind=8), intent(out) :: Dummy_0002
  integer(kind=8), intent(out) :: Dummy_0003
  integer(kind=8), intent(out) :: Dummy_0004
  integer(kind=8), intent(out) :: Dummy_0005
  integer(kind=8), intent(out) :: Dummy_0006
  integer(kind=8) :: i
  integer(kind=8), allocatable :: a(:)
  integer(kind=8) :: Dummy_0001

  allocate(a(0:4_8 - 1_8))
  Dummy_0001 = 0_8
  do i = 0_8, 4_8-1_8, 1_8
    a(Dummy_0001) = i
    Dummy_0001 = Dummy_0001 + 1_8

  end do
  Dummy_0002 = size(a,1)
  Dummy_0003 = a(0_8)
  Dummy_0004 = a(1_8)
  Dummy_0005 = a(2_8)
  Dummy_0006 = a(3_8)
  return

end subroutine functional_for_1d_range
!........................................

end module test
```

**Comment by EmilyBourne** [comment]
I have decided to use a different prefix for these output arguments. Thus the generated code is now:
```
module test

implicit none

contains

!........................................
subroutine functional_for_1d_range(Out_0001, Out_0002, Out_0003, &
      Out_0004, Out_0005)

  implicit none

  integer(kind=8), intent(out) :: Out_0001
  integer(kind=8), intent(out) :: Out_0002
  integer(kind=8), intent(out) :: Out_0003
  integer(kind=8), intent(out) :: Out_0004
  integer(kind=8), intent(out) :: Out_0005
  integer(kind=8) :: i
  integer(kind=8), allocatable :: a(:)
  integer(kind=8) :: Dummy_0001

  allocate(a(0:4_8 - 1_8))
  Dummy_0001 = 0_8
  do i = 0_8, 4_8-1_8, 1_8
    a(Dummy_0001) = i
    Dummy_0001 = Dummy_0001 + 1_8

  end do
  Out_0001 = size(a,1)
  Out_0002 = a(0_8)
  Out_0003 = a(1_8)
  Out_0004 = a(2_8)
  Out_0005 = a(3_8)
  return

end subroutine functional_for_1d_range
!........................................

end module test
```

**Comment by yguclu** [comment]
That's nice! It makes a lot of sense to differentiate between output arguments and other temporary variables! Would you do the same for a function result?

**Comment by yguclu** [comment]
By the way, why is there an empty line before the `end do` statement in your examples? Did I miss that in PR #391?

**Comment by EmilyBourne** [comment]
Yes it appears to have been missed. I will add the fix to the PR

**Comment by EmilyBourne** [comment]
> That's nice! It makes a lot of sense to differentiate between output arguments and other temporary variables! Would you do the same for a function result?

I can do. Can you give me an example?

Do you mean something like :
```
def f():
    return 1, 2
print(f())
```
which currently produces:
```
program prog_prog_test

use test, only: f

implicit none

integer(kind=8) :: Dummy_0001
integer(kind=8) :: Dummy_0002

call f(Out_0001 = Dummy_0001, Out_0002 = Dummy_0002)

print *, [Dummy_0001, Dummy_0002]

end program prog_prog_test
```

I can give the output variable whatever name seems best. E.g: `f_out_0001`

**Comment by yguclu** [comment]
Sorry, I was not clear in my comment. I meant a function with a single return value, which is translated to a Fortran function, in the case where the result requires a dummy variable. Do you handle it as in the subroutine case, by creating an `Out_1` variable?
