### ISSUE TITLE
(is and is not) not working in c and fortran

### ISSUE THREAD

**Issue by MenoIy** [pyccel/pyccel#409]
**Just found another issue in C and fortran  (is and is not )**
**in C** 
```
@types('bool')
def is_t(x):
    if x is True:
        return 1
    return 0
```

ERROR at code generation stage
pyccel: [codegen]
 |fatal| Pyccel has encountered syntax that has not been implemented yet. Please create an issue at https://github.com/pyccel/pyccel/issues and provide a small example of your problem. Do not forget to specify your target language (Is(x, True))

**and in Fortran when we compare to something different than bool or None**

```
@types('int')
def test(x):
    return x is 5
```

ERROR at code generation stage
pyccel: [codegen]
 |fatal| Only booleans and None are allowed as rhs for is statement (Is(x, 5))

**Comment by nhamidn** [comment]
i get a Semantic Error when trying to compare to None

for example : 

```
def f():
    strA = "hello world"
    return strA is None
```

this code gave me this error 

```
ERROR at annotation (semantic) stage
pyccel: [semantic] 
 |error: [6,4]| Variables cannot be equal to None unless they are optional arguments and None is the default value
```

**Comment by nhamidn** [comment]
i get the same error that @MenoIy get but at annotation (semantic) stage and when comparing the identity of two strings
For example this python code : 

```
def f():
    strA = "hello world"
    strB = strA
    return strA is strB
```
gave this error : 

```
ERROR at annotation (semantic) stage
pyccel: [semantic] 
 |error: [7,4]| Only booleans and None are allowed as rhs for is statement
```
