### ISSUE TITLE
Add brackets when mixing `and` and `or` operations for stylistic reasons

### ISSUE THREAD

**Issue by nhamidn** [pyccel/pyccel#410]
for this python code : 
```
if (x >= 0 and x <= 5) or x == 10:
        x = x + 1
```

the translated code was like this : 

```
if (x >= 0 && x <= 5 || x == 10)
    {
        x = x + 1;
    }
```

even if there is no brackets this code is working well, but it raises a warning when compiling the generated code in C, so we must add brackets when there are mixed Or and And.

----------------------------------------------------------

> It is working as intended for both. The intention is to add brackets when they are necessary in python.
> As I said above, we have 3 cases here:
> 1. `(x >= 0 and x <= 5) or x == 10`
> 2. `x >= 0 and (x <= 5 or x == 10)`
> 3. `x >= 0 and x <= 5 or x == 10`
> 
> Case 2 and 3 will give the same results in python as `and` operations  are always carried out before `or` operations when there are no brackets.
> The parsing step does not read the brackets (and we can't make it read them) so we add them back in where they are necessary. In case 2 they are not necessary. While in case 1 they are.
> 
> That said option 2 is a lot easier to understand than option 3. This is why C raises a warning when you don't use brackets. As a result it may be a good idea to always use brackets when mixing `and` and `or` operations for stylistic reasons. But this should be discussed in an issue. The only people who see messages in pull requests are people that participated in the Pull Request and it would be good to have other opinions too. Please copy this conversation into an issue

_Originally posted by @EmilyBourne in
https://github.com/pyccel/pyccel/pull/396#issuecomment-681101777_

**Comment by EmilyBourne** [comment]
Similarly the following code:
```
@types('bool', 'int')
def compare_is_int(a, b):
    c = False
    if a is bool(b):
        c = True
    return c
```
generates
```
if (a == b != 0)
```
Which also raises the warning:
```
 warning: suggest parentheses around comparison in operand of ‘!=’
```

**Comment by EmilyBourne** [comment]
> generates
> 
> ```
> if (a == b != 0)
> ```
> 
> Which also raises the warning:
> 
> ```
>  warning: suggest parentheses around comparison in operand of ‘!=’
> ```
> 
> Although this may just be due to missing parentheses in the `int` cast

An elegant way of fixing this would be to add a `precedence` property to the `Bool` class in `pyccel/ast/builtins.py`:
```
    @property
    def precedence(self):
        if isinstance(self.arg.dtype, NativeBool):
            return 17
        else:
            return 7
```

This will fix the problem above without adding additional unnecessary parentheses in examples such as:
`if bool(var):`
