### ISSUE TITLE
C modules should generate a .h file

### ISSUE THREAD

**Issue by EmilyBourne** [pyccel/pyccel#431]
**Describe the bug**
The translation of a module to C leads to the generation of a .c file containing the function definitions. It is bad practice to include this file in other files. Instead we should include a .h file containing the function signatures. Currently this .h file is not generated

**Language**
C

**Comment by yguclu** [comment]
The generated header files should contain an **include guard**: https://en.wikipedia.org/wiki/Include_guard.
