### ISSUE TITLE
Warnings are being raised multiple times for C language

### ISSUE THREAD

**Issue by nhamidn** [pyccel/pyccel#442]
while i'm working on issue #421 i found that warnings in C language are being raised 2 times.
for example this python code: 

```
from pyccel.decorators import types
import numpy
import numpy

@types('int,int')
def func(a,b):
    return a + b
```
generate multiple warnings : 

```
pyccel: [codegen] 
 |warning| Duplicated import  (numpy)

pyccel: [codegen] 
 |warning| Duplicated import  (numpy) 
```
this is because that `errors.check()` is called in both `python_wrapper.py` and  `pipeline.py`

the solution is tot call `errors.check()` in `python_wrapper.py` and let `pipeline.py` manage it

**Comment by EmilyBourne** [comment]
Is this warning generated in the codegen step or just reported then?

**Comment by nhamidn** [comment]
> Is this warning generated in the codegen step or just reported then?
yes it is generated in the codegen step

**Comment by EmilyBourne** [comment]
> > Is this warning generated in the codegen step or just reported then?
>
> yes it is generated in the codegen step

I wonder how many times a warning created in the syntactic stage is reported. It looks like we are not clearing the errors list once they have been reported. Could you run a short test to check?

**Comment by EmilyBourne** [comment]
I think we need to call `errors.reset()` after `errors.check()` to clear the errors that have already been reported

**Comment by EmilyBourne** [comment]
I think we need to call `errors.reset()` after `errors.check()` to clear the errors that have already been reported[]()

**Comment by nhamidn** [comment]
yes i agree it worked when i called `errors.reset()` after `errors.check()` in `pipeline.py`

**Comment by EmilyBourne** [comment]
I noticed that we don't have a call to `errors.set_target(filename, 'file')` in the codegen stage. That might cause problems once `reset` has been called

**Comment by nhamidn** [comment]
what kind of problems ? and what does `set_target` do ?

**Comment by EmilyBourne** [comment]
`set_target` tells errors information about the context, eg which file it is in. One of the branches (maybe the master now) prints the name of the file without checking that `filename is not None`. After reset if `set_target` has not been called to set the filename then this is no longer true

**Comment by nhamidn** [comment]
i tried to convert this python code with an invalid syntax :  

```
from pyccel.decorators import types

@types('int', results=int, results=int)
def func(n):
    return z
```

and i got this error : 

```
Traceback (most recent call last):
  File ".../pyccel/bin/pyccel", line 11, in <module>
    load_entry_point('pyccel', 'console_scripts', 'pyccel')()
  File ".../pyccel/commands/console.py", line 235, in pyccel
    execute_pyccel(filename,
  File ".../pyccel/codegen/pipeline.py", line 123, in execute_pyccel
    parser.parse(verbose=verbose)
  File ".../pyccel/parser/parser.py", line 87, in parse
    parser = SyntaxParser(self._filename, **self._kwargs)
  File ".../pyccel/parser/syntactic.py", line 117, in __init__
    tree = extend_tree(code)
  File ".../pyccel/parser/extend_tree.py", line 78, in extend_tree
    errors.report(INVALID_PYTHON_SYNTAX, symbol='\n' + str(e),
  File ".../pyccel/errors/errors.py", line 241, in report
    info = ErrorInfo(filename,
  File ".../pyccel/errors/errors.py", line 75, in __init__
    self.filename = basename(filename)
  File "/usr/local/bin/../Cellar/python@3.8/3.8.4/bin/../Frameworks/Python.framework/Versions/3.8/lib/python3.8/posixpath.py", line 142, in basename
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```
the `NVALID_PYTHON_SYNTAX` error is not raised because the `filename is None`

is this problem related to the missing `set_target` call

**Comment by EmilyBourne** [comment]
Yes exactly. If you look at the error message the last pyccel file in the backtrack is:
```
pyccel/errors/errors.py", line 75, in __init__
    self.filename = basename(filename)
```
We call the function `basename`. `basename` is a function for handling file names. It turns this: `pyccel/errors/errors.py` into `errors.py`
If we pass it a `None` then it throws an error. This means that we are passing `None` to the class. You can see this in the line above:
```
File ".../pyccel/errors/errors.py", line 241, in report
    info = ErrorInfo(filename,
```
If you look at this function you can see that we will pass `None` as the filename unless `set_target` has been called.

In the `SyntacticParser` `set_target` is called in the function `parse`. The backtrace above shows that the error is thrown in the `__init__` function which is called before `parse`. The call to `set_target` should therefore be moved to the `__init__` function

**Comment by EmilyBourne** [comment]
We should probably also handle the case where `filename` is `None` just in case we somehow find ourselves in a case where we don't know the filename.

If you want to know why I thought it was important that the filename be included in the error message try to translate the file `tests/codegen/fcode/scripts/imports.py` to c

**Comment by EmilyBourne** [comment]
@nhamidn, you have assigned this to yourself. Are you working on it? If not then I can fix this in PR 448 as I have already made changes to the use of `errors` there anyway

**Comment by nhamidn** [comment]
> @nhamidn, you have assigned this to yourself. Are you working on it? If not then I can fix this in PR 448 as I have already made changes to the use of `errors` there anyway

@EmilyBourne i didn't complete the fix and i stopped, you can fix it.
