### ISSUE TITLE
Basic syntax

### ISSUE THREAD

**Issue by yguclu** [pyccel/pyccel#466]

**Comment by EmilyBourne** [comment]
@yguclu Do you remember what this epic refers to?

**Comment by yguclu** [comment]
It referred to the ability of Pyccel to understand the syntax of the Python language and its built-in classes.

**Comment by EmilyBourne** [comment]
Ok. In that case it sounds like an epic that can never be closed given that Python regularly adds new syntax. Do you still think it's useful to have this?

**Comment by yguclu** [comment]
Not really. We can just use a "basic syntax" label for our issues.
