### ISSUE TITLE
epyccel ignores comments (and hence pragmas) at end of function

### ISSUE THREAD

**Issue by nhamidn** [pyccel/pyccel#468]
**Describe the bug**
A wrong generated code is the result of converting a python function that contain openMP pragmas at the last line of the function

**To Reproduce**
For example this python code using openMP pragmas:
```
from pyccel.decorators import types

@types('real[:,:], real[:,:], real[:,:]')
def omp_matmul_single(A, x, out):
  from numpy import matmul
  #$ omp parallel
  #$ omp single
  out[:] = matmul(A, x)
  #$ omp end single
  #$ omp end parallel
```

using epyccel : 

```
from pyccel.epyccel import epyccel
import openmp as omp
mod = epyccel(omp.omp_matmul_single, accelerator='openmp')
```

the generated code is :
```
@types('real[:,:], real[:,:], real[:,:]')
def omp_matmul_single(A, x, out):
  from numpy import matmul
  #$ omp parallel
  #$ omp single
  out[:] = matmul(A, x)

```

The gererated code does not contain the end pragmas, the last 2 lines of the function are being ignored.

**Comment by saidctb** [comment]
the bug is in the `inspect`  library it gives this result
```
>>> inspect.getsource(omp_matmul_single)                                                                                                                                     
>>> "@types('real[:,:], real[:,:], real[:,:]')\ndef omp_matmul_single(A, x, out):\n  from numpy import matmul\n  #$ omp parallel\n  #$ omp single\n  out[:] = matmul(A, x)\n"
```

**Comment by nhamidn** [comment]
> the bug is in the `inspect` library it gives this result
> 
> ```
> >>> inspect.getsource(omp_matmul_single)                                                                                                                                     
> >>> "@types('real[:,:], real[:,:], real[:,:]')\ndef omp_matmul_single(A, x, out):\n  from numpy import matmul\n  #$ omp parallel\n  #$ omp single\n  out[:] = matmul(A, x)\n"
> ```

that mean we cant fix this issue

**Comment by yguclu** [comment]
I recommend creating an issue (and maybe even a pull request) on the C Python inspect module: https://github.com/python/cpython/blob/master/Lib/inspect.py

**Comment by yguclu** [comment]
@nhamidn Can you please add a link to the issue you have created in CPython?

**Comment by nhamidn** [comment]
> @nhamidn Can you please add a link to the issue you have created in CPython?

i opened an the issue on the python website
https://bugs.python.org/issue42116

**Comment by nhamidn** [comment]
There is an update from Python, they opened a PR for this issue: https://github.com/python/cpython/pull/23630

**Comment by EmilyBourne** [comment]
This seems to be fixed in python 3.9.1:
https://docs.python.org/3/whatsnew/changelog.html#python-3-9-1-final
and python 3.8:
https://docs.python.org/3.8/whatsnew/changelog.html#python-3-8-7-release-candidate-1

**Comment by EmilyBourne** [comment]
Can this issue be closed?

**Comment by nhamidn** [comment]
yes it can be closed

**Comment by yguclu** [comment]
It's fixed with [bpo-42116](https://github.com/python/cpython/pull/23630), see [changelog](https://docs.python.org/3/whatsnew/changelog.html#id3):

>bpo-42116: Fix handling of trailing comments by inspect.getsource().
