### ISSUE TITLE
Use iso_c types for fortran to ensure compatibility for the cwrapper

### ISSUE THREAD

**Issue by EmilyBourne** [pyccel/pyccel#487]
**Description**
As a USER I want the fortran code to be easily compatible with other languages.

**Acceptance Criteria**
- [x] Use `iso_c_binding` to specify precision
- [x] Mark all structures and functions in the f2py_X.F90 file with `bind (c)`

******

In order to use the Python C API to create a fortran extension, we need to be sure that the types match as expected. For this to work we should use iso_c_binding to specify the precision.

Thus
```
integer(kind=4)
```
becomes
```
integer(c_int)
```
etc

See https://stackoverflow.com/tags/fortran-iso-c-binding/info for an overview of `ISO_C_BINDING`
Point 2 provides a list of the constants and their equivalent c types

We also need to add the bind(c) statement to the function definitions in the f2py_X.F90 file

**Comment by saidctb** [comment]
if I'm not wrong we only need the change the precision from `kind=4` to `c_int` for example ? and the `integer` always stays the same

**Comment by EmilyBourne** [comment]
Yes exactly. It is just the precision specification that changes. As long as the precision is specified in the declaration and the casting functions and we don't have any precisions specified manually anywhere it should be a really easy fix

**Comment by EmilyBourne** [comment]
We equally need to add the `bind(c)` statement to the function definitions in the `f2py_X.F90` file

**Comment by yguclu** [comment]
What about literal constants? We are currently printing
```
a = 10_8
```
which assumes that `a` is declared as
```
integer(kind=8) :: a
```

**Comment by EmilyBourne** [comment]
> What about literal constants? We are currently printing
> ```
> a = 10_8
> ```
> which assumes that `a` is declared as
> ```
> integer(kind=8) :: a
> ```

I'm not sure. It is possible to do
```
a = 10_C_LONG
```
But it seems a bit verbose. Do you have a better idea or do you think this is the right answer?

**Comment by yguclu** [comment]
If we want to make the code more readable, we should probably define our own shortcuts:
```fortran
integer, parameter :: i32 = C_INT
integer, parameter :: i64 = C_LONG
integer, parameter :: f32 = C_FLOAT
integer, parameter :: f64 = C_DOUBLE
```
But we must make sure that the names of these constants are not taken by some user-defined variables.
