### ISSUE TITLE
pyccel/ast/core.py is larger than codacy's maximum file size

### ISSUE THREAD

**Issue by EmilyBourne** [pyccel/pyccel#490]
pyccel/ast/core.py is larger than codacy's maximum file size (150KB as specified here https://docs.codacy.com/faq/troubleshooting/why-is-my-file-missing/#file-size-limitation-on-codacy-cloud). It is currently 152kB.

We should either find a way to break it into pieces. Eg. we could create an arithmetic.py file for all basic arithmetic types

Or we should use the Codacy Analysis CLI locally

**Comment by yguclu** [comment]
If we spend a little time on it, I'm sure we can shrink it down to something more manageable :smile:

**Comment by EmilyBourne** [comment]
PR #559 will help with this issue.

I would like to suggest the creation of an `ast.variables` file which would contain `Variable` (and all classes that inherit from it), `DottedVariable`, `FunctionAddress` and `IndexedElement`. We may also want to include `Constant`, `Argument`, and `ValuedArgument` and also related helper classes e.g. `Declare`, `FunctionAddressDeclare`, `VariableAddress`
I think this change should be sufficient to fix several of our circular import problems as it should allow us to move the definition of `PyccelArraySize` although where it should be moved to is not clear

We should also go through and remove unused classes, e.g. `Concatenate`? `Del`?

**Comment by yguclu** [comment]
> I would like to suggest the creation of an `ast.variables` file which would contain `Variable` (and all classes that inherit from it), `DottedVariable`, `FunctionAddress` and `IndexedElement`. We may also want to include `Constant`, `Argument`, and `ValuedArgument` and also related helper classes e.g. `Declare`, `FunctionAddressDeclare`, `VariableAddress`

I agree, your suggestion looks really good to me. Although usually splitting a module increases the chances of a circular import to happen, rather than the opposite...
