### ISSUE TITLE
Speed up builds on Travis-CI

### ISSUE THREAD

**Issue by yguclu** [pyccel/pyccel#496]
As a DEVELOPER, I would like the unit tests to run as quickly as possible on Travis-CI.

We currently have 6 different builds for our tests, but Travis-CI only allows for 5 concurrent jobs. As a consequence one build is always lagging behind the others, and this slows the process greatly.

To resolve this problem, I suggest that we drop the build for Python 3.5.

**Comment by yguclu** [comment]
@saidctb @EmilyBourne What do you think?

**Comment by EmilyBourne** [comment]
Given that python3.5 has reached it's end of life I agree. I think we could even go further. I have never seen the different linux tests give different results. I suspect we could run 1 test with the most recent version of python to test things that don't exist in previous versions and 1 test with an older version of python (3.5 or 3.6) to ensure backwards compatibility. I don't know if we gain anything by testing all the intermediate python versions.

We could have more complex builds for the master branch which run all versions of python and a slimmed down version with only 1 or 2 versions for pull requests or basic pushes

**Comment by saidctb** [comment]
I agree with @EmilyBourne

**Comment by EmilyBourne** [comment]
Similarly I don't know if it's worth running all platforms before we reach the pull request stage

**Comment by yguclu** [comment]
Since the macOS and Windows builds already use Python 3.8, I am going to use only Python 3.5 on Linux for non-master branches.

**Comment by yguclu** [comment]
By the way, it's possible to tell Travis-CI to skip a particular commit via a command in the commit message:

```
[skip travis] Update README
```

**Comment by rakati** [comment]
what do you think about using caching?
instead of always download and install some dependencies we may try caching them.

**Comment by yguclu** [comment]
We're already using caching for Homebrew on macOS. What else would you like to cache?
