### ISSUE TITLE
Generate C code for Numpy array operations

### ISSUE THREAD

**Issue by yguclu** [pyccel/pyccel#508]
**Description**

As a DEVELOPER, I need to translate Numpy array operations from Python to C, and by so doing use the Pyccel C standard library.

**Acceptance criteria**

- [ ] Copy C files to `__pyccel__` folder
- [x] Handle array creation
- [ ] Handle array deletion
- [x] Handle `__setitem__` with scalar and slice index
- [x] Handle `__getitem__` with scalar index
- [x] Handle `__getitem__` with slice index (creates array slice)
- [ ] Compile the generated code and the included C files
- [ ] Write unit tests

**Notes**
- This story is strictly about generating C code, not about calling it from Python

**Comment by EmilyBourne** [comment]
@saniQQ can you tick the boxes that have been done please
