### ISSUE TITLE
Do not use temporary variables for scalar single return in C

### ISSUE THREAD

**Issue by EmilyBourne** [pyccel/pyccel#513]
**Describe the bug**
When a function in C returns 1 scalar variable a temporary variable is created to mimic fortran. This is not necessary

**Test Code**
Provide code which does not currently work but which should do when this issue is fixed:
```python
@pure
def const_int_float():
    return 1
```

Currently generates:
```c
#include <test.h>
#include <stdlib.h>

/*........................................*/
long const_int_float(void)
{

    long Out_0001;
    Out_0001 = 1;
    return Out_0001;
}
/*........................................*/
```

**Language**
C

**Comment by EmilyBourne** [comment]
The PR that fixes this should also fix returns in the python printer

**Comment by saidctb** [comment]
this can be fixed in _print_return, where you have access to the value

**Comment by EmilyBourne** [comment]
> this can be fixed in _print_return, where you have access to the value

If this is fixed in the printer then you need to make sure that the return variable is not declared. We do not want unused variables in the generated code. I am not sure that I agree that this is the best place though, as Fortran is the exception here, not C and python

**Comment by EmilyBourne** [comment]
> I am not sure that I agree that this is the best place though, as Fortran is the exception here, not C and python

Fortran is the exception when 1 variable is returned, but when multiple variables are returned this is no longer the case. So I agree that the fix can be done in `_print_Return` by finding the original value in the `Assign` in `Return.stmt` if this exists.
Care will have to be taken to not declare the unused variable

**Comment by EmilyBourne** [comment]
As mentioned in PR #697

> During the review of this PR we noticed that the situation is more complicated than described in the issue when the function contains local arrays allocated on the heap. In this case there are deallocations which need to take place before the return statement. This can be a problem if the statement being returned uses an array operation. E.g:
> ```
> def f(j : int):
>     a = np.empty(j)
>     ...
>     return a.sum()
> ```
> In this case the temporary variable is necessary so that the sum is calculated before a is deallocated. However in the following case the temporary variable is not necessary:
> ```
> def g(a : 'int[:]'):
>     return a.sum()
> ```
> Currently there is no clean way to determine whether an expression contains a given variable. Once issue #694 is fixed then we can easily check whether or not the expression describing the contents of the temporary variable contains any of the variables which are deallocated. And thus whether the temporary variable is required or not
