### ISSUE TITLE
Handle functions that return Numpy arrays

### ISSUE THREAD

**Issue by yguclu** [pyccel/pyccel#537]
Description
---------------
As a USER, I would like to accelerate a Python function that returns a newly created array.

This happens all the time in prototype codes, even though it might not be the most efficient approach for HPC computing.

Acceptance Criteria
--------------------------
- [x] Return contiguous Numpy arrays in C
- [x] Return contiguous Numpy arrays in Fortran
- [x] Add extensive unit tests
- [x] Check for memory leaks
- [x] Return multiple arrays from a function

**Comment by EmilyBourne** [comment]
A first version of the implementation in fortran should look as follows:
- [ ] In pure fortran functions returning arrays should return an `allocatable`
- [ ] In the `bind_c_X.F90` file (see ast/cwrapper.py):
      - a `pointer` of the same size as the `allocatable` should be allocated
      - The data from the `allocatable` should be copied to the `pointer`
      - The address of the pointer should be saved in a `c_ptr` type using the `c_loc` function
- [ ] The `c_ptr` object (equivalent to `void*` in c) should be collected and translated to a numpy array in the `X_wrapper.c` file

**Comment by EmilyBourne** [comment]
Blocked by #886
