### ISSUE TITLE
Slices should have a step

### ISSUE THREAD

**Issue by EmilyBourne** [pyccel/pyccel#543]
**Describe the bug**
Steps in slices are not yet implemented however they are ready to use in c and could be added reasonably easily in fortran

**Test Code**
Provide code which does not currently work but which should do when this issue is fixed:
```python
import numpy as np

x = np.ones(10)
y = x[::2]
```

**Comment by yguclu** [comment]
This is a surprise to me! A Fortran slice is almost identical to a Numpy slice, so it should not be a problem to print the step.
