### ISSUE TITLE
The NOT operator does not work in fortran in the case of INTEGERS

### ISSUE THREAD

**Issue by nhamidn** [pyccel/pyccel#560]
**Describe the bug**
The python NOT operator does not work properly in the case of an integer for fortran.

**To Reproduce**
```python
x = 1

if not x:
    print("yes!")
```

the generated code is :
```bash/fortran/c
program prog_test

use ISO_C_BINDING

implicit none

integer(C_LONG_LONG) :: x

x = 1_C_LONG_LONG
if (.not. x) then
  print *, '' // 'yes!'
end if

end program prog_test
```

this generated code fail to compile.

```
   10 | if (.not. x) then
      |         1
Error: Operand of .not. operator at (1) is INTEGER(8)
```

i think if the `x` is not a `Boolean` then we need to cast `x` to `bool`.

**Language**
Fortran

**Comment by nhamidn** [comment]
@yguclu @EmilyBourne,  if the casting will solve this issue, i can create a small PR for that.

**Comment by EmilyBourne** [comment]
> @yguclu @EmilyBourne, if the casting will solve this issue, i can create a small PR to fix that.

I think casting in the printer should be enough :+1:
