### ISSUE TITLE
Allow multiple consecutive `+` and `-` unary operators

### ISSUE THREAD

**Issue by yguclu** [pyccel/pyccel#563]
Description
------------
As a USER, I would like to support the Python syntax `x = - - 1` and variations of it.

Language
------------
C, Fortran

Acceptance Criteria
-------------------------
- [x] Simplify consecutive unary operators `+` and  `-`
- [ ] Print parentheses when unary operator is combined with binary operator

**Comment by EmilyBourne** [comment]
I cannot reproduce this problem. This works for me, and is correctly translated to:
```
x = - (-1)
```

**Comment by EmilyBourne** [comment]
> Print parentheses when unary operator is combined with binary operator

This is fixed in PR #559

**Comment by EmilyBourne** [comment]
See #564 for details of the implementation and use case

**Comment by EmilyBourne** [comment]
Superseded by issue #564
