### ISSUE TITLE
Duplicated types in a template

### ISSUE THREAD

**Issue by rmahjoubi** [pyccel/pyccel#568]
**Describe the bug**
Using a template with duplicated types, causes a generation of identical functions with the same signature.

**To Reproduce**
Provide code to reproduce the behavior:
```python
from pyccel.decorators import types
from pyccel.decorators import template

@template('T', types=['int', 'int'])
@types('T')
def f(a):
    return a
```

Provide the generated code, or the error message:
```c
#include <test.h>
#include <stdlib.h>



/*........................................*/
long f_00(long a)
{

    long Out_0001;

    Out_0001 = a;
    return Out_0001;
}
/*........................................*/

/*........................................*/
long f_01(long a)
{

    long Out_0001;

    Out_0001 = a;
    return Out_0001;
}
/*........................................*/
```

**Expected behavior**
 Only one function should be generated.

**Language**
Fortran, C

**Comment by EmilyBourne** [comment]
Is there a fundamental difference between this issue and issue #567 ?

**Comment by rmahjoubi** [comment]
> Is there a fundamental difference between this issue and issue #567 ?

They require different changes, otherwise it's the same problem.
