### ISSUE TITLE
Update authors and add copyright

### ISSUE THREAD

**Issue by yguclu** [pyccel/pyccel#582]
- [x] Update author names
- [x] Add short copyright notice and disclaimer to each source file

**Comment by yguclu** [comment]
The LICENSE file should be modified: the line
```
Copyright (c) 2017 Ahmed Ratnani
```
should be changed to
```
Copyright (c) 2017-2020, Pyccel Developers.
```

**Comment by yguclu** [comment]
The AUTHORS file should be reorganized. Following [GitHub's documentation](https://opensource.guide/how-to-contribute/#anatomy-of-an-open-source-project), I suggest the following format:
```
Maintainers
-----------
* Ahmed Ratnani <ratnaniahmed@gmail.com> (project creator, owner)
* Yaman Güçlü <yaman.guclu@gmail.com> (administrator, owner)
* Said Hadjout
* Emily Bourne

Contributors
------------
* <1337 students>
* ...
```
@ratnania @saidctb @EmilyBourne Does this make sense to you?

**Comment by EmilyBourne** [comment]
This makes sense to me. With each of the <1337 students> listed explicitly of course

**Comment by yguclu** [comment]
> This makes sense to me. With each of the <1337 students> listed explicitly of course

Yes of course! I thought that was

**Comment by EmilyBourne** [comment]
I assume you closed this by accident?

**Comment by yguclu** [comment]
> I assume you closed this by accident?

Yes, I wanted to click on "Cancel" but my muscle memory clicked on the "Close with comment" button instead 😅

**Comment by yguclu** [comment]
As for the copyright notice to be included in each source file, @mostafaMamoni and I suggest
```
This file is part of pyccel which is released under MIT License.
See file LICENSE or go to https://github.com/pyccel/pyccel/blob/master/LICENSE for full license details.
```
Corrections are welcome.

**Comment by mostafaMamoni** [comment]
> The AUTHORS file should be reorganized. Following [GitHub's documentation](https://opensource.guide/how-to-contribute/#anatomy-of-an-open-source-project), I suggest the following format:
> 
> ```
> Maintainers
> -----------
> * Ahmed Ratnani <ratnaniahmed@gmail.com> (project creator, owner)
> * Yaman Güçlü <yaman.guclu@gmail.com> (administrator, owner)
> * Said Hadjout
> * Emily Bourne
> 
> Contributors
> ------------
> * <1337 students>
> * ...
> ```
> 
> @ratnania @saidctb @EmilyBourne Does this make sense to you?

i think we (1337 students) had some contributions about driving the vision and managing the organizational aspects of the project, so according to github we deserve the maintainers title 😇.
