### ISSUE TITLE
pyccel says function missing type annotation, but function is annotated

### ISSUE THREAD

**Issue by Beliavsky** [pyccel/pyccel#603]
For the code xfib.py

```
def Fibonacci(n: int) -> int:
    if n<=0:
        print("Incorrect input")
    # First Fibonacci number is 0
    elif n==1:
        return 0
    # Second Fibonacci number is 1
    elif n==2:
        return 1
    else:
        return Fibonacci(n-1)+Fibonacci(n-2)
 
print(Fibonacci(9))
```

`pyccel xfib.py `

gives

```
ERROR at annotation (semantic) stage
pyccel:
 |error [semantic]: xfib.py [1]| Function is missing a type annotation (Fibonacci)
 |fatal [semantic]: xfib.py [1]| Undefined variable (n)
```

**Comment by EmilyBourne** [comment]
Hi,

Thank you for your interest in pyccel. Unfortunately, pyccel is unable to read python style type annotation. Instead, the type annotation is done with a comment header or a decorator. We are currently writing a quickstart file which will provide an explanation of how this is done, but in the meantime I suggest looking at the examples in the tests. 

For the comment header syntax see:
https://github.com/pyccel/pyccel/blob/master/tests/pyccel/scripts/hope_benchmarks/hope_fib.py
and for the decorator syntax see:
https://github.com/pyccel/pyccel/blob/master/tests/pyccel/scripts/hope_benchmarks_decorators/hope_fib.py

(Both these examples specify the return type, but this is only necessary for recursive functions)

**Comment by saidctb** [comment]
Hi @Beliavsky,
you can use pyccel like this
```python
@types('int', results='int')
def fibonacci(n: int) -> int:
    if n<=0:
        print("Incorrect input")
    # First Fibonacci number is 0
    elif n==1:
        return 0
    # Second Fibonacci number is 1
    elif n==2:
        return 1
    else:
        return Fibonacci(n-1)+Fibonacci(n-2)
```
we plan to add the python annotations in the futur

**Comment by Beliavsky** [comment]
> ```python
> @types('int', results='int')
> ```

Thank you. I am able to make it work. In your code, Fibonacci should be capitalized consistently.

**Comment by yguclu** [comment]
I think it would be nice to support type hints, so I've created a separate feature request where we can have a discussion: #606.
