### ISSUE TITLE
Improve Python Printer (pycode)

### ISSUE THREAD

**Issue by ratnania** [pyccel/pyccel#643]
Right now, our Python Printer is not up-to-date. It was mainly improved so that Psydac works.

**Comment by EmilyBourne** [comment]
We should allow pyccel to translate from python to python. That way we could use all our existing tests to test the python printer

**Comment by ratnania** [comment]
Yes!!

**Comment by EmilyBourne** [comment]
This issue can be closed when the following tasks have been completed:
- [ ] Activate python tests in `tests/pyccel/` folder
- [ ] Add openmp printing to python printer

Additional problems are described by #802 and `ValuedVariable` problems (#700, #696)
