### ISSUE TITLE
Keep hidden imports (needed for pycode) related to issue-#643

### ISSUE THREAD

**Issue by ratnania** [pyccel/pyccel#644]
In many cases, some imports are removed since we rely on intrinsic Fortran functions.

Let's take the following example
```python
from pyccel.decorators import types

@types( 'int[:,:](order=C)' )
def double_loop_on_2d_array_C( z ):

    from numpy import shape

    m, n = shape( z )

    for i in range( m ):
        for j in range( n ):
            z[i,j] = i-j
```

The generated code is (using devel-643):
```python
@types("int[:,:](order=C)")
def double_loop_on_2d_array_C(z):    
    m = shape(z)[0]
    n = shape(z)[1]
    for i in range(0, m, 1):
        for j in range(0, n, 1):
            z[i,j] = i - j
```

**Expected behavior**
The import of **shape** must be kept somewhere so that we can print it using **pycode**.

**Language**
python to Python

**Additional context**
Some improvements have been done on pycode in #643

**Comment by saidctb** [comment]
the import is kept in `self.namespace.imports`

**Comment by ratnania** [comment]
I tried, but when I add the following statement inside **_print_FunctionDec** 

```python
        print('>>>> ', self.parser.namespace.imports)
```

I get the following result

```shell
>>>>  OrderedDict([('functions', OrderedDict()), ('variables', OrderedDict()), ('classes', OrderedDict()), ('imports', OrderedDict()), ('python_functions', OrderedDict()), ('symbolic_functions', OrderedDict())])
```

The **imports** dictionary is empty

**Comment by saidctb** [comment]
it's because of this line we only insert the function and ignore the imports , https://github.com/pyccel/pyccel/blob/master/pyccel/parser/semantic.py#L2866

**Comment by saidctb** [comment]
we probably need to insert the imports also

**Comment by ratnania** [comment]
Exactly!
Can we assign someone to this issue?

**Comment by ratnania** [comment]
I think a simple fix, would be to add an attribute **ignore** in **Import** then we can treat it or not in the **printing** stage

**Comment by saidctb** [comment]
> Exactly!
> Can we assign someone to this issue?

yes, any of the students can do it.
@MenoIy , @rakati , @mostafaMamoni , @nhamidn , @saniQQ , @rmahjoubi
is anyone willing to take this issue?
