### ISSUE TITLE
IfTernaryOperator is missing precedence

### ISSUE THREAD

**Issue by EmilyBourne** [pyccel/pyccel#648]
**Describe the bug**
An `IfTernaryOpererator` is an Operator. As such it should inherit from `PyccelOperator` and define a precedence. In Fortran this distinction is not important as the `IfTernaryOperator` is translated to a function however in C this leads to errors.

**To Reproduce**
Provide code to reproduce the behavior:
```python
@types('int')
def f9(x):
    a = ((5 + 7) if x < 5 else x) + 2
    return a
```

Incorrect C code:
```c
int64_t f9(int64_t x)
{
    int64_t a;
    a = (x < 5) ? 5 + 7 : x + 2;
    return a;
}
```

Correct Fortran code:
```
function f9(x) result(a)

  implicit none

  integer(C_INT64_T) :: a
  integer(C_INT64_T), value :: x

  a = merge(5_C_INT64_T + 7_C_INT64_T, x, x < 5_C_INT64_T) + 2_C_INT64_T
  return

end function f9
```

**Expected behavior**
The correct C code should be:
```c
int64_t f9(int64_t x)
{
    int64_t a;
    a = ((x < 5) ? 5 + 7 : x)  + 2;
    return a;
}
```

ideally the fortran code should remain the same rather than generating unnecessary parentheses

**Comment by saidctb** [comment]
```python
@types('int')
def f9(x):
    a = ((5 + 7) if x < 5 else x) + 2
    return a
```
why do we ignore the parethesis in this case ?

**Comment by EmilyBourne** [comment]
> ```python
> @types('int')
> def f9(x):
>     a = ((5 + 7) if x < 5 else x) + 2
>     return a
> ```
> 
> why do we ignore the parethesis in this case ?

Parentheses are added back when we handle classes which inherit from `PyccelOperator`. Despite being an operator `IfTernaryOperator` doesn't inherit from `PyccelOperator` so it doesn't have a precedence and doesn't get the parentheses added back
