### ISSUE TITLE
C shape data doesn't have same type as fortran data

### ISSUE THREAD

**Issue by EmilyBourne** [pyccel/pyccel#649]
**Describe the bug**
Pyccel expects shapes to be saved in the default `int` type, but shapes in c are saved in `int32_t`. As a result warnings are raised when we print the shape

**To Reproduce**
Provide code to reproduce the behavior:
```python
import numpy as np

x = 4
a = np.ones(x)
print(np.shape(a)[0])
```

Provide the generated code, or the error message:
```bash/fortran/c
/home/emily/Code/test/tmp/__pyccel__/tmp.c:21:15: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 2 has type ‘int32_t {aka int}’ [-Wformat=]
     printf("%ld\n", a.shape[0]);
             ~~^     ~~~~~~~~~~
             %d

  warnings.warn(UserWarning(output))
```

The same warning is raised when the shape is known (literal shape):
```python
import numpy as np

a = np.ones(4)
print(np.shape(a)[0])
```
```bash
/home/emily/Code/test/tmp/__pyccel__/tmp.c:21:15: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 2 has type ‘int’ [-Wformat=]
     printf("%ld\n", 4);
             ~~^
             %d

  warnings.warn(UserWarning(output))
```

**Expected behavior**
Either the shape data type should be changed (this will not fix the literal case, which can only be fixed by adding a precision specifier), or the printer should be improved to know that the shape precision is different in c

**Language**
C

**Comment by EmilyBourne** [comment]
@rakati Does PR #632 fix this issue?

**Comment by rakati** [comment]
PR #632 fix the first case, but the second needs improvements.
I think for the second case we should have `printf("%ld\n", a.shape[0]);` instead of `printf("%ld\n", 4);`.

**Comment by EmilyBourne** [comment]
Ok. I think the second case is due to how we handle `numpy.shape`. I discussed this with @rmahjoubi . I think it is a separate issue. So I think we can consider that #632 fixes this issue

**Comment by yguclu** [comment]
> Ok. I think the second case is due to how we handle `numpy.shape`. I discussed this with @rmahjoubi . I think it is a separate issue. So I think we can consider that #632 fixes this issue

Should this issue be closed then?

**Comment by EmilyBourne** [comment]
> > Ok. I think the second case is due to how we handle `numpy.shape`. I discussed this with @rmahjoubi . I think it is a separate issue. So I think we can consider that #632 fixes this issue
> 
> Should this issue be closed then?

I think so
