### ISSUE TITLE
Generate the module and the program in the same file 

### ISSUE THREAD

**Issue by saidctb** [pyccel/pyccel#653]
in the case of a program we currently generate two seperate files , one contains the functions and one contains the program.
**example
```python
def f():
    return 1

print(f())
```
this will generate two fortran files
The module
```fortran
module file1

use, intrinsic :: ISO_C_BINDING

implicit none

contains

!........................................
function f() result(Out_0001)

  implicit none

  integer(C_INT64_T) :: Out_0001

  Out_0001 = 1_C_INT64_T
  return

end function f
!........................................

end module file1

```
and the program
```fortran
program prog_prog_file1

use nparray, only: f
use, intrinsic :: ISO_C_BINDING

implicit none

print *, f()

end program prog_prog_file1
```
we would like to put them in one file as follows
```fortran
module file1

use, intrinsic :: ISO_C_BINDING

implicit none

contains

!........................................
function f() result(Out_0001)

  implicit none

  integer(C_INT64_T) :: Out_0001

  Out_0001 = 1_C_INT64_T
  return

end function f
!........................................
subroutine prog_prog_file1()
print *, f()
end subroutine
end module file1
```

**Comment by saidctb** [comment]
to fix this issue we need to change the `Program` node to contain a `Module` , and this needs to be determined in the semantics stage, where we decide if a python script represents a program or a module.

**Comment by EmilyBourne** [comment]
This was a conscious choice that we made a year or two ago. If I remember correctly they were split to handle the case where the user does something like:
```
def f():
    return 1

print(f())
```
```
from prog1 import f
print(f())
```
Can you explain why you think this is no longer useful?

**Comment by EmilyBourne** [comment]
The PR where this was done is PR #345 this should give indications about what needs to be changed back if we want to keep this issue

**Comment by saidctb** [comment]
> This was a conscious choice that we made a year or two ago. If I remember correctly they were split to handle the case where the user does something like:
> 
> ```
> def f():
>     return 1
> 
> print(f())
> ```
> 
> ```
> from prog1 import f
> print(f())
> ```
> 
> Can you explain why you think this is no longer useful?
yes you are right it's not going to work because this will result in two programs, that's why I wanted to fix it imagine having two scripts that are programs and one of them modifies a global variable which are imported by the other.
example
`file1.py`
```python
x = 1
```
`file2.py`
```python
from file1 import x
print(x)
```
our preivous approch is not gonna work.
even the generated `.so` is not going to give the right behaviour.
so I was thinking of putting the program in a function that we can call `def file_name_main()`
which contains the instructions of the program, this way we can import from that file, and execute the program after that

**Comment by saidctb** [comment]
we can even execute the program when we import from the `.so` file by executing the main function in the module initializer of the cpython wrapper

**Comment by EmilyBourne** [comment]
> our preivous approch is not gonna work.
even the generated .so is not going to give the right behaviour.
so I was thinking of putting the program in a function that we can call file_name_main()
which contains the instructions of the program, this way we can import from that file, and execute the program after that

Yes we also discussed doing this and I think it could be worthwhile, but I don't know why we need to combine the module and the program to do it?

Can we import from the module `nparray` in your example above in a different fortran file?

**Comment by saidctb** [comment]
> Yes we also discussed doing this and I think it could be worthwhile, but I don't know why we need to combine the module and the program to do it?
> 
> Can we import from the module `nparray` in your example above in a different fortran file?

we can't if we don't transform the program into a function.
what I want is to include the main program into the module , so it will be a function of the module

**Comment by EmilyBourne** [comment]
>we can't if we don't transform the program into a function.
what I want is to include the main program into the module , so it will be a function of the module

This is not what you have described in the issue.

If the issue is about creating a main function which will be stored in the module then I agree with you but the issue description needs modifying.

If the issue is just about writing the program and the module in the same file as described then I still don't see the utility

**Comment by saidctb** [comment]
yes, I wanted to do it in two steps, first is putting the program and the module in one file and then putting them in one module, but it seems to be not possible, so I will update the example.

**Comment by saidctb** [comment]
what's missing is creating an executable if the user asks for it otherwise we will create a `.so` file which execute the program when it's imported

**Comment by yguclu** [comment]
@saidctb So you simply want to add some instructions at import time?

This would mean that the variables created in the Python module become `static` variables in C, and module variables in Fortran. I think we need to discuss about this in detail.

**Comment by saidctb** [comment]
> @saidctb So you simply want to add some instructions at import time?
> 
> This would mean that the variables created in the Python module become `static` variables in C, and module variables in Fortran. I think we need to discuss about this in detail.

yes, we can discuss about it to better explain the mechanism
