### ISSUE TITLE
Printing of optional arguments does not work in C

### ISSUE THREAD

**Issue by EmilyBourne** [pyccel/pyccel#700]
**Describe the bug**
Optional arguments are not printed in C. No error is raised, they just disappear from the code!

**To Reproduce**
Provide code to reproduce the behavior:
```python
def f(n : int = 0):
    print(n)
```

Provide the generated code, or the error message:
```c
#include "shape.h"
#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>

/*........................................*/
void f(int64_t n)
{
    printf("\n");
}
/*........................................*/
```

**Expected behavior**
The value should be printed. An error should be raised if `_print_Print` encounters an object that it doesn't know how to print

**Language**
C

**Comment by yguclu** [comment]
We also have an issue with optional arguments in Fortran. Instead of checking using
```fortran
if (present(arg)) then
```
we compare against a zero value. I think we should be able to write a workaround in the `bind_<NAME>.c` file.

**Comment by EmilyBourne** [comment]
> We also have an issue with optional arguments in Fortran. Instead of checking using
> 
> ```fortran
> if (present(arg)) then
> ```
> 
> we compare against a zero value. I think we should be able to write a workaround in the `bind_<NAME>.c` file.

I cannot reproduce this behaviour. The following:
```
def f(n : int = None):
    if n is not None:
        print(n)
```
is correctly translated to:
```
module shape

use, intrinsic :: ISO_C_BINDING

implicit none

contains

!........................................
subroutine f(n)

  implicit none

  integer(C_INT64_T), value, optional :: n

  if (present(n)) then
    print *, n
  end if

end subroutine f
!........................................

end module shape
```

**Comment by MenoIy** [comment]
valued arguments were ignored at _print_PythonPrint 
```PYTHON
if isinstance(f, ValuedVariable):  #all valued arguments stop here 
       if f.name == 'sep'      :   sep = str(f.value)
       elif f.name == 'end'    :   end = str(f.value)
elif isinstance(f, FunctionCall) and isinstance(f.dtype, NativeTuple):
```
changing elif to an it wil fix the problem for known type valued arguments

**Comment by EmilyBourne** [comment]
> valued arguments were ignored at _print_PythonPrint
> 
> ```python
> if isinstance(f, ValuedVariable):  #all valued arguments stop here 
>        if f.name == 'sep'      :   sep = str(f.value)
>        elif f.name == 'end'    :   end = str(f.value)
> elif isinstance(f, FunctionCall) and isinstance(f.dtype, NativeTuple):
> ```
> 
> changing elif to an it wil fix the problem for known type valued arguments

Hmm, given that valued arguments are for holding the kwargs of a function I don't think the argument to the function should still be a `ValuedVariable` here. Just changing to an if will cause problems for examples such as the following:
```
def f(end : int = 0):
    tmp = 2
    print(end,tmp)

f(5)
```
the python result is:
```
5 0
```
but the pyccel result (in C only) is:
```
20
```

**Comment by yguclu** [comment]
@EmilyBourne This is what I was talking about: the Python code
```python
def f(n : int = None):
    if n:
        print(n)
```
is translated to
```fortran
subroutine f(n) 

  implicit none

  integer(C_INT64_T), value, optional :: n

  if (n /= 0) then
    print *, n
  end if

end subroutine f
```
By changing `if n` with `if n is not None` I get what I was expecting, but in fact my Python example was a bit ambiguous. To get the same behavior as Python I suppose we should print:
```fortran
if (present(n) .and. n /= 0) then
  print *, n
end if
```
or maybe safer:
```fortran
if (present(n)) then
  if (n /= 0) then
    print *, n
  end if
end if
```

**Comment by EmilyBourne** [comment]
Duplicate of #876
