### ISSUE TITLE
FloorDiv does not give an int in C

### ISSUE THREAD

**Issue by EmilyBourne** [pyccel/pyccel#702]
**Describe the bug**
The floor division `a//b` in C is translated to `floor(double(a)/double(b))` in order to preserve the correct rounding behaviour. However `floor` from `math.h` returns a `float`. This means that the floor division returns a floating point. This can potentially cause problems depending on how the result is used.
If the result is saved in a variable then there is no problem.
If the result is used as an index it causes a segmentation fault.
If the result is passed to the print function, the wrong result is printed

**To Reproduce**
For example:
```python
print(3//4)
```

Translates to:
```c
#include <stdlib.h>
#include <math.h>
#include <stdio.h>
int main()
{


    printf("%ld\n", floor(3.0 / 4.0));
    return 0;
}
```

which raises the warning:
```
/home/emily/.local/lib/python3.6/site-packages/pyccel/codegen/utilities.py:154: UserWarning: /home/emily/Code/test/tmp/__pyccel__/tmp.c: In function ‘main’:
/home/emily/Code/test/tmp/__pyccel__/tmp.c:8:15: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 2 has type ‘double’ [-Wformat=]
     printf("%ld\n", floor(3.0 / 4.0));
             ~~^
             %f

  warnings.warn(UserWarning(output))
```
Executing the program gives the following result:
```
140728609725192
```

**Language**
C

**Comment by rakati** [comment]
we just need to add casting to `int64_t`.

**Comment by EmilyBourne** [comment]
This issue might also be valid for `numpy.floor` and `math.floor`
