### ISSUE TITLE
Arguments passed to `get_index` cause segmentation faults if they do not have the expected type

### ISSUE THREAD

**Issue by EmilyBourne** [pyccel/pyccel#703]
**Describe the bug**
When indexing an array in C we must find the global index from n indices. This is done via the function `get_index`. `get_index` makes use of variadic arguments in order to collect an unknown number of arguments. However care must be taken when using variadic arguments as the input arguments are **interpreted** as the expected type, **not cast** to the expected type. As a result it is very important that the input argument has the right type. It seems that there is some flexibility here as currently we are passing `int64_t` and expecting `int32_t` I don't know if this is a fluke or not. More importantly if a non-int type is passed to `get_index` (cf #702 ) there is a segmentation fault

**To Reproduce**
Provide code to reproduce the behavior:
```python
from numpy import shape
def f(a : 'float[:]'):
    lo = 0
    hi = shape(a)[0]
    pivot = a[(lo + hi)//2]
```

**Acceptance Criteria**
- [ ] Implement solution to the problem: change signature of `get_index` so that it accepts the default CPython integer type
- [ ] Add unit test

**Language**
C

**Comment by rakati** [comment]
I did a test with the Gnu compiler using some integer types and it works without error (char, short, int, long, long int, unsigned char, unsigned short, unsigned long int, size_t).
I used the same test with flags -Wall -Wextra -Werror and I got a warning only for the char type. @EmilyBourne it is not a fluke but it seems that the compiler handles this. the only not supported types are real types and complex types. I think we need to raise an error for these types same as numpy do.

**Comment by EmilyBourne** [comment]
> I did a test with the Gnu compiler 

I was hoping for something in the standard as results of research not circumstantial evidence for one compiler :/

**Comment by saniQQ** [comment]
```
If there is no actual next argument,
or if type is not compatible with the type of the actual next argument (as promoted according to the
default argument promotions), the behavior is undefined, except for the following cases:
— one type is a signed integer type, the other type is the corresponding unsigned integer type,
and the value is representable in both types;
— one type is pointer to void and the other is a pointer to a character type.
```
default argument promotions: promote char and short int to int.
