### ISSUE TITLE
Improve the bind_c files

### ISSUE THREAD

**Issue by saidctb** [pyccel/pyccel#705]
The way we generate the `bind c` files, makes the compilation slow by the fortran compiler.
For this example
```python
def f(x:int, y:float):
    return x + y 
```
We generate the following `bind c` file
```fortran
function f(x, y) bind(c) result(Out_0001)

  use test, only: mod_f => f
  use, intrinsic :: ISO_C_BINDING
  implicit none

  integer(C_INT64_T), value :: x
  real(C_DOUBLE), value :: y
  real(C_DOUBLE) :: Out_0001
  
  Out_0001 = mod_f(x, y)
  
end function f
```
We would like to generate it in the following way
```fortran
module bind_c_test

  use, intrinsic :: ISO_C_BINDING
  use test

  implicit none

contains

  function bind_c_f(x, y) bind(c) result(Out_0001) 
    integer(C_INT64_T), value :: x
    real(C_DOUBLE), value :: y
    real(C_DOUBLE) :: Out_0001
  
    Out_0001 = f(x, y)
  
  end function bind_c_f

end module bind_c_test
```
The `c wrapper` file will have the following signature:
`double bind_c_f(int x, double y);`
instead of:
`double f(int x, double y);`

**Comment by yguclu** [comment]
As a first step we can keep the names that we have, and just make the minimum number of changes:

1. Put all functions inside an enclosing module called `bind_c_[...]`;
2. Collect all the `use` statements outside of the functions.
