### ISSUE TITLE
Numpy types int8, int16, bool are not handled

### ISSUE THREAD

**Issue by mostafaMamoni** [pyccel/pyccel#733]
When doing something like `from M import X as Y` Pyccel raises `Undefined variable Y`, just for `bool` `int8` and `int16`

**To Reproduce**
Provide code to reproduce the behavior:
```python
from numpy import bool as NumpyBool
from numpy import int8 as NumpyInt8
from numpy import int16 as NumpyInt16
g = NumpyBool(0)
a = NumpyInt8(True)
b = NumpyInt16(False)
print(g)
print(a)
print(b)
```
and
```python
def test_int8():
        from numpy import real, shape, array, int8
        arr = array([[4,5,6,2,1],[4,5,6,2,1]], int8)
        a = real(arr)
        s = shape(a)
        return len(s), s[0], s[1], a[0,1], a[1,0]
```
 the error messages:
First example  ` |fatal [semantic]: test_real.py [3]| Undefined function (NumpyBool)`
Second example `|fatal [semantic]: test_real.py [4,4]| Undefined variable (int8)`

**Expected behavior**
Shouldn’t raise any errors, and handle data types importing correctly.

**Comment by EmilyBourne** [comment]
Can you please provide an example of code that doesn't work
