### ISSUE TITLE
Allow homogeneous tuples as read-only function arguments

### ISSUE THREAD

**Issue by yguclu** [pyccel/pyccel#738]
As a USER, I would like to pass homogeneous tuples to a function, in order to reduce the number of arguments.

Use case
-------------

In a numerical simulation, homogeneous tuples are often used to collect parameters together in a logical fashion. For example:
- `degrees = (2, 3, 3)` may be the polynomial degree along each dimension (`x1, x2, x3)` of the computational domain;
- `ncells = (100, 200, 200)` may be the number of grid cells along `(x1, x2, x3)`;
- `periodic = (False, False, True)` may tell whether the domain is periodic along `(x1, x2, x3)`.

It is convenient to pass these parameters as tuples, rather than unpacking their contents:

```python
def func(degrees: tuple[int], ncells: tuple[int], periodic: tuple[bool], ... ):
```

References
--------------
For the annotation style in this case, see https://www.python.org/dev/peps/pep-0585/

**Comment by EmilyBourne** [comment]
This syntax doesn't seem quite right. As I understand it `tuple[int]` would be a tuple of length 1 containing an integer. The syntax for homogeneous tuples seems to be `tuple[int, ...]` (see https://mypy.readthedocs.io/en/stable/kinds_of_types.html#tuple-types)
