### ISSUE TITLE
Allow instructions in Python module (outside of functions)

### ISSUE THREAD

**Issue by yguclu** [pyccel/pyccel#739]
Description
--------------
As a USER, I would like to include instructions of various kind in a Python module, to be executed when the module is imported.

Acceptance criteria
------------------------
- Declare Python module variables in Fortran module, not program
- Move module instructions to `module_init` function, not program
- Only create a program if explicitly required by the user
- In Fortran module, add private variable
  ```fortran
  logical, private :: initialized = .false.
  ```
   which should be set to `.true.` by `module_init`
- Subsequent calls to `module_init` should do nothing if `initialized == True`
- `module_init` should call `module_init` on all other Pyccel-accelerated imported modules
- Make sure that `module_init` is called when the C extension module is imported

NOTE: all module variables will not be used by other modules at this stage.

Example
-----------
Let's consider the Python module `instructions.py`:

```python
def add(a: int, b: int):
    return a + b

print("Importing module 'instructions'")
x = 5
y = 6
print('x + y = ', add(x, y))
```
When the module is imported from IPython, the instructions are executed. But they are not executed a second time if the module is imported again:

```python
In [1]: import instructions                                                               
Importing module 'instructions'
x + y =  11

In [2]: import instructions                                                               

In [3]:
```
When calling `pyccel instruction.py -f` we should generate this Fortran file:

```fortran
module instructions

use, intrinsic :: ISO_C_BINDING

implicit none

logical, private :: initialized = .false.
integer(C_INT64_T) :: x
integer(C_INT64_T) :: y

contains

!........................................
function add(a, b) result(Out_0001)

  implicit none

  integer(C_INT64_T) :: Out_0001
  integer(C_INT64_T), value :: a
  integer(C_INT64_T), value :: b

  Out_0001 = a + b
  return

end function add
!........................................

!........................................
subroutine module_init

  if (initialized .eqv. .true.) then
    return
  end if
  
  print *, 'Importing module ' // ACHAR(39) // 'instructions' // ACHAR(39)
  x = 5_C_INT64_T
  y = 6_C_INT64_T
  print *, 'x + y = ' // ' ' , add(x, y)

end subroutine module_init
!........................................

end module instructions
```

**Comment by EmilyBourne** [comment]
Blocked by #886
