### ISSUE TITLE
np.array in c does not handle lists of vector variables

### ISSUE THREAD

**Issue by EmilyBourne** [pyccel/pyccel#752]
**Describe the bug**
`np.array` works for lists of scalars and lists of lists of scalars, but it does not handle lists of variables

**To Reproduce**
Provide code to reproduce the behavior:
```python
@types('real[:,:]','real[:,:]')                         
def array_real_3d_C_array_initialization_1(x, y):                   
    from numpy import array                                            
    tmp      = array([x, y], dtype='float')
```

Provide the generated code, or the error message:
```bash/fortran/c
Traceback (most recent call last):
  File "/home/emily/Code/pyccel/pyccel/codegen/printing/ccode.py", line 1297, in _print_Assign
    return self.copy_NumpyArray_Data(expr)
  File "/home/emily/Code/pyccel/pyccel/codegen/printing/ccode.py", line 317, in copy_NumpyArray_Data
    arg = functools.reduce(operator.concat, arg)
TypeError: 'Variable' object can't be concatenated
```

**Expected behavior**
This should be handled, if it is non-trivial then as a first step a neat error should be raised

**Language**
C

**Comment by saniQQ** [comment]
it will need a concatenation function to do so.

**Comment by EmilyBourne** [comment]
Error is now:
![image](https://user-images.githubusercontent.com/25363473/125041866-858a8d00-e099-11eb-80a3-4d3e81d14f25.png)
