### ISSUE TITLE
Add the attribute **name** to numpy functions

### ISSUE THREAD

**Issue by ratnania** [pyccel/pyccel#754]
For each of our numpy functions, we need to add the attribute **name**.
For example: for **NumpySin** we shall have **sin** etc

**Comment by yguclu** [comment]
@ratnania Why do you think this is necessary?

**Comment by ratnania** [comment]
When computing the complexity, we need to put SIN for example when we have a call to the sinus function.
Two options:
- have a dictionary in the complexity base file where we map the class with the name. But this means more maintaning, whenever we add new functions...
- have the name as an attribute in the class

**Comment by EmilyBourne** [comment]
Does this mean that all the numpy classes should inherit from one superclass? Or should all classes which inherit from `PyccelInternalFunction` have a `name`?

**Comment by EmilyBourne** [comment]
As per our discussion all classes inheriting from `PyccelInternalFunction` can have this attribute
