### ISSUE TITLE
Numpy.prod is not supporting scalar arguments

### ISSUE THREAD

**Issue by mostafaMamoni** [pyccel/pyccel#768]
**Describe the bug**
Numpy.prod is not supporting scalar arguments.

**To Reproduce**
Provide code to reproduce the behavior:
```python
@types('int')
    def test_int(a):
        from numpy import prod
        b = prod(a)
        return b
```

The error message:
```
ERROR at Fortran compilation stage
```
the compilation error message:
```
/Users/mostafamamouni/Desktop/env-pyccel/my_tests/__pyccel__/test_fib.f90:9:12:

    9 | b = product(5_C_INT64_T)
      |            1
Error: 'array' argument of 'product' intrinsic at (1) must be an array
```

**Expected behavior**
Generate a compilable code with correct results.

**Language**
Fortran.

**Additional context**
The tests are already in place in #719.

**Comment by EmilyBourne** [comment]
This can easily be fixed by adding a `__new__` method to `NumpyProd` which returns the argument if it is a scalar
