### ISSUE TITLE
Numpy.norm doesn't work

### ISSUE THREAD

**Issue by mostafaMamoni** [pyccel/pyccel#769]
Pyccel fails when using numpy.norm in any data type, it might need some investigations.

**To Reproduce**
Provide code to reproduce the behavior:
```python
    @types('int')
    def test_int(a):
        from numpy import norm
        b = norm(a)
        return b
```

The error message:
```
AttributeError: 'NumpyNorm' object has no attribute '_args'
```

**Expected behavior**
generate correct Fortran/C code.

**Language**
Fortran

**Additional context**
The tests are already in place in #719.

**Comment by EmilyBourne** [comment]
> AttributeError: 'NumpyNorm' object has no attribute '_args'

This error is due to [this line](https://github.com/pyccel/pyccel/blob/master/pyccel/ast/numpyext.py#L739) being in the wrong place. It should come after [this line](https://github.com/pyccel/pyccel/blob/master/pyccel/ast/numpyext.py#L731) as it is the call to `super().__init__` which sets the `_args` which are used when calling `self.dim` as done [here](https://github.com/pyccel/pyccel/blob/master/pyccel/ast/numpyext.py#L732)

**Comment by EmilyBourne** [comment]
```
@types('int')
def test_int(a):
    from numpy import norm
    b = norm(a)
    return b
```
This code does not run in python. I think you mean:
```
@types('int')
def test_int(a):
    from numpy.linalg import norm
    b = norm(a)
    return b
```

**Comment by EmilyBourne** [comment]
The example provided here is for a scalar input. The [documentation](https://numpy.org/doc/stable/reference/generated/numpy.linalg.norm.html) for numpy norm states that the input should be an array like. Tests show that `numpy.linalg.norm` does not fail when called on a scalar input, but gives the following results:
- For boolean/int arguments : they are cast to `np.float64`
- For float arguments : they are returned without modification
- For complex arguments : NumpyAbs of the argument is returned

This behaviour can be implemented in a `__new__` function

**Comment by mostafaMamoni** [comment]
> The example provided here is for a scalar input. The [documentation](https://numpy.org/doc/stable/reference/generated/numpy.linalg.norm.html) for numpy norm states that the input should be an array like. Tests show that `numpy.linalg.norm` does not fail when called on a scalar input, but gives the following results:
> 
> * For boolean/int arguments : they are cast to `np.float64`
> * For float arguments : they are returned without modification
> * For complex arguments : NumpyAbs of the argument is returned
> 
> This behaviour can be implemented in a `__new__` function

The same behaviour should be with arrays arguments, since norm function in Fortran does accept only `REAL` type.
