### ISSUE TITLE
PythonLen is not implemented in C

### ISSUE THREAD

**Issue by EmilyBourne** [pyccel/pyccel#785]
**Describe the bug**
The `len` function is very useful and is used in several tests but it is not implemented in C. This is therefore blocking some tests

**Test Code**
Provide code which does not currently work but which should do when this issue is fixed:
```python
def f(a : 'int[:,:]'):
    return len(a)
```

**Language**
C

**Comment by MenoIy** [comment]
just for clarification when you say PythonLen is not implemented in C your are talking about array (ndarrays in c) or any new iterable datatype implemented in the future ?

**Comment by EmilyBourne** [comment]
We can't implement it for all unknown types that might be implemented in the future as we don't know what will be implemented or how it will be implemented. Currently `len` is not implemented for ndarrays though, which do exist currently.

For example this is blocking [this test](https://github.com/pyccel/pyccel/blob/master/tests/epyccel/test_epyccel_openmp.py#L172-L194) which uses [this code](https://github.com/pyccel/pyccel/blob/master/tests/epyccel/modules/openmp.py#L233-L244)
