### ISSUE TITLE
Assiging a variable to an array caused a return of freed object

### ISSUE THREAD

**Issue by mostafaMamoni** [pyccel/pyccel#792]
**To Reproduce**
Provide code to reproduce the behavior:
```python
def foo()
    from numpy import, array
    b = array([3,4,5,2,2], dtype='int32')
    a = b
    return a[0]
```
in `a = b`, `a` is a Variable object which will have `is_pointer=True`, in the return printer we evaluate the `rhs` of `Out_001 = a` as the following:
- get all Variable objects (in this case `a`).
- check if there is at least one allocatable object through `allocatable` flag to see if we will need the dummy variable or not.(the dummy variable is used to store the value of the indexed element and return it because the indexed element should be freed before the return statement)

the lines of code that are responsible of this process:
```python
            variables = last_assign[0].rhs.get_attribute_nodes(Variable, excluded_nodes=(FunctionDef,))
            unneeded_var = not any(b.allocatable and not b.is_argument for b in variables)
```

According to this process, `a` will have `is_pointer=True` which we not check, so it will be considered as a normal variable
, So we will return it directly without using a dummy variable, what will happen is returning an index from a freed pointer that points on an allocatable object.

in this case:
```C
int32_t get_real(void)
{
    t_ndarray b;
    t_ndarray a;

    b = array_create(1, (int64_t[]){5}, nd_int32);
    int32_t array_dummy_0001[] = {3, 4, 5, 2, 2};
    memcpy(b.nd_int32, array_dummy_0001, b.buffer_size);

    a = b;
    free_array(b);
    free_pointer(a);
    return a.nd_int32[get_index(a, 0)];
}
```
what should be printed:
```C
int32_t get_real(void)
{
    t_ndarray b;
    int32_t Out_0001;

    b = array_create(1, (int64_t[]){5}, nd_int32);
    int32_t array_dummy_0001[] = {3, 4, 5, 2, 2};
    memcpy(b.nd_int32, array_dummy_0001, b.buffer_size);

    a = b;
    Out_0001 = a.nd_int32[get_index(a, 0)];
    free_array(b);
    free_pointer(a);
    return Out_0001;
}
```

**Expected behavior**
we should have information about pointers that tells if it is pointing on an allocatable object or a stack array, to see if we will use the dummy variable for the first case or not for the second case.

**Language**
C
**Additional context**
this issue has been discovered while trying to activate C tests for numpy.real function.

**Comment by EmilyBourne** [comment]
We should use the presence of `deallocate` nodes to indicate if there was an allocation or not. That way we don't repeat the logic here (potentially leading it to become outdated as here)
