### ISSUE TITLE
Assiging a variable to an array of type`t_ndarray` missed the slicing of the array.

### ISSUE THREAD

**Issue by mostafaMamoni** [pyccel/pyccel#794]
Assiging a variable to an array of type`t_ndarray` generates a pointer assigned to an array without slicing.

**To Reproduce**
Provide code to reproduce the behavior:
```python
def f(a : 'int[:]'):
    b = a
```

The current generated code:
```c
void f(t_ndarray a)
{
    t_ndarray b;
    b = a;
    free_pointer(b);
}
```

**Expected behavior**
should have the same behavior as:
```python
def f(a : 'int[:]'):
    b = a[:]
```
which is:
```c
void f(t_ndarray a)
{
    t_ndarray b;
    b = array_slicing(a, 1, new_slice(0, a.shape[0], 1));
    free_pointer(b);
}
```
**Language**
C

**Comment by yguclu** [comment]
@mostafaMamoni Could you provide a full Python example where the pyccelized code does not give the correct result?
