### ISSUE TITLE
obscure error message when a function argument is missing

### ISSUE THREAD

**Issue by campospinto** [pyccel/pyccel#825]
**Describe the bug**
When a function is called with one (or more) argument(s) missing, the error message is obscure

**To Reproduce**
Provide code to reproduce the behavior:
```python
def f(b:'int'):
    print(b)
def g(a:'int'):
    f()
```

Provide the generated code, or the error message:
```
ERROR at code generation stage
pyccel:
|fatal [codegen]: ***.py| Pyccel has encountered syntax that has not been implemented yet. Please create an issue at https://github.com/pyccel/pyccel/issues and provide a small example of your problem. Do not forget to specify your target language
```

**Expected behavior**
The error message should indicate that an argument is missing (and where)

**Language**
Fortran and c

**Comment by EmilyBourne** [comment]
As a general rule pyccel is only guaranteed to work if the code that is provided already works correctly in python. Unfortunately it would be too costly to check every possible error. That said I agree that this error is confusing and it is easy to fix. So I am opening a PR to fix it
