### ISSUE TITLE
max function doesn't work as property of an ndarray variable (argument)

### ISSUE THREAD

**Issue by mostafaMamoni** [pyccel/pyccel#857]
**Describe the bug**
in #826, we renamed numpy.max/min to numpy.amax/amin since we have the results of those functions not numpy.max/min and the implementation as well, for now numpy.max/min are just an alias to numpy.amax/amin, so we don't need to modify the tests according to those changes in functions names. somehow `test_max_property` fails but not `test_min_property`
the problem, in a nutshell, is printing `amax` but importing `max` function. so it needs to be investigated in terms of functions aliasing.

**To Reproduce**
Provide code to reproduce the behavior:
```python
@types('int[:]')
def max_call(x):
        return x.max()
```

the generated code :
```python
@types('int[:]')
    def max_call(x):
        from numpy import max
        return amax(x)
```

the error message:
```
NameError: name 'amax' is not defined
```

**Expected behavior**
```
@types('int[:]')
def max_call(x):
       from numpy import amax
       return amax(x)
```

**Language**
python

**Additional context**
`test_max_property` is skiped right until this but get fixed.

**Comment by EmilyBourne** [comment]
> somehow test_max_property fails but not test_min_property

This must be a problem with the test as the following code:
```
def min_call(x : 'int[:]'):
        return x.min()
```
generates:
```
from pyccel.decorators import types

@types('int[:]')
def max_call(x):
    from numpy import min
    return amin(x)
```
