### ISSUE TITLE
Imports are missing in the generated code by the PythonPrinter

### ISSUE THREAD

**Issue by nhamidn** [pyccel/pyccel#873]
**Describe the bug**
The python generated code does not contain all the imports from the same library.

**To Reproduce**
This python code :
```python
 from numpy import array
 from numpy import zeros

 a = array([0,1,2,3,4,5,6,7,8,9])

 b = zeros(10)
```

is translated to this python code:
```python
from numpy import zeros

if __name__ == "__main__":
    a = array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int, order='C')
    b = zeros((10), dtype=float, order='C')
```

**Expected behavior**
The generated code must contain all the imports.

**Language**
Python

Once this issue is resolved one test must be activated in `tests/pyccel` folder #872

**Comment by EmilyBourne** [comment]
Do you know if this is a python problem (i.e. imports created by pyccel) or a general problem (also happens if the imports are specified by the user and are not removed by pyccel at the semantic stage, i.e. imports are user defined modules)

**Comment by nhamidn** [comment]
> Do you know if this is a python problem (i.e. imports created by pyccel) or a general problem (also happens if the imports are specified by the user and are not removed by pyccel at the semantic stage, i.e. imports are user defined modules)?

I don't have an idea about the issue, but I think per my testing that the problem is from the semantic stage, the visit function override all the import from the same source with the last one

**Comment by EmilyBourne** [comment]
> I don't have an idea about the issue, but I think per my testing that the problem is from the semantic stage, the visit function override all the import from the same source with the last one

In the semantic stage builtin imports (e.g. `math`/`numpy`) are treated differently to imports of user defined modules. That is why I am asking. This can easily be tested with 2 test files
