### ISSUE TITLE
sep and end parameters in print() not working in PythonPrinter

### ISSUE THREAD

**Issue by nhamidn** [pyccel/pyccel#874]
**Describe the bug**
sep and end parameters in print() not correctly generated in Python which leads to NameError.

**To Reproduce**
This python code
```python
print('ahoy', 'world', sep=' ', end='?')
```

Translated to this:
```python
if __name__ == "__main__":
    print('ahoy', 'world', sep, end)
```
and give a NameError
`NameError: name 'sep' is not defined`

**Language**
Python

**Additional context**
Once this issue is resolved, the failing test in PR #872 must be activated.

**Comment by EmilyBourne** [comment]
Related to #700 and #696.
`ValuedVariable` is used inconsistently in pyccel. It is used for an argument passed as a keyword argument to a `FunctionCall`, but it is also used for arguments with default values. As a result it is not always clear which it is. The problems associated with this are demonstrated [here](https://github.com/pyccel/pyccel/issues/700#issuecomment-765266849). This inconsistency is the reason why the python tests in the files `test_epyccel_default_args.py` and `test_epyccel_default_args.py` are deactivated

**Comment by EmilyBourne** [comment]
Blocked by #886
