### ISSUE TITLE
Current use of ValuedVariable leads to ambiguity

### ISSUE THREAD

**Issue by EmilyBourne** [pyccel/pyccel#876]
**Describe the bug**
ValuedVariable is used inconsistently in pyccel. It is used for an argument passed as a keyword argument to a FunctionCall, but it is also used for arguments with default values. As a result it is not always clear which it is. The following example demonstrates this problem:
```python
def f(end : int = 0):
    tmp = 2
    print(end,tmp)

f(5)
```

The result given by python is:
```bash
5 2
```

but the C translation gives:
```
20
```
(the optional arguments of the `print` function are not implemented in other languages).

This confusion is the cause of issue #700.

It is also the cause of issue #696 as in the given example at the moment of the call:
```
z2 = f2(1, m=0)
```
it is impossible to know if `m` is a keyword argument or an argument whose default value was `0`

**Expected behavior**
We should use 2 classes:
- `FunctionCallArgument` for all arguments to function calls. This class contains the argument passed and an optional keyword
- `Argument` for the argument of a function def. This class should contain a reference to the underlying variable. It may also contain information about the argument including potentially a default value

I.e in the following:
```
1 @types('int')
2 def f(a = 0):
3     b = a + 2
4     c = g(val = b)
5     d = g(val = a)
```
- `a` in line 2 should be a `Argument` (containing the `Variable` `a` and a value `0`)
- `a` in line 3 should be a basic `Variable`
- `val` in line 4 should be a `FunctionCallArgument` whose value is `b` which is in turn a basic `Variable`
- `val` in line 5 should be a `FunctionCallArgument` whose value is `a` which is in turn a basic `Variable`

Currently the behaviour is:
- `a` in line 2 is a `ValuedVariable` with value 0
- `a` in line 3 is a `ValuedVariable` with value 0
- `val` in line 4 is a `ValuedVariable` whose value is `b` which is in turn a basic `Variable`
- `val` in line 5 is a `ValuedVariable` whose value is `a` which is in turn a `ValuedVariable` with value 0

**Additional context**
This is causing problems in the python printer as can be seen in any of the tests in [test_epyccel_default_args.py](https://github.com/pyccel/pyccel/blob/master/tests/epyccel/test_epyccel_default_args.py) or [test_epyccel_optional_args.py](https://github.com/pyccel/pyccel/blob/master/tests/epyccel/test_epyccel_optional_args.py).

Possibly related #874 

**Acceptance Criteria**
- [x] The tests in [test_epyccel_default_args.py](https://github.com/pyccel/pyccel/blob/master/tests/epyccel/test_epyccel_default_args.py) or [test_epyccel_optional_args.py](https://github.com/pyccel/pyccel/blob/master/tests/epyccel/test_epyccel_optional_args.py) can be activated
- [x] Tests should be added to prove that #696 and #700 are fixed

**Comment by EmilyBourne** [comment]
This behaviour is implemented in branch `devel-issue876` for almost all parts of the code except `cwrappercode.py`. It is not worth modifying this file before PR #886 is merged. This issue is therefore blocked by #886

**Comment by EmilyBourne** [comment]
Blocked by #886

**Comment by nhamidn** [comment]
> ```python
> def f(end : int = 0):
>     tmp = 2
>     print(end,tmp)
> 
> f(5)
> ```
> 
> The result given by python is:
> 
> ```shell
> 5 0
> ```
> 

A small error in the description of the issue, the result of the test code in python is :
`5 2`
