### ISSUE TITLE
An interface argument cannot be both an array and a scalar

### ISSUE THREAD

**Issue by EmilyBourne** [pyccel/pyccel#892]
**Describe the bug**
In the cwrapper if any of the possible types of an interface argument is an array then the value is collected into a PyArrayObject. This causes compiler problems when we try to unpack a scalar

**To Reproduce**
Provide code to reproduce the behavior:
```python
@types('int[:]')
@types('int')
def f(a):
    print(a)
```

Provide the generated code, or the error message:
```bash/fortran/c
/home/emily/.local/lib/python3.8/site-packages/pyccel/codegen/python_wrapper.py:151: UserWarning: tmp_wrapper.c: In function ‘f_01_mini_wrapper’:
tmp_wrapper.c:62:31: warning: passing argument 1 of ‘(void (*)(PyObject *, void *))*(PyArray_API + 496)’ from incompatible pointer type [-Wincompatible-pointer-types]
   62 |         PyArray_ScalarAsCtype(a_tmp, &a);
      |                               ^~~~~
      |                               |
      |                               PyArrayObject * {aka struct tagPyArrayObject *}
tmp_wrapper.c:62:31: note: expected ‘PyObject *’ {aka ‘struct _object *’} but argument is of type ‘PyArrayObject *’ {aka ‘struct tagPyArrayObject *’}
tmp_wrapper.c:66:27: warning: passing argument 1 of ‘PyLong_AsLong’ from incompatible pointer type [-Wincompatible-pointer-types]
   66 |         a = PyLong_AsLong(a_tmp);
      |                           ^~~~~
      |                           |
      |                           PyArrayObject * {aka struct tagPyArrayObject *}
In file included from /usr/include/python3.8/Python.h:98,
                 from tmp_wrapper.c:6:
/usr/include/python3.8/longobject.h:23:32: note: expected ‘PyObject *’ {aka ‘struct _object *’} but argument is of type ‘PyArrayObject *’ {aka ‘struct tagPyArrayObject *’}
   23 | PyAPI_FUNC(long) PyLong_AsLong(PyObject *);
      |                                ^~~~~~~~~~

  warnings.warn(UserWarning(err))
```

**Expected behavior**
The value should be collected into a `PyObject*` and only converted to a `PyArrayObject*` once we know that it is an array

**Language**
Fortran/C

**Comment by EmilyBourne** [comment]
Blocked by #886

**Comment by EmilyBourne** [comment]
@bauom This issue needs fixing before adding code to pass cuda arrays to functions

**Comment by bauom** [comment]
I will take a look on it to see if i can fix it.

**Comment by EmilyBourne** [comment]
I'm happy to do it (I just created a branch with a failing test). But if you want to learn more about the c wrapper you can try to start there ^^. I'm not sure it's the easiest starting point though

**Comment by bauom** [comment]
I did find it a bit taxing to follow the code a bit :sweat_smile:  i will follow what you will do to get an idea and try to implement the cuda parts.

**Comment by EmilyBourne** [comment]
> I did find it a bit taxing to follow the code a bit sweat_smile i will follow what you will do to get an idea and try to implement the cuda parts.

If you have the C code, then there should only be a few lines in the wrapper at the points that I indicated in the PR, to get cuda working. Let me know once you've written the code and we can go through it together if you want.

I think it would be a good idea for you to do the initial review of  PR #1278 to get some basic familiarity with the code
