### ISSUE TITLE
Variables in different functions considered equal if they have the same name

### ISSUE THREAD

**Issue by EmilyBourne** [pyccel/pyccel#910]
**Describe the bug**
If a variable is returned and a function call calls a function with an argument with the same name the 2 variables are confused which can lead to `stored_in_c_pointer` returning the wrong result

**To Reproduce**
Provide code to reproduce the behavior:
```python
def f(x : int, y : int):
    print(x,y)

def g():
    x = 0
    y = 1
    f(x,y)
    return x,y
```

Provide the generated code, or the error message:
```bash/fortran/c
#include "tmp.h"
#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>

/*........................................*/
void f(int64_t x, int64_t y)
{
    printf("%ld %ld\n", x, y);
}
/*........................................*/
/*........................................*/
int g(int64_t *x, int64_t *y)
{
    (*x) = 0;
    (*y) = 1;
    f(x, y);
    return 0;
}
/*........................................*/
```

**Expected Solution**
The value should be passed to the function expecting a value, not the pointer, i.e:
```bash/fortran/c
#include "tmp.h"
#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>

/*........................................*/
void f(int64_t x, int64_t y)
{
    printf("%ld %ld\n", x, y);
}
/*........................................*/
/*........................................*/
int g(int64_t *x, int64_t *y)
{
    (*x) = 0;
    (*y) = 1;
    f(*x, *y);
    return 0;
}
/*........................................*/
```

**Language**
C

**Comment by yguclu** [comment]
How should the correct C code look like in your example? Should `f(x, y)` be replaced with `f(*x, *y)`?

**Comment by EmilyBourne** [comment]
> How should the correct C code look like in your example? Should `f(x, y)` be replaced with `f(*x, *y)`?

Yes exactly, I have updated the description to describe this
