### ISSUE TITLE
PGI/Nvidia/Intel fortran compilers cause seg faults when functions have optional arguments

### ISSUE THREAD

**Issue by EmilyBourne** [pyccel/pyccel#929]
**Describe the bug**
As of Fortran 2018, to not pass a value to an optional arguments in a bind_c function in fortran, the user can pass `NULL`. Pyccel makes use of this fact to avoid large numbers of if/else blocks in the bind_X.f90 file. This capability is built into recent GNU implementations, however it is not available for intel/PGI/nvidia. As a result the files compile but when the function is called from python a segmentation fault is returned.

To fix this we should change how arrays are passed in the cwrapper. This change will also be necessary to fix issue #1117 .
Currently the wrapper for the following function:
```python
def f(a: 'float[:]' = None, b: 'float' = None):
    if a is not None:
        print(a)
    if b is not None:
        print(b)
```
is:
```fortran
  subroutine bind_c_f(n0_a, a, b) bind(c)

    implicit none

    integer(i64), value :: n0_a
    real(f64), intent(in), optional :: a(0:n0_a - 1_i64)
    real(f64), intent(in), optional :: b

    call f(a, b)

  end subroutine bind_c_f
```
Instead it should be:
```fortran
  subroutine bind_c_f(n0_a, a_ptr, b_ptr) bind(c)

    implicit none

    integer(i64), value :: n0_a
    type(c_ptr), value :: a_ptr
    type(c_ptr), value :: b_ptr

    real(f64), pointer :: a(:)
    real(f64), pointer :: b

    if (c_associated(a_ptr)) then
      call c_f_pointer(a_ptr, a, [n0_a])
      if (c_associated(b_ptr)) then
        call c_f_pointer(b_ptr, b)
        call f(a, b)
      else
        call f(a)
      end if
    else
      if (c_associated(b_ptr)) then
        call c_f_pointer(b_ptr, b)
        call f(b = b)
      else
        call f()
      end if
    end if

  end subroutine bind_c_f
```

**Comment by EmilyBourne** [comment]
Some of the classes created in PR #1118 will be useful for this PR. The missing section is essentially the function which takes a `FunctionDef` (f) and returns the necessary if blocks

**Comment by yguclu** [comment]
Do you plan to generate different codes depending on the target compiler? The additional code blocks become increasingly ugly as the number of optional arguments grows.

**Comment by EmilyBourne** [comment]
> Do you plan to generate different codes depending on the target compiler? The additional code blocks become increasingly ugly as the number of optional arguments grows.

I agree that the code is ugly, but this is limited to the C-Fortran wrapper, it does not appear in the generated code. This change is needed to fix #1117 as you can only slice an array which exists, so it should not depend on the compiler

**Comment by yguclu** [comment]
The most recent Intel compilers claim to fully support Fortran 2018, and I expect the others to follow suit.

Do we really want to generate such a messy code in order to support old compilers? The number of branches is `2^N` with `N` being the number of optional arguments.

**Comment by yguclu** [comment]
Regarding #1117 I am not following the reasoning. There is no proper explanation of the problem, nor of the proposed solution.

**Comment by EmilyBourne** [comment]
> The most recent Intel compilers claim to fully support Fortran 2018, and I expect the others to follow suit.

You are more optimistic than I am :sweat_smile: . I work with the Nvidia compilers a lot. Currently it supports Fortran 2003. They will have to finish implementing Fortran 2008 before they think about Fortran 2018. I think it is a shame to exclude this compiler just to avoid branches in the wrapper. We always said that the wrapper didn't need to be optimised as we shouldn't be calling Pyccel functions in a loop anyway, the loop should be inside. So I am not convinced that this is such a huge problem. Is it common to have a large number of optional variables in a low level function? It should also be pointed out that in Pyccel an optional variable is one that has a default value of `None`. Any other default value is handled in the c wrapper.

Regarding #1117 , in order to add slices with optionals as you suggest we would need to do the following:
```fortran
subroutine bind_f(a, n, s)
    double(8), optional intent(inout) :: a(0:n-1)
    integer*4 :: n, s

    call f(a(::s))
end subroutine
```
However the statement `a(::s)` will fail (seg fault or similar) if `a` is not present. Therefore we have to choose:
1. Forbid optional arrays (error raised during translation)
2. Forbid optional slices (error raised in C wrapper)
3. Write the code as suggested above:
```fortran
subroutine bind_f(a, n, s)
    c_pointer, optional intent(in) :: a_ptr
    integer*4 :: n, s
    double(8), pointer :: a(:)

    if c_allocated(a_ptr)
        call c_f_pointer(a_ptr, a, (/ n /))
        call f(a(::s))
    else
        call f()
    end if
end subroutine
```

**Comment by EmilyBourne** [comment]
The final solution is what has been implemented in #1388

**Comment by yguclu** [comment]
Issue #1117 is not about optional arguments though. Can you please explain the problem there?

**Comment by EmilyBourne** [comment]
> Issue #1117 is not about optional arguments though. Can you please explain the problem there?

No it is about strides. As I said above if I apply strides directly without changing the handling of optionals there will be a seg fault. So I could fix strides and cause a bug. Or I can fix this as described which allows me to fix strides

**Comment by EmilyBourne** [comment]
> Can you please explain the problem there?

Done

**Comment by yguclu** [comment]
Thanks, I have a clear picture now.

The day the Nvidia compiler finally supports Fortran 2008, will we be able to interface to our Fortran modules using the facilities provided by `ISO_Fortran_binding.h` instead?

**Comment by EmilyBourne** [comment]
> Thanks, I have a clear picture now.
> 
> The day the Nvidia compiler finally supports Fortran 2018, will we be able to interface to our Fortran modules using the facilities provided by `ISO_Fortran_binding.h` instead?

*2018

When we want to use `ISO_Fortran_binding.h` several changes will be required on the side of the python-c wrapper in order to create the necessary structure. In the c-fortran wrapper changes will also be needed to revert what is done in PR #1388 for this issue. This will be quite limited in scope though and will only concern the following functions:
- https://github.com/pyccel/pyccel/blob/c3eaf109961b1bf68712e7b08882bbf5954f6edb/pyccel/codegen/wrapper/fortran_to_c_wrapper.py#L38-L70
- https://github.com/pyccel/pyccel/blob/c3eaf109961b1bf68712e7b08882bbf5954f6edb/pyccel/codegen/wrapper/fortran_to_c_wrapper.py#L110-L134
- https://github.com/pyccel/pyccel/blob/c3eaf109961b1bf68712e7b08882bbf5954f6edb/pyccel/ast/bind_c.py#L205-L222
