### ISSUE TITLE
Type() function support

### ISSUE THREAD

**Issue by AbdelGhafour69** [pyccel/pyccel#945]
**Describe the bug**
In the use case of Templates, it would be helpful to know the type of a passed argument to a function.

**Test Code**
Provide code which does not currently work but which should do when this issue is fixed:
```python
from numpy import zeros
#$ header template T(float|int)
#$ header function test_fun(T)
def test_fun(a):
    x = zeros(10,dtype= type(a))
```

**Language**
C/Fortran

**Comment by yguclu** [comment]
As a workaround, this code will work as intended:

```python
from numpy import full

#$ header template T(float|int)
#$ header function test_fun(T)
def test_fun(a):
    x = full(10, 0 * a)
```

**Comment by AbdelGhafour69** [comment]
> As a workaround, this code will work as intended:
> 
> ```python
> from numpy import full
> 
> #$ header template T(float|int)
> #$ header function test_fun(T)
> def test_fun(a):
>     x = full(10, 0 * a)
> ```
Thank you for your reply, I think that will do what I need.
