### ISSUE TITLE
Error recursive function C

### ISSUE THREAD

**Issue by zzak00** [pyccel/pyccel#947]
```python
@types('int')
def fibonacci_pycc(n):
    if n < 2:
        return n
    else:
        return fibonacci_pycc(n-1)+fibonacci_pycc(n-2)
fib1 = epyccel(fibonacci_pycc,language='c')
```

```bash/fortran/c
ERROR at annotation (semantic) stage
pyccel:
 |fatal [semantic]: mod_xjklvkhh.py [6,8]| Undefined function (fibonacci_pycc)

```

**Comment by rakati** [comment]
For recursive functions you have to add return type if the function.
`fibo(x:'int' )->'int' :`

**Comment by EmilyBourne** [comment]
I think we should try to add a clearer error message for this. It is not obvious for users who have not encountered this problem before, why you get this error message. Recursive functions which return something are quite a specific use case anad even if someone has thoroughly read the tutorial they could have forgotten this case by the time they encounter it

**Comment by EmilyBourne** [comment]
Actually, when I run the code I get the following error message:
```
ERROR at annotation (semantic) stage
pyccel:
 |fatal [semantic]: tmp.py| A results type must be provided for recursive functions with one of the following three syntaxes:
def FUNC_NAME(arg1_name:arg1_type, ...) -> RESULT_TYPES
@types('ARG_TYPES', results='RESULT_TYPES')
#$ header function FUNC_NAME(ARG_TYPES) results(RESULT_TYPES)
 (fibonacci_pycc(n) -> Out_0001
```

Checking through the version system I see that this error message was improved in version 0.10.1 (the current version is 1.3.1).
@zzak00 I am not sure which version you are using, but I would recommend that you update your version of pyccel to use the latest improvements which includes amongst other things, clearer error messages and better C support
