### ISSUE TITLE
Add copy() method to ndarray

### ISSUE THREAD

**Issue by EmilyBourne** [pyccel/pyccel#980]
**Describe the bug**
The `copy()` function is very useful, but currently does not exist in pyccel. It should be added

**Test Code**
Provide code which does not currently work but which should do when this issue is fixed:
```python
r = s.copy()
```
This should be translated to:
```python
r = np.empty_like(s)
r[:] = s
```

**Comment by EmilyBourne** [comment]
> I agree with you Emily. Maybe we should extend this Issue since other datatypes covered by Pyccel, do offer the same method. In general, what are the datatypes for which `copy` is implemented in Pyccel?

Currently there aren't any. But currently the only non-scalar types officially implemented by pyccel are:
- ndarray
- tuples (which are constant so copy is unnecessary)

**Comment by EmilyBourne** [comment]
What datatypes did you have in mind?

**Comment by ratnania** [comment]
In fact, i was thinking of a more general implementation that will propagate the method copy if the datatype allows it.
As you know, there are two ways of doing a copy in python, using a method or the function copy from the stdlib
