### ISSUE TITLE
Pyccel prints forbidden fortran aliasing

### ISSUE THREAD

**Issue by EmilyBourne** [pyccel/pyccel#981]
# The bug
Fortran has several restrictions on how arguments can be passed. Pyccel does not pay attention to these restrictions when printing. This can therefore lead to code which produces unexpected input

# Example
## Python code:
```python
def mod_values(x : int):
    return x+2,x+3

if __name__ == '__main__':
    a = 3
    b = 4
    c = 5
    a,d = mod_values(a)
    b,e = mod_values(b)
    c,f = mod_values(c)

    print(a)
    print(b)
    print(c)
    print(d)
    print(e)
    print(f)
```

## Fortran code
```fortran
module tmp


  use, intrinsic :: ISO_C_Binding, only : i64 => C_INT64_T
  implicit none

  contains

  !........................................
  subroutine mod_values(x, Out_0001, Out_0002)

    implicit none

    integer(i64), intent(out) :: Out_0001
    integer(i64), intent(out) :: Out_0002
    integer(i64), value :: x

    Out_0001 = x + 2_i64
    Out_0002 = x + 3_i64
    return

  end subroutine mod_values
  !........................................

end module tmp
```
```fortran
program prog_prog_tmp

  use tmp

  use, intrinsic :: ISO_C_Binding, only : i64 => C_INT64_T
  implicit none

  integer(i64) :: a
  integer(i64) :: b
  integer(i64) :: c
  integer(i64) :: d
  integer(i64) :: e
  integer(i64) :: f

  a = 3_i64
  b = 4_i64
  c = 5_i64
  call mod_values(a, Out_0001 = a, Out_0002 = d)
  call mod_values(b, Out_0001 = b, Out_0002 = e)
  call mod_values(c, Out_0001 = c, Out_0002 = f)
  print *, a
  print *, b
  print *, c
  print *, d
  print *, e
  print *, f

end program prog_prog_tmp
```

## Python Output
```bash
5
6
7
6
7
8
```

## Fortran Output
```bash
                    2
                    6
                    7
                    3
                    7
                    8
```

## Explanation
The variable `x` is assigned to 2 argument variables. One with intent `in`, and one with intent `out`. Intent `out` means that the current value of `x` can be discarded while `in, value` means that it is used and copied into the argument variable. These statements are contradictory 

# Expected behaviour
When a variable is passed to multiple arguments of a function and those arguments have conflicting intents (i.e. `out` and anything else), a copy must be made of the variable before/after the call

# Language
Fortran

**Comment by yguclu** [comment]
I've noticed that the example code can be fixed by simply changing `intent(in)` with `intent(inout)`.

**Comment by yguclu** [comment]
It appears that we have no such problem for arrays in Fortran, because we never print array arguments with `intent(out)`. Let's take this code as an example:
```python
def incr(x : 'int[:]', y : 'int[:]'):
    x[:] += y
    return y.sum()


if __name__ == '__main__':

    import numpy as np

    a = np.ones(10, dtype=int)
    print(a)

    x = incr(a, a)
    print(a)
    print(x)
```
Although the generated code compiles with `gfortran` and returns the correct output, it modifies an aliased array and hence it violates the Fortran standard:
```f90
module test_dummy


  use, intrinsic :: ISO_C_Binding, only : i64 => C_INT64_T
  implicit none

  contains

  !........................................
  function incr(x, y) result(Out_0001)

    implicit none

    integer(i64) :: Out_0001
    integer(i64), intent(inout) :: x(0:)
    integer(i64), intent(in) :: y(0:)

    x(:) = x(:) + y
    Out_0001 = sum(y)
    return

  end function incr
  !........................................

end module test_dummy
```

```f90
program prog_prog_test_dummy

  use test_dummy

  use, intrinsic :: ISO_C_Binding, only : i64 => C_INT64_T
  implicit none

  integer(i64), allocatable :: a(:)
  integer(i64) :: x

  allocate(a(0:9_i64))
  a = 1_i64
  print *, a
  x = incr(a, a)
  print *, a
  print *, x
  if (allocated(a)) then
    deallocate(a)
  end if

end program prog_prog_test_dummy
```
Python output:
```bash
$ python3.7 test_dummy.py 
[1 1 1 1 1 1 1 1 1 1]
[2 2 2 2 2 2 2 2 2 2]
20
```
Fortran output
```bash
$ ./test_dummy
                    1                    1                    1                    1                    1                    1                    1                    1                    1                    1
                    2                    2                    2                    2                    2                    2                    2                    2                    2                    2
                   20
```

**Comment by EmilyBourne** [comment]
@yguclu For arrays we do not currently have a problem, but we will as soon as issue #537 is fixed. I agree that your example might cause problems with some compilers. This issue is slightly different to the one handled in PR #1013 . PR #1013 handles aliasing with `intent(out)` variables. In this case creating a copy is sufficient, however for arrays as arguments the problem is somewhat different. As python passes references to variables rather than copies creating a copy would lead to wrong results. However in this case, I am not sure what we can do to avoid the illegal aliasing beyond raising a warning for the user?

**Comment by EmilyBourne** [comment]
In fact the problem with arrays already exists for instances of classes
